<?php 
/**
 * Pandamp
 * 
 * @author		2012-2013 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: dc.excel.phtml 1 2012-10-09 20:24Z $
 */
?>
<?php

error_reporting(E_ERROR | E_WARNING | E_PARSE);
		
require_once("Spreadsheet/Excel/Writer/Format.php");
require_once("Spreadsheet/Excel/Writer/BIFFwriter.php");
require_once("Spreadsheet/Excel/Writer/Worksheet.php");
require_once("Spreadsheet/Excel/Writer/Workbook.php");
require_once("Spreadsheet/Excel/Writer/Parser.php");
require_once("Spreadsheet/Excel/Writer.php");

