<!-- Header -->
<header id="top">
    <div class="wrapper">
        <!-- Title/Logo - can use text instead of image -->
        <div id="title"><img src="<?php echo $this->cdn('images'); ?>/logo.png" alt="hukumonline" /><!--<span>CMS Hukumonline</span>--></div>
        <!-- Top navigation -->
        <?php echo $this->action('topnav','index','admin'); ?>
        <!-- End of Top navigation -->
        <!-- Main navigation -->
        <nav id="menu">
            <ul class="sf-menu sf-js-enabled sf-shadow">
                <li class="current"><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/dms">Dms</a></li>
                <?php if ($this->isAllowed('store','all')) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/store">Store</a></li>
                <?php } if ($this->isAllowed('membership','all')) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/customer/user/list">User</a></li>
                <?php } if ($this->aclCheck('action','all','content','aclist')) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/acl">Access Control</a></li>
                <?php } if ($this->aclCheck('action','all','content','all-access')) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/search">Search</a></li>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/setting">Setting</a></li>
                <?php } ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/report">Report</a></li>
            </ul>
        </nav>
        <!-- End of Main navigation -->
        <!-- Aside links -->
        <aside>
            <?php if ($this->getLanguage() == "id") { ?>
            <a href="<?php echo ROOT_URL; ?>/en">English</a> &middot; <b>Indonesia</b>
            <?php } else { ?>
            <b>English</b> &middot; <a href="<?php echo ROOT_URL; ?>/id">Indonesia</a>
            <?php } ?>
        </aside>
        <!-- End of Aside links -->
    </div>
</header>
<!-- End of Header -->
<!-- Page title -->
<div id="pagetitle">
    <div class="wrapper">
        <h1>Dashboard</h1>
        <!-- Quick search box -->
        <form id="frmSearch" method="get" action="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse">
			<select name="category" id="category">
                <option value="all">All</option>
                <option value="article">Artikel</option>
                <option value="isuhangat">Isu Hangat</option>
                <option value="comment">Komentar</option>
                <option value="klinik">Klinik</option>
                <option value="kutu_putusan">Putusan</option>
                <option value="(kutu_peraturan_kolonial OR kutu_rancangan_peraturan OR kutu_peraturan)">Peraturan</option>
            </select>    
            <input class="" id="q" name="q" type="text" value="<?php echo $this->layout()->searchQuery; ?>">
            <input type="hidden" id="sLimit" name="sLimit" value="25">
            <input type="hidden" id="sOffset" name="sOffset" value="<?php echo $this->sOffset; ?>">
        </form>
    </div>
</div>
<!-- End of Page title -->