<!-- Left column/section -->
<section class="column width6 first">

        <div class="colgroup leading">
            <div class="column width3 first">
                <h3>Welcome back, <a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/edit/id/<?=$this->user->kopel;?>"><?=$this->user->username;?></a></h3>
            </div>
            <div class="column width3">
                <h4>Last login</h4>
                <p>
                    <?=$this->lastLogin();?><br>
                </p>
            </div>
        </div>

        <div class="colgroup leading">
            <div class="column width3 first">
                <h4>Invoices: <a href="#">10</a></h4>
                <hr/>
                <table class="no-style full">
                    <tbody>

                    <tr>
                        <td>Total Invoices</td>
                        <td class="ta-right"><a href="#">10</a></td>
                        <td class="ta-right">1,322.10</td>
                    </tr>
                    <tr>
                        <td>Total Paid</td>

                        <td class="ta-right"><a href="#">9</a></td>
                        <td class="ta-right">900.00</td>
                    </tr>
                    <tr>
                        <td>Total Due</td>
                        <td class="ta-right"><a href="#">1</a></td>
                        <td class="ta-right">422.10</td>

                    </tr>
                    <tr>
                        <td>Total Overdue</td>
                        <td class="ta-right">0</td>
                        <td class="ta-right">0.00</td>
                    </tr>
                    </tbody>

                </table>
            </div>
            <div class="column width3">
                <h4>Sales: <a href="#">1</a></h4>
                <hr/>
                <table class="no-style full">
                    <tbody>
                    <tr>
                        <td>Clients This Month</td>
                        <td class="ta-right"><a href="#">1</a></td>
                        <td class="ta-right"></td>
                    </tr>
                    <tr>
                        <td>Sales This Month</td>
                        <td class="ta-right"><a href="#">9</a></td>

                        <td class="ta-right">900.00</td>
                    </tr>
                    <tr>
                        <td>Clients Total</td>
                        <td class="ta-right"><a href="#">5</a></td>
                        <td class="ta-right"></td>
                    </tr>
                    <tr>
                        <td>Sales Total</td>
                        <td class="ta-right"><a href="#">9</a></td>
                        <td class="ta-right">900.00</td>
                    </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <div class="colgroup leading">
            <div class="column width6 first">
                <?=$this->action('approval','user','customer');?>
            </div>
        </div>

        <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?=$this->action('sidebar','user','customer');?>
    </div><br/>
    <div id="showDiv1" style="width:100%;text-align:center;">
    <? if ($this->getLanguage() == "id") { 
    $this->action('browse','manager','agenda'); 
    }
    ?>
    <?//=$this->ajaxActionRenderer(ROOT_URL.'/'.$this->getLanguage().'/agenda/manager/browse');?>
    </div>
    <?=$this->action('view','manager','polling');?>
</aside>
<!-- End of Right column/section -->
