<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?=$tag;?>" target="_blank" title="Search <?=$tag;?>"><?=$tag;?></a></h3>
            <p>
                <a href="" id="indexing" class="btn">Indexing</a>
            </p>
            <p>
                <label for="loadsolr">Load http://</label>
                <input id="url" class="half" value="<?=$this->solrWriteDir;?>" readonly />
            </p>
            <p>
                <label for="timeout">with&nbsp;timeout </label>
                <input id="timeout" value="10000" size="10"> ms
            </p>
            <br>
            <div id="status"></div><br>
            <iframe width="100%" height="700"></iframe>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?=$this->action('sidebar','user','customer');?>
    </div>
</aside>
<!-- End of Right column/section -->

