<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?=$tag;?>" target="_blank" title="Search <?=$tag;?>"><?=$tag;?></a></h3><br />
            <p>
                <a href="javascript:;" id="indx" class="btn">Indexing</a>
            </p><br>
            <p>
                <label for="loadsolr">Load http://</label>
                <input id="url" class="half" value="<?=$this->solrWriteDir;?>" readonly />
            </p>
            <p>
                <label for="timeout">with&nbsp;timeout </label>
                <input id="timeout" value="10000" size="10"> ms
            </p>
            <br>
            <div id="status"></div><br>
            <iframe width="100%" height="700"></iframe>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?=$this->action('sidebar','user','customer');?>
    </div>
</aside>
<!-- End of Right column/section -->

<script type="text/javascript">
$(document).ready(function(){
    $("#status").hide();
    $("#indx").click(function(){
        $.ajax({
            url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/setting/cekstatus/format/json",
            type: 'POST',
            dataType: 'json',
            success:function(json){
                if( json.success == true ) {
                    if (confirm("In order indexing to run properly, change website status into Offline.")) {
                        $.post('<?=ROOT_URL;?>/admin/setting/change-status/status/offline/format/json',function(){
                            $("#status").show().html("Loading ...");
                            $("iframe").src("<?=ROOT_URL;?>/<?=$this->getLanguage();?>/search/manager/reindex", function(duration){
                                $("#status").blink("Loaded in " + duration + "ms");

                            }, {
                                timeout: $("#timeout").val(),
                                onTimeout: function() { $("#status").blink("Timed out!"); }
                              }
                            );
                        });
                    }
                    
                } else {
                    if (confirm("Are you sure?")) {
                        $("#status").show().html("Loading ...");
                        $("iframe").src("<?=ROOT_URL;?>/<?=$this->getLanguage();?>/search/manager/reindex", function(duration){
                            $("#status").blink("Loaded in " + duration + "ms");

                        }, {
                            timeout: $("#timeout").val(),
                            onTimeout: function() { $("#status").blink("Timed out!"); }
                          }
                        );
                    }

                }
            }
        }
        );


        return false;
    });

    $.fn.blink = function(message) {
      $(this).animate({opacity: 0.01}, 200, function() {
        $(this).html(message).show(); $(this).animate({opacity:1}, 200, function() {
          $(this).animate({opacity: 0.1}, 200, function() {
            $(this).animate({opacity: 1}, 200)
          })
        })
      });
    }

	
});
</script>
