<?php 
$this->headLink()
	->appendStylesheet($this->cdn('scripts') . '/plugins/iCheck/flat/blue.css');

$this->headScript()
	->appendFile($this->cdn('scripts') . '/plugins/iCheck/icheck.min.js');

?>

<section class="content-header">
<?php echo $this->breadcrumbs->render(); ?>
</section>
<!-- Select Profile -->
<div id="dialog-catalog" class="hide">
	<h4>Profile:</h4>
	<?php echo $this->profile(null,true); ?>
</div>
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<form method="post" action="" name="catalogForm" id="catalogForm" class="form-horizontal" role="form">
					<div class="box-header with-border">
						<h3 class="box-title">&nbsp;</h3>
						<div class="box-tools pull-left">
						
						</div>	
					</div>
					<div class="box-body no-padding">
						<div class="mailbox-controls">
							<a href="javascript:;" class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></a>
							<div class="btn-group">
								<a href="javascript:;" class="btn btn-default btn-sm deletecatalog"><i class="fa fa-trash-o"></i> Delete</a>
								<a href="javascript:;" class="btn btn-default btn-sm editcatalog"><i class="fa fa-edit"></i> Edit</a>
								<a href="javascript:;" id="newcatalog" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Add New</a>
							</div>
							<a href="javascript:;" class="btn btn-default btn-sm copycatalog"><i class="fa fa-copy"></i> Copy</a>
							<a href="javascript:;" class="btn btn-default btn-sm movecatalog"><i class="fa fa-exchange"></i> Move</a>
							<div class="pull-right">
								<?php
									$start=($this->paginator['current']-1)*$this->limit;
									$s1=$start+1;
									$position = $this->paginator['current'] * $this->limit;
								?>
								<?php echo $s1.'-'.$position; ?>/<?php echo $this->totalItems; ?>
								<div class="btn-group">
								<?php if(isset($this->paginator['previous'])): ?>
								<a class="btn btn-default btn-sm" href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $this->currentNode; ?>/page/<?php echo $this->paginator['previous']; ?>"><i class="fa fa-chevron-left"></i></a>
								<?php else: ?>
								<a class="btn btn-default btn-sm disabled"><i class="fa fa-chevron-left"></i></a>
								<?php endif; ?>
								
								<?php if(isset($this->paginator['next'])): ?>
								<a class="btn btn-default btn-sm" href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $this->currentNode; ?>/page/<?php echo $this->paginator['next']; ?>"><i class="fa fa-chevron-right"></i></a>
								<?php else: ?>
								<a class="btn btn-default btn-sm disabled"><i class="fa fa-chevron-right"></i></a>
								<?php endif; ?>
								</div>
							</div>
						</div>
						<div class="table-responsive mailbox-messages">
							<table class="table table-hover table-striped">
								<?php $now = date('Y-m-d H:i:s'); ?>
								<?php foreach ($this->rowset as $row) : ?>
								<tbody>
									<td><input type="checkbox" name='catalogGuid[]' id='catalogGuid' value='<?php echo $row->guid; ?>'></td>
									<td class="mailbox-star">
									<?php
									if ($now <= $row->publishedDate && $row->status == 99) {
										$status = "publish_y";
										$ht = "Published, but is Pending";
									}
									else if (($now <= $row->expiredDate || $row->expiredDate == '0000-00-00 00:00:00') && $row->status == 99) {
										$status = "publish_g";
										$ht = "Published and is Current";
									}
									else if ($now > $row->expiredDate && $row->status == 99) {
										$status = "publish_r";
										$ht = "Published, but has Expired";
									}
									else if ($row->status == 0) {
										$status = "publish_x";
										$ht = "Draft";
									}
									else if ($row->status == -1) {
										$status = "disabled";
										$ht = "Archived";
									}
									else if ($row->status == 2) {
										$status = "exclamation";
										$ht = "UnPublished";
									}
									else if ($row->status == 1) {
										$status = "cancel";
										$ht = "Not Applicable";
									}
									else if ($row->status == -2) {
										$status = "delete";
										$ht = "Deleted";
									}
									
									?>
									<span title="<?php echo $ht; ?>">
										<img class="middle" src="<?php echo $this->cdn('images'); ?>/<?php echo $status; ?>.png">
									</span>
									
									</td>
									<td class="mailbox-name"><?php echo $row->createdBy; ?></td>
									<td class="mailbox-subject">
										<?php if ($row->profileGuid == 'kutu_doc') : ?>
										<a href="">File: <?php echo $this->getCatalogAttribute($row->guid,'fixedTitle'); ?></a>
										<?php elseif ($row->profileGuid == 'clinic' || $row->profileGuid == 'klinik') : ?>
										<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $row->guid; ?>/node/<?php echo $this->currentNode; ?>" target="_blank"><?php echo $this->getCatalogAttribute($row->guid,'fixedCommentTitle'); ?></a>
										<?php elseif ($row->profileGuid == 'comment') : ?>
										<a href=""><?php echo $this->getCatalogAttribute($row->guid,'fixedJudul'); ?></a>
										<?php else : ?>
										<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $row->guid; ?>/node/<?php echo $this->currentNode; ?>" target="_blank"><?php echo $this->getCatalogAttribute($row->guid,'fixedTitle'); ?></a>
										<?php endif; ?>
									
									</td>
									<td class="mailbox-date"><?php if (isset($row->createdDate) && ($row->createdDate != "0000-00-00 00:00:00")) : echo Pandamp_Lib_Formater::get_date($row->createdDate); endif; ?></td>
								</tbody>
								<?php endforeach; ?>
							</table>
						</div>
					</div>
					<div class="box-footer no-padding">
						<div class="mailbox-controls">
							<div class="form-inline" style="float:left">
								<div class="btn-group">
									<label>Show
										<select name="showperpage" id="showperpage" onchange="this.form.submit()" class="form-control">
											<?php if ($this->totalItems < 11) { ?>
											<option value="10">10 rows</option>
											<?php } else if ($this->totalItems < 26) { ?>
											<option value="10">10 rows</option>
											<option value="25">25 rows</option>
											<?php } else if ($this->totalItems < 51) { ?>
											<option value="10">10 rows</option>
											<option value="25">25 rows</option>
											<option value="50">50 rows</option>
											<?php } else if ($this->totalItems < 101) { ?>
											<option value="10">10 rows</option>
											<option value="25">25 rows</option>
											<option value="50">50 rows</option>
											<option value="100">100 rows</option>
											<?php } else if ($this->totalItems < 251) { ?>
											<option value="10">10 rows</option>
											<option value="25">25 rows</option>
											<option value="50">50 rows</option>
											<option value="100">100 rows</option>
											<option value="250">250 rows</option>
											<?php } else { ?>
											<option value="10">10 rows</option>
											<option value="25">25 rows</option>
											<option value="50">50 rows</option>
											<option value="100">100 rows</option>
											<option value="250">250 rows</option>
											<option value="500">500 rows</option>
											<?php } ?>
										</select>
									</label>
								</div>
								<div class="btn-group">
									<label>Status
										<?php echo $this->catalogStatus(array('id' => 'status', 'name' => 'status', 'class' => 'form-control')); ?>
									</label>
								</div>
								<div class="btn-group">
									<label>Sort
										<select name="sortby" id="sortby" onchange="this.form.submit()" class="form-control">
											<option value="createdDate asc">createdDate A TO Z</option>
											<option value="createdDate desc">createdDate Z TO A</option>
											<option value="publishedDate asc">publishedDate A To Z</option>
											<option value="publishedDate desc">publishedDate Z To A</option>
										</select>
									</label>
								</div>
							</div>
							<div class="pull-right">
								<?php
									$start=($this->paginator['current']-1)*$this->limit;
									$s1=$start+1;
									$position = $this->paginator['current'] * $this->limit;
								?>
								<?php echo $s1.'-'.$position; ?>/<?php echo $this->totalItems; ?>
								<div class="btn-group">
								<?php if(isset($this->paginator['previous'])): ?>
								<a class="btn btn-default btn-sm" href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $this->currentNode; ?>/page/<?php echo $this->paginator['previous']; ?>"><i class="fa fa-chevron-left"></i></a>
								<?php else: ?>
								<a class="btn btn-default btn-sm disabled"><i class="fa fa-chevron-left"></i></a>
								<?php endif; ?>
								
								<?php if(isset($this->paginator['next'])): ?>
								<a class="btn btn-default btn-sm" href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $this->currentNode; ?>/page/<?php echo $this->paginator['next']; ?>"><i class="fa fa-chevron-right"></i></a>
								<?php else: ?>
								<a class="btn btn-default btn-sm disabled"><i class="fa fa-chevron-right"></i></a>
								<?php endif; ?>
								</div>
							</div>
							
						</div>
						
					</div>
				</form>
			</div>		
		</div>
	</div>
</section>
<?php $this->headScript()->captureStart(); ?>
$(function () {
    $("#showperpage").val('<?php echo $this->layout()->showperpage; ?>');
    $("#status").val('<?php echo $this->layout()->status; ?>');
    $("#sortby").val('<?php echo $this->sortby; ?>');
    
	$('.mailbox-messages input[type="checkbox"]').iCheck({
		checkboxClass: 'icheckbox_flat-blue',
		radioClass: 'iradio_flat-blue'
	});

	//Enable check and uncheck all functionality
	$(".checkbox-toggle").click(function () {
		var clicks = $(this).data('clicks');
		if (clicks) {
			//Uncheck all checkboxes
			$(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
			$(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
		} else {
			//Check all checkboxes
			$(".mailbox-messages input[type='checkbox']").iCheck("check");
			$(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
		}
		$(this).data("clicks", !clicks);
	});
	
	$("#newcatalog").click(function(){
		var dialogcatalog = $( "#dialog-catalog" ).removeClass('hide').dialog({
			width: 420,
			modal: true,
			title: "New Catalog",
			buttons: [{
				text: "Cancel",
				"class" : "btn btn-xs",
				click: function() {
					$(this).dialog("close");
				}
			},
			{
				text: "OK",
				"class" : "btn btn-primary btn-xs",
				click: function() {
					var idPredefineDetail=$(this).closest( "#dialog-catalog" ).children("select[name=pg]").val();
					if (idPredefineDetail) {
						window.location = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/new/profile/"+idPredefineDetail+"/node/<?php echo $this->currentNode; ?>";
					}
				}
			}
			]
		});
	});
	
	$(".editcatalog").click(function() {
		var ids = new Array();
		$('input[type="checkbox"]:checked').each(function() {
			ids.push($(this).val());
		});

		for(var i = 0; i< ids.length; i++){
			var href = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/edit/guid/"+ids[i]+"/node/<?php echo $this->currentNode; ?>";
			window.open(href,"_blank");
		}
		
		return false;
	});

	$(".deletecatalog").click(function() {
		checkValues = new Array();
		a=0;
    	$('input[type="checkbox"]:checked').each(function(){
        	checkValues[a]=$(this).val();
        	a++;
		});	
		if(checkValues.length==0)
        {
        	alert('NO CATALOG SELECTED');
            return false;
        }
		window.location = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/delete-confirm/guid/"+checkValues;
	});
	
	$(".copycatalog").click(function() {
		checkValues = new Array();
		a=0;
    	$('input[type="checkbox"]:checked').each(function(){
        	checkValues[a]=$(this).val();
        	a++;
		});
		if(checkValues.length==0)
        {
        	alert('NO CATALOG SELECTED');
            return false;
        }
		window.location = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/copy-folder/guid/"+checkValues;	
	});

	$(".movecatalog").click(function() {
		checkValues = new Array();
		a=0;
    	$('input[type="checkbox"]:checked').each(function(){
        	checkValues[a]=$(this).val();
        	a++;
		});
		if(checkValues.length==0)
        {
        	alert('NO CATALOG SELECTED');
            return false;
        }
		window.location = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/move-folder/sourceNode/"+currentNode+"/guid/"+checkValues;	
	});

});
<?php $this->headScript()->captureEnd(); ?>