<?php if ($this->getCountShortener($this->guid)) : ?>
<div class="box box-solid">
	<div class="box-header with-border">
		<h3 class="box-title">Shortener URL</h3>
		<div class="box-tools">
			<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<div class="box-body no-padding">
		<ul class="nav nav-pills nav-stacked">
			<li class="active"><a href="<?php echo $this->shortUrl; ?>" target="_blank"><i class="fa fa-skype"></i> <?php echo basename($this->shortUrl); ?> <span class="label label-primary pull-right"><?php echo $this->getCountShortener($this->guid); ?></span></a></li>
		</ul>
	</div>
</div>
<?php endif; ?>