<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>

            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <h5>Hukumonline Comment</h5>
            <h6><a href="javascript:void(0);" id="deleteAction">delete</a></h6>
            <div class="box box-success" id="message"></div>
            <table class="display stylized" id="holcomment">
                <thead>
                    <th width="5%"><input name="select_deselect" id="select_deselect" type="checkbox"></th>
                    <th>Comment</th>
                    <th>Created on</th>
                    <th>Status</th>
                </thead>
                <tbody>

                    <?php $i=$this->offset+1; foreach ($this->commentList as $comment) { ?>
                    <tr class="<?php echo ($i%2 ? 'gradeX' : 'gradeC'); ?>" id="row_<?php echo $comment->id; ?>">
                        <td><input type='checkbox' name='cid[]' id='cid' value='<?php echo $comment->id; ?>' class="check_me"></td>
                        <td>
                            <a href="http://www.hukumonline.com/berita/baca/<?php echo $comment->object_id; ?>/<?php echo $this->getCatalogShortTitle($comment->object_id); ?>#comments" title="<?php echo $comment->email; ?>" target="_blank"><?php echo $comment->title; ?></a>
                            <br><small>id:<?php echo $comment->id; ?> - by: <?php echo $comment->name; ?></small>
                            <br><?php echo $comment->comment; ?>
                            <br><a href="<?php echo $comment->id; ?>" class="delete">delete</a>
                        </td>
                        <td><?php echo Pandamp_Lib_Formater::get_date($comment->date); ?>
                        <br><small>ip:<?php echo $comment->ip; ?></small>
                        </td>
                        <td nowrap>
                        <?php if ($comment->published == 99) { ?>
                            
                            <a href="<?php echo $comment->id; ?>/st/0" class="status">Active</a>
                            
                        <?php } else { ?>
                            
                            <a href="<?php echo $comment->id; ?>/st/1" class="status">Not Active</a>
                        
                        <?php } ?>
                        </td>
                    </tr>
                    <?php $i++; } ?>

                </tbody>
            </table>
            <table width='100%'>
            <tr>
                <td align=right><div id='commentPagination' class="pagination"></div></td>
            </tr>
            </table>
        </div>
    </div>

	<div id="confirmDialog" style="display:none"></div>
    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div><br>
</aside>
<!-- End of Right column/section -->