<?php 
$this->headLink()
	->appendStylesheet($this->cdn('scripts') . '/plugins/iCheck/flat/blue.css');

$this->headScript()
	->appendFile($this->cdn('scripts') . '/plugins/iCheck/icheck.min.js');

?>
<section class="content-header">
	<h1>Comment <small>Below are the list of comment:</small></h1>
    <ol class="breadcrumb">
		<li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/comment/catalog/browse"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Comment</li>
    </ol>
</section>
<?php if ($this->paginator->getTotalItemCount() == 0) : ?>
Not found any comment <br />
<?php else : ?>
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-body no-padding">
					<div class="mailbox-controls">
						<button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
						<button class="btn btn-default btn-sm delete"><i class="fa fa-trash-o"></i> Delete</button>
						<div class="pull-right">
							<?php
							$start=($this->currentPageNumber-1)*$this->perpage;
							$s1=$start+1;
							$position = $this->currentPageNumber * $this->perpage;
							?>
							<?php echo $s1.'-'.$position; ?>/<?php echo $this->paginator->getTotalItemCount(); ?>
							<?php echo $this->paginationControl($this->paginator,'Sliding','partial/post2pagination.phtml'); ?>
						</div>
					</div>
					<div class="table-responsive mailbox-messages">
						<table class="table table-hover table-striped">
						<?php foreach ($this->commentList as $comment) : ?>
						<tbody>
							<tr id="commentRow_<?php echo $comment->id; ?>">
							<td><input type="checkbox" name='cid[]' id='cid' value='<?php echo $comment->id; ?>'></td>
							<td class="mailbox-star">
								<a href="http://www.hukumonline.com/berita/baca/<?php echo $comment->object_id; ?>/<?php echo $this->getCatalogShortTitle($comment->object_id); ?>#comments" title="<?php echo $comment->email; ?>" target="_blank"><?php echo $comment->title; ?></a>
								<br><small>id:<?php echo $comment->id; ?> - by: <?php echo $comment->name; ?></small>
								<br><?php echo $comment->comment; ?>
								<br><a href="<?php echo $comment->id; ?>" class="delete"><i class="fa fa-remove"></i> delete</a>
							</td>
							<td class="mailbox-subject"><?php echo Pandamp_Lib_Formater::get_date($comment->date); ?>
							<br><small>ip:<?php echo $comment->ip; ?></small>
							</td>
							<td>
								<?php if ($comment->published == 99) : ?>
								<a href="<?php echo $comment->id; ?>/st/0" class="status">Active</a>
								<?php else : ?>
								<a href="<?php echo $comment->id; ?>/st/1" class="status">Not Active</a>
								<?php endif; ?>
							</td>
							</tr>
						</tbody>
						<?php endforeach; ?>
						</table>
					</div>
				</div>
				<div class="box-footer no-padding">
					<div class="mailbox-controls">
						<button class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i></button>
						<button class="btn btn-default btn-sm delete"><i class="fa fa-trash-o"></i> Delete</button>
						<div class="pull-right">
							<?php
							$start=($this->currentPageNumber-1)*$this->perpage;
							$s1=$start+1;
							$position = $this->currentPageNumber * $this->perpage;
							?>
							<?php echo $s1.'-'.$position; ?>/<?php echo $this->paginator->getTotalItemCount(); ?>
							<?php echo $this->paginationControl($this->paginator,'Sliding','partial/post2pagination.phtml'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<?php $this->headScript()->captureStart(); ?>
$(function () {
	$('.mailbox-messages input[type="checkbox"]').iCheck({
		checkboxClass: 'icheckbox_flat-blue',
		radioClass: 'iradio_flat-blue'
	});

	//Enable check and uncheck all functionality
	$(".checkbox-toggle").click(function () {
		var clicks = $(this).data('clicks');
		if (clicks) {
			//Uncheck all checkboxes
			$(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
			$(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
		} else {
			//Check all checkboxes
			$(".mailbox-messages input[type='checkbox']").iCheck("check");
			$(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
		}
		$(this).data("clicks", !clicks);
	});

	$('.status').click(function(){
		var removeId = $(this).attr('href'),
            qString = removeId.split('/'),
            cId = qString[0];

		if (confirm("Are you sure?")) {
			window.location = '<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/comment/catalog/status/id/'+removeId;
		}

		return false;
	});
	
	$('.delete').click(function(){
        var removeId = $(this).attr('href');

		if (confirm("Are you sure?")) {
        	window.location = '<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/comment/catalog/delete/id/'+removeId;
    	}

    	return false;
    });
	
	$('#deleteAction').click(function() {
		var numSelected = $('input[type="checkbox"]:checked').length;
		var self = this;
		if (0 == numSelected) {
			alert('Please select at least one comment');
		}
		else
		{
			var ids = new Array();
			$('input[type="checkbox"]:checked').each(function() {
            	ids.push($(this).val());
            });
            
            $.ajax({
   				url: "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/comment/catalog/delcom",
   				type: 'POST',
   				data: { id: $.toJSON(ids) },
                beforeSend: function()
                {
   					for (var i in ids) {
   						$('#row_' + ids[i]).addClass('loading').text('processing...');
   					}
                },
   				success: function(response) {
   					if ('RESULT_OK' == response) {
   						for (var i in ids) {
  							$('#row_' + ids[i]).fadeOut('slow').removeClass('loading').text('delete');
   						}
   					}
   				}
            });
		}
	});
	
	
                
});
<?php $this->headScript()->captureEnd(); ?>
<?php endif; ?>