<link rel="stylesheet" type="text/css" href="<?php echo $this->cdn('scripts'); ?>/hol/jquery/jstree/tree_component.css" />
<script type="text/javascript" src="<?php echo $this->cdn('scripts'); ?>/hol/jquery/jstree/_lib/css.js"></script>
<script type="text/javascript" src="<?php echo $this->cdn('scripts'); ?>/hol/jquery/jstree/tree_component.js"></script>
<script>
$(document).ready(function() {
    $("#ctf").tree({
          data  : {
            type  : "json",
            url   : "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/folder/getchildreninjson",
            async : true,
            async_data : function (NODE) { return { id : $(NODE).attr("id") || 0, my_param : "my_value" } }
          },
            callback    : {
                    onselect    : function(NODE,TREE_OBJ) {
                        $("#targetNodeTitle").val(TREE_OBJ.selected.text());
                        $("#targetNode").val(TREE_OBJ.selected.attr("id"));
                    }
            },
            cookies : { prefix : "treeCategories", opts : { path : '/' }}
        });


    var message = "<?php echo $this->message; ?>";
    if(message!="")
    {
        alert (message);
    }

});

</script>
<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <a href="<?php echo $this->urlReferer; ?>">Back to Origin Page</a>
        </div>
    </div>
    <div class="colgroup leading">
        <div class="column width3 first">
            <h4>Choose Folders</h4>
            <div id="ctf" class="demo"></div>
        </div>
        <div class="column width3">
            <fieldset>
                <legend>You will COPY the following CATALOG:</legend>
                <strong><?php echo $this->catalogTitle; ?></strong>
            </fieldset>
            <form id="frmCopyToFolder" method="post">
		<fieldset>
                    <legend>Selected Target Folder</legend>
                    <p>
                        <label for="targetNode">Target Folder</label>
                        <input type="text" id="targetNodeTitle" name="targetNodeTitle" value="">
                        <input type="hidden" id="targetNode" name="targetNode" value="">
                        <input type="hidden" id="guid" name="guid" value="<?php echo $this->guid; ?>">
                    </p>
                    <p>
                        <label for="Save">&nbsp;</label>
                        <input type="submit" value="Save" class="btn btn-blue big" />
                    </p>
		</fieldset>
            </form>

        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>
    <div class="content-box">
        <?php echo $this->action('rightdown','misc','dms'); ?>
    </div>
</aside>
<!-- End of Right column/section -->

