<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="Search <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <fieldset>
                <legend>Navigation</legend>
                <?php echo $this->widget2->render(); ?>
            </fieldset>
            <fieldset>
                <legend>Data Center</legend>
                <h4><?php echo $this->catalogTitle; ?></h4>
                <h6><?php echo $this->catalogSubTitle; ?></h6>
                <p>
                    <label for="price">Price:</label>
                    <?php echo $this->rowCatalog['price']; ?>
                </p>
                <hr>
                <?php echo $this->widget1->render(); ?>
            </fieldset>
            <?php //echo $this->widgetImageFiles->render(); ?>

            <div class="ta-center">
                <div id="galleryLoading"></div>
                <div id="content"></div>
            </div>

            <?php
            Zend_Session::sessionExists('cfg') ? Zend_Session::namespaceUnset('cfg') : '';
            $configGallery = new Zend_Session_Namespace("cfg");
            if (sizeof($configGallery->allThumbs) > $configGallery->perPage) {
            ?>

            <table width="800px;">
                <tr>
                    <td>
                        <ul id="pagination">
                            <?php for ($j = 1; $j <= ceil(sizeof($configGallery->allThumbs) / $configGallery->perPage); $j++) { ?>
                            <li id="<?php echo $j; ?>"><?php echo $j; ?></li>
                            <?php } ?>
                        </ul>
                    </td>
                </tr>
            </table>

            <?php } ?>

            <?php echo $this->widgetFiles->render(); ?>
            <?php echo $this->widgetHistory->render(); ?>
            <?php echo $this->widgetLegalBasis->render(); ?>
            <?php echo $this->widgetImplementingRegulation->render(); ?>
            <?php echo $this->widget3->render(); ?>
            <?php echo $this->widget4->render(); ?>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>
    <?php echo $this->action('rightdown','catalog','dms',array('guid'=>$this->catalogGuid,'node'=>$this->currentNode)); ?>
    <?php echo $this->action('view','manager','comment',array('guid'=>$this->catalogGuid,'node'=>$this->currentNode)); ?>
    
</aside>
<!-- End of Right column/section -->

<script type="text/javascript">
$(document).ready(function(){
    function displayLoad()
    {
        $("#galleryLoading").fadeIn(900,0);
        $("#galleryLoading").html("<img src='<?php echo $this->cdn('images'); ?>/bigLoader.gif' />");
    }
    function hideLoad()
    {
        $("#galleryLoading").fadeOut('slow');
    }

    //Default Starting Page Results
    $("#pagination li:first").css({'color' : '#FF0084'}).css({'border' : 'none'});

    displayLoad();
    $("#content").load("<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/gallery/guid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->currentNode; ?>",hideLoad());
    //Pagination Click
    $("#pagination li").click(function(){

            displayLoad();

            //CSS Styles
            $("#pagination li")
            .css({'border' : 'solid #dddddd 1px'})
            .css({'color' : '#0063DC'});

            $(this)
            .css({'color' : '#FF0084'})
            .css({'border' : 'none'});

            //Loading Data
            var pageNum = this.id;

            $("#content").load("<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/gallery/guid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->currentNode; ?>/page/" + pageNum,hideLoad());
    });
});
</script>