<?php 
/**
 * Pandamp
 * 
 * @author		2011-2018 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: editdoc.phtml 1 2014-02-20 15:48Z $
 */
?>
<?php
if ($this->getLanguage() == 'id')
	$tag = "www.hukumonline.com";
else
	$tag = "en.hukumonline.com";
?>
<h5>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h5>
<form method="post" action="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/fileuploader/edit" name="FileUploadFormEd" enctype="multipart/form-data">
<?php 
$i = 1;
foreach ($this->catalogGuid as $cid) :

$tblCatalog = new App_Model_Db_Table_Catalog();
$rowset = $tblCatalog->find($cid)->current();
$rowsetCatalogAttribute = $rowset->findDependentRowsetCatalogAttribute();
$oriName = $rowsetCatalogAttribute->findByAttributeGuid('docOriginalName')->value;

echo $oriName.'<br>';

?>

<input type='file' name='uploadedFile<?php echo $i; ?>' id='uploadedFile' size='50'/><br>
<input type='hidden' name='itemGuid<?php echo $i; ?>' id='itemGuid' value='<?php echo $cid; ?>'>

<?php 
$i++;
endforeach; 
?>

<input type='hidden' name='profileGuid' id='profileGuid' value='kutu_doc'>
<input type='hidden' name='relatedGuid' id='relatedGuid' value='<?php echo $this->relatedGuid; ?>'>
<input type='hidden' name='folderGuid' id='folderGuid' value='<?php echo $this->folderGuid; ?>'>
<input type="hidden" name="id" id="id" value="<?php echo $this->numberOfRows; ?>">

<br>
<p style="z-index:1;overflow:hidden;">
<input value="Save" type="submit" class="btn">
<input type="button" name="cancel" id="cancel" value="Cancel" class="btn" />
</p>
</form>
