<?php 
/**
 * Pandamp
 * 
 * @author		2011-2012 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: edit.phtml 1 2012-03-06 13:31Z $modified
 */
?>
<?php 
$this->headTitle('Edit new article');

$this->headLink()
	->appendStylesheet($this->cdn('scripts') . '/hol/datepicker/rfnet.css');

$this->headScript()
	->appendFile($this->cdn('scripts') . '/hol/pandamp/util.js');
?>

<script type="text/javascript" src="<?php echo ROOT_URL; ?>/library/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="<?php echo $this->cdn('scripts'); ?>/hol/datepicker/datetimepicker.js"></script>

<!-- Left column/section -->
<section class="column width6 first">
    <div class="colgroup leading">
        <div class="column width6 first">
            <?
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?=$tag;?>" target="_blank" title="DMS <?=$tag;?>"><?=$tag;?></a></h3>
            <h4>SOLR Dir: <?php echo $this->getSolrDir(); ?></h4>
            <a href="<?=$this->urlReferer;?>">Back to Origin Page</a>
            <fieldset>
                <legend>LOCATION:</legend>
                <?=$this->widget2->render();?>
            </fieldset>
            <form id="catalogInputForm" name="catalogInputForm" method="POST">
                <fieldset>
                    <legend>EDIT CATALOG</legend>
                    <?php if ($this->profile == 'article') : ?>
                    <div class="box box-info">
                    <abbr>Perhatian:</abbr> Untuk mengaktifkan fitur berita terkait
                    isikan kolom <abbr>keywords</abbr>.<br>Pisahkan setiap keywords dengan
                    koma, contoh: dpr, pemilu, partai politik
                    </div>
                    <?php endif; ?>
					<? foreach ($this->aRenderedAttributes['baseForm'] as $a) : ?>
					<? if (isset($a['description']) && isset($a['form'])) : ?>
					<p>
						<label><?=$a['description']; ?></label><br>
						<?=$a['form']; ?>
					</p>
					<? endif; ?>
					<? endforeach; ?>
					<? foreach ($this->aRenderedAttributes['attributeForm'] as $a) : ?>
					<? if (isset($a['description']) && isset($a['form'])) : ?>
					<p>
						<label><?=$a['description']; ?></label><br>
						<?=$a['form']; ?>
					</p>
					<? endif; ?>
					<? endforeach; ?>
					<p>
                    	<input type="submit" name="save" id="save" value="Save" class="btn btn-blue big" />
                    </p>
                </fieldset>
            </form>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?=$this->action('sidebar','user','customer');?>
    </div>
</aside>
<!-- End of Right column/section -->
<script type="text/javascript">
setTimeout(function()
{
	/**
	 * Validate form
	 */
	$.validator.addMethod('shortTitle', function(value) {
		value = value.replace(/^\s+|\s+$/g, '');
		var regex = new RegExp(/^[a-z0-9\-]+$/);
		if (value == '' || value.match(regex)) {
			return true;
		} else {
			return false;
		}
	});
	
    $("#catalogInputForm").validate({
        rules: {
            fixedTitle: "required"
        },
        messages: {
            fixedTitle: "Enter Title"
        }
    });

	/**
	 * Automatically create shortTitle once user enter the title
	 */
	$('#fixedTitle').bind('change', function() {
		$('#shortTitle').val(Pandamp.Util.generateShortTitle($(this).val()));
	});
});
</script>
