<div id='editupload' style="display:none;">
    <h3>Edit Upload form</h3>
    <?php
    if ($this->getLanguage() == 'id')
        $tag = "www.hukumonline.com";
    else
        $tag = "en.hukumonline.com";
    ?>
    <h5>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h5>
    
	<form id="FileUploadFormEd" enctype="multipart/form-data">
		
		<?php 
		$i = 1;
		foreach ($this->catalogGuid as $cid) : 
		
		$tblCatalog = new App_Model_Db_Table_Catalog();
		$rowset = $tblCatalog->find($cid)->current();
		$rowsetCatalogAttribute = $rowset->findDependentRowsetCatalogAttribute();
		$oriName = $rowsetCatalogAttribute->findByAttributeGuid('docOriginalName')->value;
		
		echo $oriName.'<br>';
		
		?>
		
		<input type='file' name='uploadedFile<?php echo $i; ?>' id='uploadedFile' size='50'/><br>
		<input type='hidden' name='itemGuid<?php echo $i; ?>' id='itemGuid' value='<?php echo $cid; ?>'>
		
		<?php 
		$i++;
		endforeach; 
		?>
		
		<input type='hidden' name='profileGuid' id='profileGuid' value='kutu_doc'>
		<input type='hidden' name='relatedGuid' id='relatedGuid' value='<?php echo $this->relatedGuid; ?>'>
		<input type="hidden" name="id" id="id" value="<?php echo $this->numberOfRows; ?>">
					
		<br>
		<p style="z-index:1;overflow:hidden;">
		<input value="Save" type="submit" class="btn">
		<input type="button" name="cancel" id="cancel" value="Cancel" class="btn nyroModalClose" />
		</p>
	</form>
<div id="uploaderSpinner" style="color:red; display:none;"><img src="<?php echo $this->cdn('images'); ?>/index.gif" border="0"> Sending Request</div>
<script type="text/javascript">
	var options = {
		type:'post',
		url: '<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/fileuploader/edit',
		beforeSubmit: prepareData,
		success: showResponse
	};
	$('#FileUploadFormEd').ajaxForm(options);
    function prepareData() 
    { 
	  	$('#uploaderSpinner').show();
	} 
	function showResponse(responseText, statusText) 
	{ 
	    alert('status: ' + statusText + '\n\nresponseText: \n' + responseText + 
	        '\n\nThe output div should have already been updated with the responseText.'); 
	        
	    $('#uploaderSpinner').hide();
	}
</script>
</div>