<div class="content-box">
    <header style="cursor: s-resize;">
        <h3>Manage Catalog</h3>
    </header>
    <section>
        <dl>
            <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/edit/guid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->currentNode; ?>"><abbr>Edit</abbr></a></dd>
            <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/uploader/new/relatedGuid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->currentNode; ?>"><abbr>Upload Document(s)</abbr></a></dd>
            <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/relation/search/relatedGuid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->currentNode; ?>"><abbr>Add Relation(s)</abbr></a></dd>
            <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/copy-folder/guid/<?php echo $this->catalogGuid; ?>"><abbr>Copy to Folder(s)</abbr></a></dd>
            <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/move-folder/guid/<?php echo $this->catalogGuid; ?>"><abbr>Move to Folder(s)</abbr></a></dd>
            <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/delete-confirm/guid/<?php echo $this->catalogGuid; ?>"><abbr>Delete</abbr></a></dd>
        </dl>
    </section>
</div>