<?php if (count($this->aData) > 0) : ?>
<div class="content-box">
    <header style="cursor: s-resize;">
        <h3><img src="<?php echo $this->cdn('images'); ?>/information.png" alt="" />Kategori Klinik</h3>
    </header>
    <section>
        <form id="frmFcClinic" name="frmFcClinic" method="post" action="<?php echo $this->baseUrl(); ?>/cari">
        <table class="no-style full">
            <tbody>
                <?php for($i=0; $i<count($this->aData);$i++) : ?>
                <tr>
                    <td><a href="<?php echo $this->aData[$i][0]; ?>" id="fcClinic"><abbr><?php echo $this->getCatalogAttribute($this->aData[$i][0],'fixedTitle'); ?></abbr></a></td>
                    <td class="ta-right"><?php echo $this->aData[$i][1]; ?></td>
                </tr>
                <?php endfor; ?>
            </tbody>
        </table>
        <input type="hidden" id="keyword" name="keyword" />
        <input type="hidden" id="ct" name="category" value="klinik" />
        </form>
    </section>
</div>
<script>
$(document).ready(function(){
    $('#fcClinic').live('click', function(){
        var iId = $(this).attr('href');
        var q = '<?php echo $this->query.' kategoriklinik:'; ?>' + iId;
        $("#keyword").val(q);
        $("#frmFcClinic").submit();

        return false;
    });


});
</script>
<?php endif; ?>