<?php if (count($this->aData) > 0) : ?>
<div class="content-box">
    <header style="cursor: s-resize;">
        <h3><img src="<?php echo $this->cdn('images'); ?>/information.png" alt="" />Penulis Artikel</h3>
    </header>
    <section>
        <form id="frmFcCreatedBy" name="frmFcCreatedBy" method="get" action="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse">
        <table class="no-style full">
            <tbody>
                <?php for($i=0; $i<count($this->aData);$i++) : ?>
                <tr>
                    <td><a href="<?php echo $this->aData[$i][3]; ?>" id="fcCreatedBy"><abbr><?php echo $this->aData[$i][0]; ?></abbr></a></td>
                    <td class="ta-right"><?php echo $this->aData[$i][1]; ?></td>
                </tr>
                <?php endfor; ?>
            </tbody>
        </table>
        <input type="hidden" id="keywordtypes" name="q" />
        <input type="hidden" id="sLimit" name="sLimit" value="25">
        <input type="hidden" id="sOffset" name="sOffset" value="0">
        </form>
    </section>
</div>
<script>
$(document).ready(function(){
    $('#fcCreatedBy').live('click', function(){
        var iIds = $(this).attr('href');
        var qIs = '<?php echo $this->query.' createdBy:'; ?>' + iIds;
        $("#keywordtypes").val(qIs);
        $("#frmFcCreatedBy").submit();

        return false;
    });


});
</script>
<?php endif; ?>