<? if (count($this->aData) > 0) : ?>
<div class="content-box">
    <header style="cursor: s-resize;">
        <h3><img src="<?=$this->cdn('images');?>/information.png" alt="" />Berdasarkan Tipe Peraturan</h3>
    </header>
    <section>
        <form id="frmFcHold" name="frmFcHold" method="get" action="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/search/dms/browse">
        <table class="no-style full">
            <tbody>
                <? for($i=0; $i<count($this->aData);$i++) : ?>
                <tr>
                    <td><a href="<?=$this->regulationType($this->aData[$i][0]);?>" id="fcHold"><abbr><?=$this->aData[$i][0];?></abbr></a></td>
                    <td class="ta-right"><?=$this->aData[$i][1];?></td>
                </tr>
                <? endfor; ?>
            </tbody>
        </table>
        <input type="hidden" id="keywordtype" name="q" />
        <input type="hidden" id="sLimit" name="sLimit" value="25">
        <input type="hidden" id="sOffset" name="sOffset" value="0">
        </form>
    </section>
</div>
<script>
$(document).ready(function(){
    $('#fcHold').live('click', function(){
        var iId = $(this).attr('href');
        var qI = '<?=$this->query.' regulationOrder:';?>' + iId;
        $("#keywordtype").val(qI);
        $("#frmFcHold").submit();

        return false;
    });


});
</script>


<? endif; ?>