<?php
//$sso = new Pandamp_Session_Remote();
//if ($sso->getInfo() || ($_SERVER['REQUEST_METHOD'] == 'POST' && $sso->authenticate())) {
//    $sReturn = "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
//    header("Location:".$sReturn, true, 303);
//    exit;
//}
//
//if ($_SERVER['REQUEST_METHOD'] == 'POST') $errmsg = "Login failed";

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>CMS Hukumonline</title>
        <link href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->baseUrl();?>/resources/css/administry.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery/form/jquery.validate.pack.js"></script>
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/ie.css"/>

        <script src="<?=$this->baseUrl();?>/js/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->baseUrl();?>/js/IE8.js"></script>

        <![endif]-->

        <script type="text/javascript">
            $(document).ready(function(){
                // validate signup form on keyup and submit
                var validator = $("#loginform").validate({
                        rules: {
                            username: "required",
                            password: "required"
                        },
                        messages: {
                            username: "Enter your username",
                            password: "Provide your password"
                        },
                        // the errorPlacement has to take the layout into account
                        errorPlacement: function(error, element) {
                            error.insertAfter(element.parent().find('label:first'));
                        },
                        // set new class to error-labels to indicate valid fields
                        success: function(label) {
                            // set &nbsp; as text for IE
                            label.html("&nbsp;").addClass("ok");
                        }
                });

            });
        </script>
    </head>
    <body>
        <!-- Header -->
        <header id="top">
            <div class="wrapper-login">
                <div id="title"><img src="<?=$this->cdn('images');?>/logo.png" alt="hukumonline" /><!--<span>CMS Hukumonline</span>--></div>
                <!-- Main navigation -->
                <nav id="menu">
                    <ul class="sf-menu sf-js-enabled sf-shadow">
                        <li class="current"><a href="<?=ROOT_URL;?>">Login</a></li>
                        <li><a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/account/register">Register</a></li>
                    </ul>
                </nav>
                <!-- End of Main navigation -->
            </div>
        </header>
        <!-- End of Header -->
	<!-- Page title -->
	<div id="pagetitle">
            <div class="wrapper-login"></div>
	</div>
	<!-- End of Page title -->

	<!-- Page content -->
	<div id="page">
            <!-- Wrapper -->
            <div class="wrapper-login">
                <!-- Login form -->
                <section class="full">

                    <h3>Login</h3>

                    <? if (isset($this->message)): ?>
                    <div class="box box-error">
                        <?= $this->message; ?>
                    </div>
                    <? endif; ?>

                    <?php
                    $my_access = new Pandamp_Core_Hol_Auth();
                    $my_access->login_reader();
                    ?>
                    <form id="loginform" method="post" action="<?php $_SERVER['PHP_SELF'];?>">

                        <p>
                            <label class="required" for="username">Username:</label><br>
                            <input id="username" class="full" name="username" value="<?=$my_access->user; ?>" type="text" />
                        </p>

                        <p>
                            <label class="required" for="password">Password:</label><br>
                            <input id="password" class="full" value="<?=$my_access->user_pw; ?>" name="password" type="password" />
                        </p>
                        <?
                        $lang = array(
                            'id'=>'Indonesia',
                            'en'=>'English'
                        );
                        ?>
                        <p>
                            <label for="langselector">Language:</label><br>
                                <select name="langselector">
                                    <?
                                    foreach ($lang as $key=>$val) {
                                        $sel = ($key == $this->getLanguage())? " selected" : "";
                                        echo '<option value='.$key . $sel.'>'.$val.'</option>';
                                    }
                                    ?>
                                </select>
                        </p>

                        <p>
                            <input id="remember" class="" value="yes"<?=($my_access->is_cookie == true) ? " checked" : ""; ?> name="remember" type="checkbox" />
                            <label class="choice" for="remember">Remember me?</label>
                        </p>

                        <p>
                            <input class="btn btn-green big" value="Login" type="submit" /> &nbsp; <a href="javascript:%20//;" onclick="$('#emailform').slideDown(); return false;">Forgot password?</a> or <a href="#">Need help?</a>
                        </p>
                        <input name="broker" type="hidden" value="<?=$this->broker; ?>" />
                        <div class="clear">&nbsp;</div>

                    </form>

                    <form id="emailform" style="display: none;" method="post" action="#">
                        <div class="box">
                            <p id="emailinput">
                                <label for="email">Email:</label><br>
                                <input id="email" class="full" name="email" type="text" />
                            </p>
                            <p>
                                <input class="btn" value="Send" type="submit" />
                            </p>
                        </div>
                    </form>

                </section>
                <!-- End of login form -->

            </div>
            <!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper-login">
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->
    </body>
</html>