<?php if (sizeof($this->allThumbs) !== 0) : ?>
<table cellspacing="2" cellpadding="0" class="full" id="gal">
    <tbody>
        <tr>
            <td colspan="4">
                <fieldset>
                    <legend>DOWNLOADABLE IMAGE(s)</legend>
                </fieldset>
            </td>
        </tr>
        <tr>
            <?php
            $n=1;
            $end = min(($this->page * $this->perPage), sizeof($this->allThumbs));
            for ($i = (($this->page - 1) * $this->perPage);  $i < $end; $i++) :
            ?>
            <td class="ta-center">
                <table border="0" cellspacing="1" cellpadding="0">
                    <tr>
                        <td>
                            <div style="cursor: pointer;" id="gvID<?php echo $i; ?>">
                                <a href="<?php echo $this->sdir; ?>/<?php echo $this->allThumbs[$i]; ?>">
                                    <img src="<?php echo $this->sdir; ?>/<?php echo $this->allThumbs[$i]; ?>" /><br>
                                </a>
                                <?php
                                $ext = explode(".",$this->allThumbs[$i]);
                                $ext = strtolower(array_pop($ext));
                                $th = str_replace(array('tn_','.'.$ext), "", $this->allThumbs[$i])
                                ?>
                                <div style="top:-16px;opacity:0.75;">
                                    <small><?php echo $this->getCatalogTitle($th,'fixedTitle'); ?></small>&nbsp;<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/edit/guid/<?php echo $th; ?>/node/<?php echo $this->folderGuid; ?>" target="_blank">[edit]</a><br>
                                    <small>delete:</small>&nbsp;<a href="javascript:;" onclick="remove('<?php echo $th; ?>', '<?php echo $this->catalogGuid; ?>', 'RELATED_IMAGE');return false;"><?php echo $th; ?></a>
                                </div><br/>
                            </div>
                        </td>
                    </tr>
                </table>
                
            </td>
            <?php
            if (($n % 4) == 0 && ($n != $this->perPage)) {
            ?>
                </tr>
                <tr align='center'>
            <?php
            }
            $n++;
            endfor;
            ?>
        </tr>
    </tbody>
</table>
<script type="text/javascript">
    function displayLoad()
    {
        $("#gal").fadeIn(900,0);
        $("#gal").html("<img src='<?php echo $this->cdn('images'); ?>/bigLoader.gif' />");
    }
    function hideLoad()
    {
        $("#gal").fadeOut('slow');
    }
    function remove(itemGuid, relatedGuid, relateAs)
    {
        if(confirm ('Are you sure ?')) {
        $.ajax({
            type:"post"
            ,url:"<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/relation/delete"
            ,data: "itemGuid="+ itemGuid + "&relatedGuid="+ relatedGuid +"&relateAs="+ relateAs
            ,beforeSend: function()
            {
                displayLoad();
            }
            ,success: function()
            {
                $("#content").load("<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/gallery/guid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->folderGuid; ?>",hideLoad());
            }
        });
        }

        return false;
    }
</script>
<?php endif; ?>