<?php if (count($this->aData) > 0) { ?>
<fieldset>
    <legend>DOWNLOADABLE FILE(s)</legend>
    <table class="display stylized" id="catalog">
    <thead>
        <tr>
            <th><input name="select_deselect" value="1" type="checkbox"></th>
            <th>Type</th>
            <th>Title</th>
            <th>Size</th>
        </tr>
    </thead>
	<tbody>
	<?php foreach ($this->aData as $data) { ?>
	<tr id="row_<?php echo $data->itemGuid; ?>">
		<td width="5%"><input type='checkbox' name='catalogGuid[]' id='catalogGuid' value='<?php echo $data->itemGuid; ?>' class="check_me"></td>
		<td width="5%"><?php echo $this->GetCatalogDocType($data->itemGuid); ?></td>
		<td><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/browser/download-file/guid/<?php echo $data->itemGuid; ?>/parent/<?php echo $data->relatedGuid; ?>"><abbr><?php echo $this->getCatalogTitle($data->itemGuid,'fixedTitle'); ?></abbr></a></td>
		<td><?php echo $this->GetCatalogDocSize($data->itemGuid); ?></td>
	</tr>
	<?php } ?>
    <tr>
        <td colspan="4">
            <select id="uof" name="uof">
                <option value="withselected">With selected:</option>
                <option value="delete">Delete</option>
                <option value="edit">Edit</option>
            </select>
        </td>
    </tr>
	</tbody>    
    </table>
</fieldset>
<div style="display:none;">
	<a href="#" class="nyroModal" id="d1">Edit Uploaded File(s)</a>
</div>
<script type="text/javascript">
    $(document).ready(function(){
                $('#uof').change(function(){
                     checkValues = new Array();
                     a=0;
                     $("input.check_me:checked").each(function(){
                         checkValues[a]=$(this).val();
                         a++;
                     });

                    if ($("#uof").val() == "edit")
                    {
                        if(checkValues.length==0)
                        {
                            alert('NO CATALOG SELECTED');
                            $("#uof").val("withselected");
                            return false;
                        }
                        else
                        {
                        	
							var sHref = '<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/editdocument/guid/'+checkValues+'/relatedGuid/<?php echo $this->catalogGuid; ?>#editupload';
							$('#d1').attr('href',sHref);
							if(this.value != '')
								$('#d1').click();
								
								
										                        	

                        }


                    }
					else if ($("#uof").val() == "delete")
					{
						window.location = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/delete-confirm/guid/"+checkValues;
					}
                    
					return false;
                });
    });
</script>
<?php } ?>