<?php if (count($this->rowsetFolder) > 0) { ?>
<div id="content_rfolder">
<fieldset>
    <legend>RELATED FOLDERS</legend>
    <ul id="dhline" style="list-style:none;">
        <?php foreach ($this->rowsetFolder as $row) { ?>
        <li>
            <?php if($row->guid==$this->folderGuid) { ?>
            <img src="<?php echo $this->cdn('images'); ?>/page_right.gif">
            <?php } ?>
            <a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $row->guid; ?>"><?php echo $row->title; ?></a>
            - [<?php echo $row->guid; ?>]&nbsp;<a href="javascript:;" onclick="remfol('<?php echo $this->catalogGuid; ?>', '<?php echo $row->guid; ?>');return false;">Remove</a>
        </li>
        <?php } ?>
    </ul>
</fieldset>
</div>
<script type="text/javascript">
    function displayLoad()
    {
        $("#dhline").fadeIn(900,0);
        $("#dhline").html("<img src='<?php echo $this->cdn('images'); ?>/wait.gif' />");
    }
    function hideLoad()
    {
        $("#dhline").fadeOut('slow');
    }
    function remfol(guid, folderGuid)
    {
        if(confirm ('Are you sure ?')) {
        $.ajax({
            type:"post"
            ,url:"<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/catalog/remove-from-folder"
            ,data: "guid=" + guid + "&folderGuid=" + folderGuid
            ,beforeSend: function()
            {
                displayLoad();
            }
            ,success: function(response)
            {
            	$("#content_rfolder").load("<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/render-folder/guid/<?php echo $this->catalogGuid; ?>/node/<?php echo $this->folderGuid; ?>",hideLoad());
            }
        });
        }

        return false;
    }
</script>
<?php } ?>