<?php if (count($this->rowsetRegulation) > 0) { ?>
<fieldset>
    <legend>PERATURAN PELAKSANA - NEW</legend>
    <ul id="ppline">
        <?php foreach ($this->rowsetRegulation as $data) { ?>
        <li>
            <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $data->itemGuid; ?>/node/<?php echo $this->folderGuid; ?>"><?php echo $this->getCatalogTitle($data->itemGuid,'fixedTitle'); ?></a>
            - <a href="javascript:;" class="deleterelation" data-itemguid="<?php echo $data->itemGuid; ?>" data-relatedguid="<?php echo $data->relatedGuid; ?>" data-relateas="<?php echo $data->relateAs; ?>">Delete</a><br>
            <?php echo $this->getCatalogTitle($data->itemGuid,'fixedSubTitle'); ?>
        </li>
        <?php } ?>
    </ul>
</fieldset>
<?php } ?>