<?php if (count($this->rowsetLegalBasic) > 0) { ?>
<fieldset>
    <legend>LEGAL BASIS</legend>
    <ul id="dhline">
        <?php foreach ($this->rowsetLegalBasic as $data) { ?>
        <li>
            <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/search/catalog/detail/guid/<?php echo $data->itemGuid; ?>/node/<?php echo $this->folderGuid; ?>"><?php echo $this->getCatalogTitle($data->itemGuid,'fixedTitle'); ?></a>
        </li>
        <?php } ?>
    </ul>
</fieldset>
<?php } ?>