<? if (count($this->aData) > 0) { ?>
<fieldset>
    <legend>RELATED ITEMS</legend>
    <ul id="ppline">
        <? foreach ($this->aData as $data) { ?>
        <li>
            <? if($data['node']==$this->catalogGuid) { ?>
            <img src="<?=$this->cdn('images'); ?>/page_right.gif">
            <? } ?>
            <a href="<?=$this->baseUrl();?>/<?=$this->getLanguage();?>/search/catalog/detail/guid/<?=$data['node'];?>/node/<?=$this->folderGuid; ?>"><?=$data['title']; ?></a><br>
            <?=$data['subTitle']; ?>
            <? if ($data['description']) { ?>
            <br><strong>Notes: </strong><?=$data['description']; ?>
            <? } ?>
        </li>
        <? } ?>
    </ul>
</fieldset>
<? } ?>