<? if (count($this->rowsetRegulation) > 0) { ?>
<fieldset>
    <legend>IMPLEMENTING REGULATIONS</legend>
    <ul id="ppline">
        <? foreach ($this->rowsetRegulation as $data) { ?>
        <li>
            <a href="<?=$this->baseUrl();?>/<?=$this->getLanguage();?>/search/catalog/detail/guid/<?=$data->relatedGuid;?>/node/<?=$this->folderGuid; ?>"><?=$this->getCatalogTitle($data->relatedGuid,'fixedTitle'); ?></a><br>
            <?=$this->getCatalogTitle($data->relatedGuid,'fixedSubTitle'); ?>
        </li>
        <? } ?>
    </ul>
</fieldset>
<? } ?>