<?php if (count($this->rowsetRegulation) > 0) { ?>
<fieldset>
    <legend>IMPLEMENTING REGULATIONS</legend>
    <ul id="ppline">
        <?php foreach ($this->rowsetRegulation as $data) { ?>
        <li>
            <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $data->relatedGuid; ?>/node/<?php echo $this->folderGuid; ?>"><?php echo $this->getCatalogTitle($data->relatedGuid,'fixedTitle'); ?></a><br>
            <?php echo $this->getCatalogTitle($data->relatedGuid,'fixedSubTitle'); ?>
        </li>
        <?php } ?>
    </ul>
</fieldset>
<?php } ?>