<ol class="breadcrumb">
<?php for($i=0; $i<count($this->aPath);$i++) { ?>
	<?php if($i != count($this->aPath)-1) { ?>
            <li><a href="<?php echo $this->aPath[$i]['url']; ?>"><?php echo str_replace('Root','Home',$this->aPath[$i]['title']); ?></a></li>
	<?php } else { ?>
            <li class="active"><?php echo str_replace('Root','Home',$this->aPath[$i]['title']); ?></li>
	<?php } ?>

<?php } ?>
</ol>
