<ul class="breadcrumbs">
<?php for($i=0; $i<count($this->aPath);$i++) { ?>
	<?php if($i != count($this->aPath)-1) {?>
            <li><a href="<?=$this->aPath[$i]['url']; ?>"><span class="<?=($i%2 ? 'label label-blue' : 'label label-red');?>"><?=$this->aPath[$i]['title'];?></span></a></li>
	<?php } else {?>
            <li><a href="<?=$this->aPath[$i]['url']; ?>"><?=$this->aPath[$i]['title'];?></a></li>
	<?php }?>

<?php } ?>
</ul>
