<link rel="stylesheet" type="text/css" href="<?=$this->cdn('scripts');?>/hol/jquery/jstree/tree_component.css" />
<script type="text/javascript" src="<?=$this->cdn('scripts');?>/hol/jquery/jstree/_lib/css.js"></script>
<script type="text/javascript" src="<?=$this->cdn('scripts');?>/hol/jquery/jstree/tree_component.js"></script>
<script>
/*
*****************************************
Author: Vivekanand
Website: http://www.developersnippets.com
*****************************************
*/
$(document).ready(function(){

	$(".toggleBtn").click(function(){
			if($("#slideMenu").hasClass('closed')){
				$("#slideMenu").animate({left:0}, 500, function(){
					$(this).removeClass('closed').addClass('opened');
					$("a#toggleLink").removeClass('toggleBtn').addClass('toggleBtnHighlight');
				});
			}//if close

			$('#slideMenu').bind("mouseleave",function(){
				$("#slideMenu").animate({left:-300}, 500, function(){
					$(this).removeClass('opened').addClass('closed');
					$("a#toggleLink").removeClass('toggleBtnHighlight').addClass('toggleBtn');
				});
			});//bind close
	});//toggleBtn click close

	$("a.anchorLink").click(function () {
		elementClick = $(this).attr("href");
		destination = $(elementClick).offset().top;
		$("html:not(:animated),body:not(:animated)").animate({ scrollTop: destination}, 1000 );
		return false;
	});

	//Mouse Enter Event (that is mouseover event)
	$(".toggleBtn").bind("mouseenter",function(){
			if($("#slideMenu").hasClass('closed')){
				$("#slideMenu").animate({left:0}, 500, function(){
					$(this).removeClass('closed').addClass('opened');
					$("a#toggleLink").removeClass('toggleBtn').addClass('toggleBtnHighlight');
				});
			}//if close

			$('#slideMenu').bind("mouseleave",function(){
				$("#slideMenu").animate({left:-300}, 500, function(){
					$(this).removeClass('opened').addClass('closed');
					$("a#toggleLink").removeClass('toggleBtnHighlight').addClass('toggleBtn');
				});
			});//bind close
	});//toggleBtn click close

	var treeFirstTime = 1;
	$("#dmsTreeSlideMenu").tree({
	      data  : {
	        type  : "json", // or "xml_nested" or "xml_nested"
	        url   : "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/folder/getchildreninjson",
	        async : true,
	        async_data : function (NODE) { return { id : $(NODE).attr("id") || 0, my_param : "my_value" } }
	      },
		callback    : {

					ondblclk    : function(NODE,TREE_OBJ) {
							if(true)
                                                                switch(TREE_OBJ.selected.text())
                                                                {
                                                                    case "Approved":
                                                                        window.location = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/clinic/browse/status/1/node/"+TREE_OBJ.selected.attr("id");
                                                                    break;
                                                                    case "Draft":
                                                                        window.location = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/clinic/browse/status/0/node/"+TREE_OBJ.selected.attr("id");
                                                                    break;
                                                                    case "NA":
                                                                        window.location = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/clinic/browse/status/2/node/"+TREE_OBJ.selected.attr("id");
                                                                    break;
                                                                    case "Published":
                                                                        window.location = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/clinic/browse/status/99/node/"+TREE_OBJ.selected.attr("id");
                                                                    break;
                                                                    case "Selected":
                                                                    	window.location = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/clinic/browse/status/9/node/"+TREE_OBJ.selected.attr("id");
                                                                    break;
                                                                    default:
                                                                        window.location = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/explorer/browse/node/"+TREE_OBJ.selected.attr("id");
                                                                }
							treeFirstTime = 0;
						}

				},
			cookies : { prefix : "dmsTreeSlideMenu", opts : { path : '/' }}
	    });

});
</script>
<div id="slideMenu" class="closed">
    <div class="slideMenuContent">
    <div id="dmsTreeSlideMenu" class="demo"></div>

    </div>
    <a style="top:100px; right: -42px;" href="#" class="toggleBtn" id="toggleLink"></a>
</div>