<?php $tblCatalog = new App_Model_Db_Table_Folder(); ?>
<form id="frmFolders" name="frmFolders" method="post">
<h3><input type='checkbox' name='folderGuid' id='folderGuid' value='<?php echo $this->node; ?>'>&nbsp;<?php echo $this->currentNodeTitle; ?></h3>
<hr>
<?php if($this->numberOfFolders == 0) { ?>
	No Sub-Folder(s)
<?php } ?>
    <table width="100%"  border="0" cellspacing="6" cellpadding="6" bgcolor="">
        <?php
        for($i = 0; $i < $this->rows; $i++)
                    {
        ?>
              <tr valign="top">
              <?php
              for($j = 0; $j < $this->columns; $j++) {
                    if(isset($this->data[$i + ($j * $this->rows)][2]))
                    {
              ?>
                        <td width="30" valign="top"><input type='checkbox' name='folderGuid' id='folderGuid' value='<?php echo $this->data[$i + ($j * $this->rows)][2]; ?>'></td>
                        <td width="250" valign="top">
                        	<?php
                        	$folderTitle = $this->data[$i + ($j * $this->rows)][0]; 
                        	?>
                        	<?php if ($folderTitle == 'Approved') { ?>
   							<a class="folderTitleLink" href="<?php echo ROOT_URL.'/'.$this->getLanguage().'/dms/clinic/browse/status/1/node/'.$this->data[$i + ($j * $this->rows)][2]; ?>"><?php echo $this->data[$i + ($j * $this->rows)][0]; ?></a>                     	
                        	<?php } else if ($folderTitle == 'Draft') { ?>
   							<a class="folderTitleLink" href="<?php echo ROOT_URL.'/'.$this->getLanguage().'/dms/clinic/browse/status/0/node/'.$this->data[$i + ($j * $this->rows)][2]; ?>"><?php echo $this->data[$i + ($j * $this->rows)][0]; ?></a>                     	
                        	<?php } else if ($folderTitle == 'NA') { ?>
   							<a class="folderTitleLink" href="<?php echo ROOT_URL.'/'.$this->getLanguage().'/dms/clinic/browse/status/2/node/'.$this->data[$i + ($j * $this->rows)][2]; ?>"><?php echo $this->data[$i + ($j * $this->rows)][0]; ?></a>                     	
                        	<?php } else if ($folderTitle == 'Selected') { ?>
   							<a class="folderTitleLink" href="<?php echo ROOT_URL.'/'.$this->getLanguage().'/dms/clinic/browse/status/9/node/'.$this->data[$i + ($j * $this->rows)][2]; ?>"><?php echo $this->data[$i + ($j * $this->rows)][0]; ?></a>                     	
                        	<?php } else if ($folderTitle == 'Published') { ?>
   							<a class="folderTitleLink" href="<?php echo ROOT_URL.'/'.$this->getLanguage().'/dms/clinic/browse/status/99/node/'.$this->data[$i + ($j * $this->rows)][2]; ?>"><?php echo $this->data[$i + ($j * $this->rows)][0]; ?></a>                     	
                        	<?php } else { ?>
                            <a class="folderTitleLink" href="<?php echo ROOT_URL.'/'.$this->getLanguage().'/dms/explorer/browse/node/'.$this->data[$i + ($j * $this->rows)][2]; ?>"><?php echo $this->data[$i + ($j * $this->rows)][0]; ?></a>
                            <?php } ?>
                        </td>
                        <td width="10">&nbsp;</td>
                        <td width="">&nbsp;</td>
                    <?php }} ?>
              </tr>
            <?php } ?>
    </table>
</form>
<div class="borderBottom">&nbsp;</div>
<div style="padding-top:1px"></div>