<?php 
/**
 * Pandamp
 * 
 * @author		2012-2013 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: dc.phtml 1 2012-10-03 14:17Z $
 */
?>
<!-- section category -->
<section class="column first">
<div class="width8">
	<?php if ($this->totalOfRows > 0) : ?>
	<h4>Jumlah peraturan tahun <?php echo $this->y; ?> : <?php echo $this->totalOfRows; ?></h4>
	<form id="peraturan" method="GET">
	<table width="100%">
	<tr>
		<td><label>Urutkan Berdasarkan:</label></td>
		<td>&nbsp;</td>
	</tr>
	</table>
	</form>
	<table class="display stylized full">
	<thead>
		<tr>
			<th>Title</th>
			<th nowrap>Created Date</th>
			<th nowrap>Modified Date</th>
			<th nowrap>Created By</th>
			<th nowrap>Modified By</th>
		</tr>
	</thead>
	<tbody>
		<?php for ($i=0;$i<$this->numberOfRows;$i++) : ?>
		<tr>
			<td class="title">
			<div>
				<a href="#"><b><?php echo $this->data[$i][1]; ?></b></a>
				<div class="listingDetails">
					<div class="pad">
						<b>Additional information</b>
						<ul>
							<li>LOCATION
								<ul>
									<?php
									$bpm = new Pandamp_Core_Hol_Catalog();
									$rowsetFolder = $bpm->getFolders($this->data[$i][0]);
									foreach ($rowsetFolder as $row) :
									?>
									<li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $row->guid; ?>" target="_blank"><?php echo $row->title; ?></a>&nbsp;&nbsp;&nbsp;<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $this->data[$i][0]; ?>/node/<?php echo $row->guid; ?>"><img src="<?php echo $this->cdn('images'); ?>/page_right.gif"></a></li>
									<?php endforeach; ?>
								</ul>
							</li>
						</ul>
					</div>
				</div>
				<small>id:<?php echo $this->data[$i][0]; ?></small>
			</div>
			</td>
			<td nowrap><?php echo $this->helperLoader('report')->translateSolrDate($this->data[$i][2]); ?></td>
			<td nowrap><?php echo $this->helperLoader('report')->translateSolrDate($this->data[$i][3]); ?></td>
			<td nowrap><?php echo $this->data[$i][4]; ?></td>
			<td nowrap><?php echo $this->data[$i][5]; ?></td>
		</tr>
		<?php endfor; ?>
	</tbody>
	</table>
	<?php if (isset($this->paginator['next']) || isset($this->paginator['previous'])) : ?>
	<div class="paginator">
		<?php if(isset($this->paginator['previous'])): ?>
		<a href="<?php echo $this->url(array($this->nodeText => $this->folderGuid, 'page' => $this->paginator['previous']), $this->pager); ?>">&laquo; Sebelumnya</a>
		<?php else: ?>
			<span class="ui_disable">&laquo; Sebelumnya</span>
		<?php endif ?>
		
		<?php if($this->paginator['firstPageInRange'] > $this->paginator['first']): ?>
			<a href="<?php echo $this->url(array($this->nodeText => $this->folderGuid, 'page' => $this->paginator['first']), $this->pager); ?>"><?php echo $this->paginator['first'] ?></a>
			<span>...</span>
		<?php endif ?>
		
		<?php foreach($this->paginator['pagesInRange'] as $page): ?>
			<?php if($page == $this->paginator['current']): ?>
				<span class="ui_active"><?php echo $page ?></span>
			<?php else: ?>
				<a href="<?php echo $this->url(array($this->nodeText => $this->folderGuid, 'page' => $page), $this->pager); ?>"><?php echo $page ?></a>
			<?php endif ?>
		<?php endforeach ?>
		
		<?php if($this->paginator['lastPageInRange'] < $this->paginator['last']): ?>
			<span>...</span>
			<a href="<?php echo $this->url(array($this->nodeText => $this->folderGuid, 'page' => $this->paginator['last']), $this->pager); ?>"><?php echo $this->paginator['last'] ?></a>
		<?php endif ?>
		
		<?php if(isset($this->paginator['next'])): ?>
			<a href="<?php echo $this->url(array($this->nodeText => $this->folderGuid, 'page' => $this->paginator['next']), $this->pager); ?>">Berikutnya &raquo;</a>
		<?php else: ?>
			<span class="ui_disable">Berikutnya &raquo;</span>
		<?php endif ?>
	</div>
	<?php endif ?>
	
	<div class='clear'>&nbsp;</div>
	<?php endif ?>
</div>
</section>