<?php 
/**
 * Pandamp
 * 
 * @author		2012-2013 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: dc.phtml 1 2012-10-03 14:17Z $
 */
?>
<!-- section category -->
<section class="column first">
<div class="width8">
	<h4>Jumlah <?php echo $this->p; ?> tahun <?php echo $this->y; ?> : <?php echo $this->totalOfRows; ?></h4>
	<form name="peraturan" id="peraturan" method="GET">
	<table width="100%">
	<tr>
		<td><label>Urutkan Berdasarkan:</label></td>
		<td><?php echo $this->helperLoader('report')->selectSorting(array('id' => 'sort', 'name' => 'sort', 'class' => 'no-class', 'selected' => $this->sort, 'profile' => $this->p)); ?></td>
		<?php if ($this->p == 'peraturan') { ?>
		
		<td>&nbsp;</td>
		<td><?php echo $this->helperLoader('report')->selectBy(array('id' => 'by', 'name' => 'by', 'class' => 'no-class', 'selected' => $this->by, 'profile' => 'kutu_peraturan')); ?></td>
		<td>&nbsp;</td>
		<td><?php echo $this->helperLoader('report')->selectRegulation(array('id' => 'regulation', 'name' => 'regulation', 'class' => 'no-class', 'selected' => $this->regulation, 'profile' => 'kutu_peraturan', 'prtJenis' => 'prtJenis')); ?></td>
		
		<?php } else if ($this->p == 'article') { ?>
		<td>&nbsp;</td>
		<td><?php echo $this->helperLoader('report')->selectBy(array('id' => 'by', 'name' => 'by', 'class' => 'no-class', 'selected' => $this->by, 'profile' => 'article')); ?></td>
		<td><?php echo $this->helperLoader('report')->selectAuthor(array('id' => 'author', 'name' => 'author', 'class' => 'no-class', 'selected' => $this->author, 'profile' => 'article')); ?></td>
		
		<?php } else { ?>
		<td>&nbsp;</td>
		<td><?php echo $this->helperLoader('report')->selectBy(array('id' => 'by', 'name' => 'by', 'class' => 'no-class', 'selected' => $this->by, 'profile' => 'kutu_putusan')); ?></td>
		<td>&nbsp;</td>
		<td><?php echo $this->helperLoader('report')->selectRegulation(array('id' => 'regulation', 'name' => 'regulation', 'class' => 'no-class', 'selected' => $this->regulation, 'profile' => 'kutu_putusan', 'prtJenis' => 'ptsJenisLembaga')); ?></td>
		<?php } ?>
		
		<td><label>Show</label></td>
		<td><?php echo $this->helperLoader('report')->selectPerpage(array('id' => 'perpage', 'name' => 'perpage', 'class' => 'no-class', 'selected' => $this->perpage, 'totalnum' => $this->totalOfRows)); ?></td>
	</tr>
	</table>
	</form>
	<?php if ($this->totalOfRows > 0) : ?>
	<table class="display stylized full" width="100%">
	<thead>
		<tr>
			<th>Title</th>
			<?php if ($this->p == 'peraturan') { ?>
			<th>Tgl. Ditetapkan</th>
			<th>Jenis Peraturan</th>
			<th>Number</th>
			<th>Year</th>
			<?php } else if ($this->p == 'article') { ?>
			<th>Published Date</th>
			<th>Author</th>
			<?php } ?>
			<th>Created Date</th>
			<th>Modified Date</th>
			<th>Created By</th>
			<th>Modified By</th>
			<th><input name='sdc' id='sdc' type='checkbox'></th>
		</tr>
	</thead>
	<tbody>
		<?php for ($i=0;$i<$this->numberOfRows;$i++) : ?>
		<tr id="row_<?php echo $this->data[$i][0]; ?>">
			<td class="title">
			<div>
				<a href="#"><b><?php echo $this->data[$i][1]; ?></b></a>
				<div class="listingDetails">
					<div class="pad">
						<b>Additional information</b>
						<ul>
							<?php if (!empty($this->data[$i][6])) : ?>
							<li>HITS DESKTOP
								<ul>
									<li><?php echo $this->data[$i][6]; ?></li>
								</ul>
							</li>
							<?php endif; ?>
							<?php if (!empty($this->data[$i][7])) : ?>
							<li>HITS MOBILE
								<ul>
									<li><?php echo $this->data[$i][7]; ?></li>
								</ul>
							</li>
							<?php endif; ?>
							<li>LOCATION
								<ul>
									<?php
									$bpm = new Pandamp_Core_Hol_Catalog();
									$rowsetFolder = $bpm->getFolders($this->data[$i][0]);
									foreach ($rowsetFolder as $row) :
									?>
									<li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $row->guid; ?>" target="_blank"><?php echo $row->title; ?></a>&nbsp;&nbsp;&nbsp;<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $this->data[$i][0]; ?>/node/<?php echo $row->guid; ?>"><img src="<?php echo $this->cdn('images'); ?>/page_right.gif"></a></li>
									<?php endforeach; ?>
								</ul>
							</li>
						</ul>
					</div>
				</div>
				<small>id:<?php echo $this->data[$i][0]; ?></small>
			</div>
			</td>
			<?php if ($this->p == 'peraturan') { ?>
			<td><?php echo $this->helperLoader('report')->translateSolrDate($this->data[$i][10]); ?></td>
			<td><abbr><?php echo $this->data[$i][11]; ?></abbr></td>
			<td><?php echo $this->data[$i][8]; ?></td>
			<td><?php echo $this->data[$i][9]; ?></td>
			<?php } else if ($this->p == 'article') { ?>
			<td><?php echo $this->helperLoader('report')->translateSolrDate($this->data[$i][8]); ?></td>
			<td><?php echo $this->data[$i][9]; ?></td>
			<?php } ?>
			<td><?php echo $this->helperLoader('report')->translateSolrDate($this->data[$i][2]); ?></td>
			<td><?php echo $this->helperLoader('report')->translateSolrDate($this->data[$i][3]); ?></td>
			<td><?php echo $this->data[$i][4]; ?></td>
			<td><?php echo $this->data[$i][5]; ?></td>
			<td><input type='checkbox' name='guid[]' id='guid' value='<?php echo $this->data[$i][0]; ?>' class='check_me'></td>
		</tr>
		<?php endfor; ?>
	</tbody>
	</table>
	<?php if (isset($this->paginator['next']) || isset($this->paginator['previous'])) : ?>
	<div class="paginator">
		<?php if(isset($this->paginator['previous'])): ?>
		<a href="<?php echo $this->this_url; ?>page=<?php echo $this->paginator['previous'] ?>">&laquo; Sebelumnya</a>
		<?php else: ?>
			<span class="ui_disable">&laquo; Sebelumnya</span>
		<?php endif ?>
		
		<?php if($this->paginator['firstPageInRange'] > $this->paginator['first']): ?>
			<a href="<?php echo $this->this_url; ?>page=<?php echo $this->paginator['first'] ?>"><?php echo $this->paginator['first'] ?></a>
			<span>...</span>
		<?php endif ?>
		
		<?php foreach($this->paginator['pagesInRange'] as $page): ?>
			<?php if($page == $this->paginator['current']): ?>
				<span class="ui_active"><?php echo $page ?></span>
			<?php else: ?>
				<a href="<?php echo $this->this_url; ?>page=<?php echo $page ?>"><?php echo $page ?></a>
			<?php endif ?>
		<?php endforeach ?>
		
		<?php if($this->paginator['lastPageInRange'] < $this->paginator['last']): ?>
			<span>...</span>
			<a href="<?php echo $this->this_url; ?>page=<?php echo $this->paginator['last'] ?>"><?php echo $this->paginator['last'] ?></a>
		<?php endif ?>
		
		<?php if(isset($this->paginator['next'])): ?>
			<a href="<?php echo $this->this_url; ?>page=<?php echo $this->paginator['next'] ?>">Berikutnya &raquo;</a>
		<?php else: ?>
			<span class="ui_disable">Berikutnya &raquo;</span>
		<?php endif ?>
	</div>
	<?php endif ?>
	
	<div class='clear'>&nbsp;</div>
	<form id="action">
		<table>
		<tr>
			<td><label>With Selected</label>&nbsp;</td>
			<td>
			<select name="choose" id="choose">
				<option value="">---</option>
				<option value="delete">Delete</option>
				<option value="export">Export</option>
			</select>
			</td>
		</tr>
		</table>
	</form>
	<?php endif ?>
	<div class='clear'>&nbsp;</div>
</div>
</section>