<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <a href="javascript:history.back();">Back to Folder</a>
            <fieldset>
                <legend>Location:</legend>
                <?php echo $this->widget2->render(); ?>
            </fieldset>
            <form id="frmEditFolder" method="post">
                <fieldset>
                    <legend>Folder Info</legend>
                    <p>
                        <label class="required" for="title">Folder Title</label><br>
                        <input id="title" name="title" class="required half" value="<?php echo $this->row->title; ?>" />
                    </p>
                    <p>
                        <label for="description">Description</label><br>
                        <textarea id="description" name="description" class="medium" cols=35 rows="1"><?php echo $this->row->description; ?></textarea>
                    </p>
                    <p>
                        <label for="viewOrder">Menu View Order</label><br>
                        <input id="viewOrder" name="viewOrder" class="half" value="<?php echo $this->row->viewOrder; ?>" />
                    </p>
                    <p>
                        <label for="cmsParams">Cms Parameters</label><br>
                        <?php
                        $prm = Zend_Json::decode($this->row->cmsParams);
                        ?>
                        <input id="cmsParams" name="cmsParams" class="half" value="<?php echo $prm['st']; ?>" />
                    </p>
                    <p>
                        <label for="typeoffolder">Type of Folder</label><br>
                        <select name="tof" id="tof">
                            <option value="">Choose:</option>
                            <option value="cms">Berita</option>
                            <option value="cms-en">CMS En</option>
                            <option value="dms">Peraturan</option>
                            <option value="eventcalendar">Project</option>
                            <option value="klinik">Klinik</option>
                            <option value="marketing">Marketing</option>
                            <option value="membership">Membership</option>
                            <option value="menu">Menu</option>
                        </select>
                    </p>
                    <p>
                        <input type="hidden" id="node" name="node" value="<?php echo $this->currentNode; ?>">
                        <input type="submit" value="Save" class="btn btn-blue big" />
                    </p>

                </fieldset>
            </form>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>
</aside>
<!-- End of Right column/section -->

<script type="text/javascript">
$(document).ready(function(){
    $("#tof").val('<?php echo $this->row->type; ?>');
    var message = "<?php echo $this->message; ?>";
    if(message!="")
    {
        alert (message);
    }

    $("#frmEditFolder").validate();

});
</script>
