<?php echo $this->headTitle('Add New Polling'); ?>
<?php 
$this->headScript()
	->appendFile($this->cdn('scripts') . '/hol/jquery/form/jquery.validate.min.js');
?>
<section class="content-header">
	<h1>Add New Polling <small>Enter new information about the polling in the form below:</small></h1>
    <ol class="breadcrumb">
		<li><a href="<?php echo ROOT_URL; ?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/polling/manager/list"><i class="fa fa-bars"></i> Polling</a></li>
        <li class="active">Add New</li>
    </ol>
</section>
<section class="content">
	<div class="row">
		<div class="col-md-12">
			<?php echo $this->flashMessenger(); ?>
			<form class="form-horizontal" method="post" action="" id="addPollForm">
				<div class="form-group">
					<label class="col-sm-1 control-label">Title</label>
					<div class="col-sm-8">
						<input class="form-control" placeholder="Title" id="title" name="title" type="text" />
					</div>
				</div>
				
				<div class="form-group" id="fields">
		            <label class="col-sm-1 control-label" for="field1">Answer</label>
        		    <div class="col-sm-10 controls"> 
        		    	<div>
		                    <div class="entry input-group col-xs-5">
		                        <input class="form-control" name="answers[]" type="text" placeholder="Choice answers" />
		                    	<span class="input-group-btn">
		                            <button class="btn btn-success btn-add" type="button">
		                                <span class="glyphicon glyphicon-plus"></span>
		                            </button>
		                        </span>
		                    </div>
	                    </div>
            			<br>
			            <small>Press <span class="glyphicon glyphicon-plus gs"></span> to add another form field :)</small>
            		</div>
        		</div>
        		
        		<div class="form-group">
        			<div class="col-sm-1 control-label">&nbsp;</div>
        			<div class="col-sm-8">
						<button class="btn btn-sm btn-primary" type="submit">Process</button>&nbsp;
						<button type="button" class="btn btn-sm btn-success" onClick="window.location.href='<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/polling/manager/list'">Back</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</section>
<?php $this->headScript()->captureStart(); ?>
$(function() {
    $(document).on('click', '.btn-add', function(e)
	{
    	e.preventDefault();
    	var controlForm = $('.controls div:first'),
    		currentEntry = $(this).parents('.entry:first'),
    		newEntry = $(currentEntry.css('padding', '0 0 10px 0').clone()).appendTo(controlForm);
    	newEntry.find('input').val('');
    	controlForm.find('.entry:not(:last) .btn-add')
    		.removeClass('btn-add').addClass('btn-remove')
    		.removeClass('btn-success').addClass('btn-danger')
    		.html('<span class="glyphicon glyphicon-minus"></span>');
	}).on('click', '.btn-remove', function(e)
	{
		$(this).parents('.entry:first').remove();
		e.preventDefault();
		return false;
	});

	$('#addPollForm').validate({
		errorClass: 'help-block',
		ignore: [],
		rules: {
			title: {
				required: true,
		  		maxlength: 255
			},
			'answers[]': {
				required: true,
			}
		},
		messages: {
			title: {
	        	required: "You have not entered title",
				maxlength: "Maximum allowed length is 80 characters"
			},
			'answers[]': {
				required: "You have not entered answer",
			}
		},
		highlight: function (e) {
			$(e).closest('.profile-info-value').removeClass('has-info').addClass('has-error');
		},
		success: function (e) {
			$(e).closest('.profile-info-value').removeClass('has-error').addClass('has-success');			
			$(e).remove();
		
		}
	});
})
<?php $this->headScript()->captureEnd(); ?>