<div class="align-left">
    <div style="font:bold 16px Georgia,Times New Roman,Times,serif;">Polling</div>
</div>
<div class="align-right">
    &raquo;&nbsp;<a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/polling/election/browse/id/<?php echo $this->rowPoll->guid; ?>">index</a>
</div>
<div class="clear">&nbsp;</div>
<hr>
<table class="no-style full" id="poll-container">
    <tbody>
        <tr>
            <td><?php echo $this->rowPoll->title; ?></td>
        </tr>
        <?php foreach ($this->rowOpt as $row) { ?>
        <tr>
            <td>
                &raquo;&nbsp;<?php echo $row->text; ?>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <td>
                <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/polling/election/whos/id/<?php echo $this->rowPoll->guid; ?>" style="font-size:12px;" class="bb">Hasil Polling</a>
            </td>
        </tr>
    </tbody>
</table>
<div class="clear">&nbsp;</div>