<?php 
/**
 * Pandamp
 * 
 * @author		2011-2012 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: answer-clinic.phtml 1 2012-03-06 16:55Z $modified
 */
?>
<?php 
$this->headTitle('Answer Clinic');

$this->headLink()
	->appendStylesheet($this->cdn('scripts') . '/hol/datepicker/rfnet.css');

$this->headScript()
	->appendFile($this->cdn('scripts') . '/hol/pandamp/util.js');
?>

<script type="text/javascript" src="<?php echo ROOT_URL; ?>/library/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="<?php echo $this->cdn('scripts'); ?>/hol/datepicker/datetimepicker.js"></script>

<!-- Left column/section -->
<section class="column width6 first">
	<h3><?php echo $this->flashMessenger(); ?></h3>
    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <a href="<?php echo $this->urlReferer; ?>">Back to Origin Page</a>
            <fieldset>
                <legend>LOCATION:</legend>
                <?php echo $this->widget2->render(); ?>
            </fieldset>
            <form id="answerClinicForm" name="answerClinicForm" method="POST">
                <fieldset>
                    <legend>CLINIC</legend>
					<?php foreach ($this->aRenderedAttributes['baseForm'] as $a) : ?>
					<p>
						<label><?php echo $a['description']; ?></label><br>
						<?php echo $a['form']; ?>
					</p>
					<?php endforeach; ?>
					<?php foreach ($this->aRenderedAttributes['attributeForm'] as $a) : ?>
					<?php if (isset($a['description']) && isset($a['form'])) : ?>
					<p>
						<label><?php echo $a['description']; ?></label><br>
						<?php echo $a['form']; ?>
					</p>
					<?php endif; ?>
					<?php endforeach; ?>
					<p>
                    	<input type="submit" name="save" id="save" value="Save" class="btn btn-blue big" />
					</p>
                </fieldset>
            </form>
        </div>
    </div>

    <div class="clear">&nbsp;</div>
</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>
</aside>
<!-- End of Right column/section -->
<script type="text/javascript">
setTimeout(function()
{
	/**
	 * Validate form
	 */
	$.validator.addMethod('shortTitle', function(value) {
		value = value.replace(/^\s+|\s+$/g, '');
		var regex = new RegExp(/^[a-z0-9\-]+$/);
		if (value == '' || value.match(regex)) {
			return true;
		} else {
			return false;
		}
	});
	
    $("#answerClinicForm").validate({
        rules: {
            fixedAnswer: "required"
        },
        messages: {
            fixedAnswer: "Enter Title"
        }
    });

	/**
	 * Automatically create shortTitle once user enter the title
	 */
	$('#fixedCommentTitle').bind('change', function() {
		$('#shortTitle').val(Pandamp.Util.generateShortTitle($(this).val()));
	});
});
</script>
