<?php 
$this->headLink()
	->appendStylesheet($this->cdn('scripts') . '/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css');

$this->headScript()
	->appendFile($this->cdn('scripts') . '/plugins/jQuery/jquery.tagsinput.min.js')
	->appendFile($this->cdn('scripts') . '/plugins/bootstrap-datetimepicker/scripts/moment.js')
	->appendFile($this->cdn('scripts') . '/plugins/bootstrap-datetimepicker/scripts/bootstrap-datetimepicker.js')
	->appendFile($this->cdn('scripts') . '/plugins/phpjs/php.full.min.js')
	->appendFile($this->cdn('scripts') . '/hol/pandamp/util.js');

$this->headStyle()->captureStart();
?>
.mloading{margin:0 auto; background:url(<?php echo $this->cdn('styles'); ?>/images/loading.gif) center no-repeat; height:20px; line-height:20px}
.ui-autocomplete-loading { background:url('<?php echo $this->cdn('styles'); ?>/images/loading.gif') no-repeat right center }
.bootstrap-tagsinput { width: 100%;min-height: 100px; }
.ui-dialog{font-size: 83.5%;}
.ui-widget-overlay
{
  opacity: .50 !important; /* Make sure to change both of these, as IE only sees the second one */
  filter: Alpha(Opacity=50) !important;

  background:"rgb(0, 0, 0)";
}
.photos { overflow: auto; }
.photos li { float: left; margin-right: 5px; position: relative; margin-bottom: 5px; list-style-type: none; }
.photos li img { width: 48px; height: 45px; border: 1px solid #999; cursor: pointer; }
.photos li a { position: absolute; left: 0; top: 35px; }
.t_a_ui_paginator { margin: 0 auto; text-align: center; font-size:10px }
.t_a_ui_paginator span { margin: 0px 10px 0px 0px; }
.t_a_ui_paginator a { text-decoration: underline; text-align: center; margin: 0px 5px 0px 0px; line-height: 20px; }
.t_a_ui_paginator span.t_a_ui_active { background-color: #555; padding: 6px 8px; line-height: 9px; height: 9px; width: 7px; }
.ephotos { overflow: auto; border: 1px solid #444; padding: 5px; }
.ephotos li { float: left; margin-right: 10px; margin-bottom: 15px; }
div.tagsinput { border:1px solid #CCC; background: #FFF; padding:5px; width:300px; height:100px; overflow-y: auto;}
div.tagsinput span.tag { border: 1px solid #a5d24a; -moz-border-radius:2px; -webkit-border-radius:2px; display: block; float: left; padding: 5px; text-decoration:none; background: #cde69c; color: #638421; margin-right: 5px; margin-bottom:5px;font-family: helvetica; font-size:13px;}
div.tagsinput span.tag a { font-weight: bold; color: #82ad2b; text-decoration:none; font-size: 11px; }
div.tagsinput input { width:80px; margin:0px; font-family: helvetica; font-size: 13px; border:1px solid transparent; padding:5px; background: transparent; color: #000; outline:0px; margin-right:5px; margin-bottom:5px; }
div.tagsinput div { display:block; float: left; }

<?php $this->headStyle()->captureEnd(); ?>
<?php $this->headTitle('Jawab klinik'); ?>
<!-- Content Header (Page header) -->
<section class="content-header">
	<?php
	if ($this->getLanguage() == 'id')
		$tag = "www.hukumonline.com";
	else
		$tag = "en.hukumonline.com";
	?>
	<h1>
		Site
		<small><?php echo $tag; ?></small>
	</h1>
	<?php echo $this->widget2->render(); ?>
</section>
<!-- Main content -->
<section class="content">
	<?php echo $this->flashMessenger(); ?>
	<!-- form start -->
	<form id="editPost" method="post">
		<div class="box box-info">
			<div class="box-header with-border">
				<h3 class="box-title">Edit Klinik</h3>
			</div><!-- /.box-header -->
			<div class="box-body">
				<div class="row">
					<div class="form-group col-xs-8">
						<label for="shortTitle">Slug</label>
						<input type="text" class="form-control" name="shortTitle" id="shortTitle" value="<?php echo $this->catalog['shortTitle']; ?>" />
					</div>
				</div>
				<div class="row">
					<div class="form-group col-xs-3">
						<label>Published Date</label>
						<div class="input-group" id="datetimepicker1" data-date-format="YYYY-MM-DD HH:mm:ss">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" class="form-control" name="publishedDate" id="publishedDate" value="<?php echo $this->catalog['publishedDate']; ?>" />
						</div>
					</div>
					<div class="form-group col-xs-3">
						<label>Expired Date</label>
						<div class="input-group" id="datetimepicker2" data-date-format="YYYY-MM-DD HH:mm:ss">
							<input type="text" class="form-control" name="expiredDate" id="expiredDate" value="<?php if ($this->catalog['expiredDate']!=='0000-00-00 00:00:00') : echo $this->catalog['expiredDate']; endif; ?>">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
						</div>
					</div>
					
				</div>
				<div class="row">
					<div class="form-group col-xs-3">
						<label>Status</label>
						<?php
						require_once(CONFIG_PATH.'/master-status.php');
						$aStatus = MasterStatus::getPublishingStatus();
						?>
						<select name="status" class="form-control">
						<?php foreach($aStatus as $val => $label) : ?>
						<option value="<?php echo $val; ?>"<?php if($this->catalog['status'] == $val) echo ' selected'; ?>><?php echo $label;?></option>
						<?php endforeach; ?>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label>Price</label>
					<div class="input-group col-xs-3">
						<span class="input-group-addon">Rp</span>
						<input type="text" class="form-control" name="price" value="<?php echo $this->catalog['price']; ?>" />
					</div>
				</div>

				<?php foreach ($this->aRenderedAttributes['attributeForm'] as $a) : ?>
					<?php if (isset($a['form'])) : ?>
						<?php echo $a['form']; ?>
					<?php endif; ?>
				<?php endforeach; ?>
				
			</div>
			<input type="hidden" name="guid" value="<?php echo $this->catalogGuid; ?>">
			<input type="hidden" name="profileGuid" value="<?php echo $this->profile; ?>">
			<input type="hidden" name="folderGuid" value="<?php echo $this->currentNode; ?>">
			<input type="hidden" name="fixedAnswer" id="showfckdatanswer">
			<input type="hidden" name="fixedCommentQuestion" id="showfckdatquestion">
			<div class="box-footer">
            	<button type="submit" class="btn btn-primary">Submit</button>
            	<p class="help-block" id="wait"></p>
        	</div>			
		</div>
		<div class="row">
			<!-- left column -->
			<div class="col-md-6">
				<div class="box box-success">
					<div class="box-header with-border">
						<h3 class="box-title">Unggahan</h3>
	                  	<div class="box-tools pull-right">
	                		<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
	                		<button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
	          			</div>		
					</div>
					<div class="box-body">
						<div class="nav-tabs-custom">
							<ul class="nav nav-tabs">
								<li class="active"><a href="#images" data-toggle="tab">Images</a></li>
								<li><a href="#files" data-toggle="tab">Files</a></li>
							</ul>
							<div class="tab-content">
								<div class="active tab-pane" id="images">
									<?php
									$relatedItemDb = new App_Model_Db_Table_RelatedItem();
									$relItems = $relatedItemDb->fetchAll("relatedGuid='".$this->catalogGuid."' AND relateAs='RELATED_IMAGE'");
									?>
									<?php if ($this->currentNode !== 'lt4de5c32a53bd4') : // guid beritafoto => solusi sementara karena jika tidak begini maka tidak bisa di sembunyikan ?>
									<div style="margin-bottom: 2px">Search for existing images.</div>
									<div class="box-body">
										<div class="form-group">
											<label>Title</label>
											<div class="input-group">
												<input type="text" class="form-control" name="keyword" id="keyword" />
												<div class="input-group-addon">
													<a href="javascript: void(0);" id="searchButton">
														<i class="fa fa-search"></i>
													</a>
												</div>
											</div>
										</div>
									</div>
									<div class="photos" style="margin-top:-15px;margin-bottom: 10px;margin-left:-15px">
										<ul id="uploadedPhotos"></ul>
										<ul id="searchPhotos"></ul>
									</div>
									<div class="clearfix"></div>
									<div class="clearfix t_a_ui_paginator" id="searchPager" style="margin-bottom: 10px"></div>
									
									<div id="articleImageContainer">
									<?php
									if ($relItems) :
									foreach ($relItems as $relItem) :
									$fs = 'thumbnail_';
									$filename = $this->getCatalogAttribute($relItem['itemGuid'],'docSystemName');
									$ext = pathinfo($filename, PATHINFO_EXTENSION);
									$fn = pathinfo($filename, PATHINFO_FILENAME);
									if (substr($fn,0,2) !== 'lt') {
										$fn = $relItem['itemGuid'];
										$fs = 'tn_';
										$filename = $fn.'.'.$ext;
									}
									$title = $this->getCatalogAttribute($fn,'fixedTitle');
									$rg = $this->getItemRelated($fn,'RELATED_IMAGE');
									/*
									$catalogDb = new App_Model_Db_Table_Catalog();
									$catalog = $catalogDb->fetchRow("guid='".$fn."' AND status!=-1");
									if ($catalog) :
									$pd1 = $catalog['createdBy'];
									$pd2 = date('Y',strtotime($catalog['createdDate']));
									$pd3 = date('m',strtotime($catalog['createdDate']));
									$pd4 = date('d',strtotime($catalog['createdDate']));
									*/
									?>
									
									<div style="padding: 5px 0px 0px;" id="row_<?php echo $fn; ?>">
										<img src="<?php echo $this->cdn('rim'); ?>/frontend/<?php echo $rg['relatedGuid']; ?>/<?php echo $fs.$filename; ?>" height="70" width="80">
										<a href="javascript:;" id="<?php echo $fn; ?>" class="irAction" style="text-decoration: none">[-]</a>
										<input value="<?php echo $title; ?>" style="width: 340px;" id="<?php echo $fn; ?>" name="fileImage" type="text" onchange="javascript:updateImageSet(this);">
										<input value="<?php echo $this->cdn('rim'); ?>/frontend/<?php echo $rg['relatedGuid']; ?>/<?php echo $fs.$filename; ?>" name="fixedFileImage" type="hidden">
									</div>						
									<?php //endif; ?>
									<?php endforeach; ?>
									<?php endif; ?>
									</div>
									
									<?php else : ?>
									
									<!--
									Untuk beritafoto 
									 -->
									<div class="photos" style="margin-top: 10px">
										<ul id="filesSet">
											<?php if (count($relItems) != 1) : ?>
											<?php foreach ($relItems as $item) : ?>
											<?php
											$fs2 = 'thumbnail_';
											$filename2 = $this->getCatalogAttribute($item['itemGuid'],'docSystemName');
											$ext2 = pathinfo($filename2, PATHINFO_EXTENSION);
											$fn2 = pathinfo($filename2, PATHINFO_FILENAME);
											if (substr($fn2,0,2) !== 'lt') {
												$fn2 = $item['itemGuid'];
												$fs2 = 'tn_';
												$filename2 = $fn2.'.'.$ext2;
											}
											$title2 = $this->getCatalogAttribute($fn2,'fixedTitle');
											$rg2 = $this->getItemRelated($fn2,'RELATED_IMAGE');
												
											?>
											<li>
												<div style="padding: 5px 0px 5px;" id="row_<?php echo $fn2; ?>">
													<img src="<?php echo $this->cdn('rim'); ?>/frontend/<?php echo $rg2['relatedGuid']; ?>/<?php echo $fs2.$filename2; ?>" height="70" width="80">
													<a href="javascript:;" id="<?php echo $fn2; ?>" class="irAction" style="text-decoration: none">[-]</a>
													<input value="<?php echo $title2; ?>" style="width: 310px;" id="<?php echo $fn2; ?>" name="fileImage" type="text" onchange="javascript:updateImageSet(this);">
													<input value='{"id":"<?php echo $fn2; ?>","title":"<?php echo $title2; ?>", "url":"<?php echo $this->cdn('rim'); ?>/frontend/<?php echo $rg2['relatedGuid']; ?>/<?php echo $fs2.$filename2; ?>"}' name="photos[]" type="hidden">
												</div>
											</li>
											<?php endforeach; ?>
											<?php endif; ?>
										</ul>
									</div><!-- eof beritafoto -->
									<?php endif; ?>
								</div>
								<div class="tab-pane" id="files">
									<div id="progress" class="progress" style="display: none;">
										<div class="progress-bar progress-bar-success"></div>
									</div>
									<p>
										<label>Or Upload File</label>
										<input type='file' name='uploadedFiles[]' id='fileupload' multiple />
									</p>
									<p class="help-block">
										You can select files/images to upload at the same time.
									</p>
									<p>
										<label for='fixedType'>Type</label>
										<select name='fixedType' id='fixedType' class="form-control">
											<option value="">--- Pilih ---</option>
											<option value='file'<?php if (Zend_Auth::getInstance()->getIdentity()->name == "Dc Admin") : ?> selected<?php endif; ?>>File</option>
											<option value='image'<?php if (Zend_Auth::getInstance()->getIdentity()->name == "News Admin") : ?> selected<?php endif; ?>>Image</option>
										</select>
									</p>
									<input type='hidden' name='profile' id='profile' value='kutu_doc'>
									
									<ul class="list-inline" id="ephotos"></ul>
									
									<div class='box-body'><div id="extraattribute"></div></div>
								</div>
							</div>
						</div>
					</div>
					
				</div>
				
			</div><!--/.col (left) -->
			<!-- right column -->
			<div class="col-md-6">
				<div class="box box-warning">
					<div class="box-header with-border">
						<h3 class="box-title">Relasi Katalog</h3>
						<div class="box-tools pull-right">
							<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
							<button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
						</div>
					</div>
					<div class="box-body">
						<p class="margin">Enter relation (you don't have to remember title exactly, there are suggestions based on your input):</p>
						<div class="form-group">
							<input type="text" id="relInput" class="form-control" placeholder="keywords" />
						</div>
						<p class="margin">List of selected relations (Click on title to remove it):</p>
						<div id="relsList" class="well" style="height: 200px; overflow: auto">
						<?php
						$relsDb = new App_Model_Db_Table_RelatedItem();
						$rels = $relsDb->fetchAll("relatedGuid='".$this->catalogGuid."' AND relateAs IN ('RELATED_OTHER','RELATED_ISSUE','RELATED_Clinic','RELATED_HISTORY','RELATED_BASE','RELATED_TRANSLATION_ID','RELATED_TRANSLATION_EN')");
						if ($rels) :
						foreach ($rels as $rel) :
						?>
						<span class="text-green">
							<?php if ($rel->relateAs == "RELATED_Clinic") { ?>
							<?php echo $this->getCatalogAttribute($rel->itemGuid,'fixedCommentTitle'); ?>
							<?php } else { ?>
							<?php echo $this->getCatalogAttribute($rel->itemGuid,'fixedTitle'); ?>
							<?php } ?>
							<input type="hidden" name="relIds[]" value="<?php echo $rel->itemGuid; ?>" />
							<input type="hidden" name="relGuids[]" value="<?php echo $rel->relateAs; ?>" />
						</span>
						<?php endforeach; ?>
						<?php endif; ?>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</form>
	<div id="confirmDialog"></div>
	<div id="messageDialog"></div>
</section>
<?php $this->headScript()->captureStart(); ?>
$(function () {
	$("input[name=fixedTitle]").prop('required',true);
	$("input[name=fixedAnswer]").prop('required',true);
	
	$.validator.addMethod('shortTitle', function(value) {
		value = value.replace(/^\s+|\s+$/g, '');
		var regex = new RegExp(/^[a-z0-9\-]+$/);
		if (value == '' || value.match(regex)) {
			return true;
		} else {
			return false;
		}
	});
	
	/**
	 * Automatically create shortTitle once user enter the title
	 */
	$('#fixedCommentTitle').bind('change', function() {
		$('#shortTitle').val(Pandamp.Util.generateShortTitle($(this).val()));
	});
	
	$('#datetimepicker1').datetimepicker({
		pick12HourFormat: false,
		sideBySide: true
	});
	
	$('#datetimepicker2').datetimepicker({
		pick12HourFormat: false,
		sideBySide: true
	});
	
	$('#fixedKeywords').tagsInput();
	
	$("[rel=tooltip]").tooltip({ placement: 'right'});
	
	$('#relsList').find('span').click(function(){
		$(this).remove();
	});
	
	$('#relInput').autocomplete({
		source: "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/suggest?limit=10&profile=klinik",
		select: function( event, ui ) {
			if ($('#relsList').find('input[type="hidden"][value="' + ui.item.value + '"]').length == 0) {
				$('<p/>')
					.html(ui.item.label)
					.addClass("text-green")
					.append($('<input/>').attr('type', 'hidden').attr('name', 'relIds[]').val(ui.item.value))
					.append($('<input/>').attr('type', 'hidden').attr('name', 'relGuids[]').val('RELATED_Clinic'))
					.click(function() {
						$(this).remove();
					}).appendTo($('#relsList'));
			}
			
			$(this).val('');
			
			return false;
			
		}, 
		open: function() {
			$(".ui-autocomplete").css({
				"z-index":1000,
				"font-size": "12px"
			});
		}
	
	});
	
	 /**
	 * Search for photos
	 * @param string url The url which returns the result in JSON format
	 */
	function searchFiles(url) {
		$('#searchPhotos').html('').addClass('mloading');
		$.ajax({
			url: url,
			type: 'GET',
			success: function(response) {
				var res = $.evalJSON(response);
				var files = res.files;
				$('#searchPhotos').removeClass('mloading');
				$('#searchPhotos').html('');
				$(files).each(function(i) {
					var li = $('<li/>');
					var coverImages = files[i];
					
					$('<img/>').attr('src', files[i].url).click(function() {
						setCoverForSet(coverImages);
					}).appendTo(li);
					
					$('<a/>').attr('href', 'javascript: void(0);').html('[+]')
					.css('text-decoration', 'none')
					.click(function() {
						addImageToSet($(this));
					}).appendTo(li);
					
					/**
					 * Add input element to indicate which files will be added to set later
					 */
					var urls = {};
					for (var thumb in files[i]) {
						urls[thumb] = files[i][thumb]; 
					}
					$(li).append($('<input/>').attr('type', 'hidden').val($.toJSON(urls)))
						.prependTo($('#searchPhotos'));
					
					
				});
				
				$('#searchPager').html(res.paginator).find('a').each(function() {
					var link = $(this).attr('href');
					$(this).attr('href', 'javascript: void(0);').click(function() {
						searchFiles(link);
					});
				});
				
				
			},
			error: function(xhr, status, error) {
				alert( "Request failed: " + status );
			}
		});
		
	}
	
	function setCoverForSet(images) {
		$('#articleImageContainer').html('<img src="' + images.url + '" width="80" height="70" />');
		var div = $('<div/>').css('padding', '5px 0 0 0');
	    $(div).append($('<input/>').val(images.title)
	    .attr('type', 'text').attr('name', 'fileImage').attr('id', 'fileImage')
	    .addClass('form-control'))
	    .append($('<input/>').attr('type', 'hidden').attr('name','fixedFileImage').val(images.url))
	    .appendTo('#articleImageContainer');
	    
	}	 
	
	/**
	 * Add image to set when user click on + link
	 * @param link The HTML link
	 */
	function addImageToSet(link) {
		var li = $(link).parent().clone(true);
		$(li).find('a:first').remove();
		var cloneLink = $(link).clone();
		$(cloneLink).html('[-]').unbind('click').bind('click', function() {
			removeImageFromSet($(this));
		});
		$(li).find('input').attr('name', 'photos[]');
		$(li).append(cloneLink).appendTo($('#filesSet'));
		$(link).parent().remove();	
		
	}	
	
	/**
	 * Remove image from set when user click on - link
	 * @param link The HTML link
	 */
	function removeImageFromSet(link) {
		var li = $(link).parent().clone(true);
		$(li).find('a:first').remove();
		var cloneLink = $(link).clone();
		$(cloneLink).html('[+]').unbind('click').bind('click', function() {
			addImageToSet($(this));
		});
		$(li).find('input').attr('name', '');
		$(li).append(cloneLink).appendTo($('#uploadedPhotos'));	
		$(link).parent().remove();
	};
	
	/**
	 * Search handler
	 */
	 $('#searchButton').click(function(){
	 	var exp = {
	 		keyword: $('#keyword').val(),
	 		format: 'JSON'
	 	};
	 	var q = rawurlencode(base64_encode($.toJSON(exp)));
	 	searchFiles('<?php echo $this->url(array('lang'=>$this->getLanguage()),'search_catalog_findimage'); ?>?q=' + q);
	 });
	 
	 $('#searchButton').click();
	 
    $('#fileupload').fileupload({
    	url: '<?php echo $this->url(['lang'=>$this->getLanguage()],'upload_file_upload'); ?>',
    	dataType: 'json',
    	done: function (e, data) {
    		if(data.result) {
    			if (data.result.original.type == "file") {
    				var presentImage = "<div style='padding:5px'>"+data.result.original.title+"</div>";
    			}
    			else
    			{
    			var presentImage = $('<img/>');
    			$(presentImage).attr('src', data.result.original.url)
	    			.attr('width', '100').attr('height', '100')
					.attr('style', 'cursor: pointer')
					.click(function() {
						console.log($.toJSON(data.result));
					});
				}
				var select = $('<select/>');
				$(select).attr('width', '100');
				$('<option/>').attr('value', '').html('--- Pilih ---').appendTo(select);
				$('<option/>').attr('value', 'caption').attr('data-options',data.result.original.id)
					.attr('data-name',data.files[0].name)
					.html('Insert Caption')
					.appendTo(select);
				$(select).change(function() {
					if ($(this).val() != '') {
						if ($(this).val() == 'caption') {
							addFormAttribute($(this).val(), $(this).find('option:selected').data('options'), $(this).find('option:selected').data('name'));
						}
					}
				});	
				$('<li/>').append(presentImage)
				.append($('<input/>').attr('type', 'hidden').attr('name','filename[]').val(data.files[0].name))
				.append($('<input/>').attr('type', 'hidden').attr('name','fileUrl[]').val($.toJSON(data.result)))
				.append($('<br/>')).append(select).appendTo($('#ephotos'));
    			
    			$('#progress').hide();
    		}
    		
    		
    	},
    	fail: function (e, data) {
    		$.each(data.messages, function (index, error) {
    			alert('Upload file error: ' + error);
    		});
    	},
    	progressall: function (e, data) {
    		var progress = parseInt(data.loaded / data.total * 100, 10);
    		$('#progress .progress-bar').css(
                'width',
                progress + '%'
            );
    	},
    	add: function (e, data) {
    		var uploadErrors = [],
    			type = $('select[name=fixedType]').val();
    		
    		console.log(type + ' ' + data.originalFiles[0]['size']);	
    		if(type == 'image' && data.originalFiles[0]['size'] > 500000) {
    			uploadErrors.push('Filesize is too big');
    		}
    		if(uploadErrors.length > 0) {
    			alert(uploadErrors.join("\n"));
    		}
    		else
    		{
				data.submit();
			}
    	},
    	start: function(e) {
    		$('#progress').css({display:'block'});
    	}
    }).bind('fileuploadsubmit',function (e, data) {
    	var type = $('select[name=fixedType]').val(),
    	guid = '<?php echo $this->catalogGuid; ?>';
    	data.formData = {type:type,guid:guid};
    	if (!data.formData.type) {
    		alert('Pilih Jenis Upload');
			data.context.find('button').prop('disabled', false);
			return false;
    	}
    });
    
	$('#editPost').validator().on('submit', function (e) {
	  	if (e.isDefaultPrevented()) {
	    	$('#confirmDialog').html('form is not valid!Please check again')
	    		.dialog({
	    			title:'Error',
	    			modal: true,
	    			closeOnEscape: false,
	    			resizable: false,
	    			open: function(event, ui) {
						$('.ui-dialog-titlebar-close').hide();
						$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
					},
	    			buttons: {
	    				'OK': function() {
							$(this).dialog('destroy').empty();
						}
	    			}
	    		});
	  	} else {
	    	e.preventDefault();
	    	var inst = FCKeditorAPI.GetInstance("fixedAnswer");
			var sValue = inst.GetHTML();
    		if (sValue) {
			    $("#showfckdatanswer").val(sValue);   
			}
	    	var instq = FCKeditorAPI.GetInstance("fixedCommentQuestion");
			var cqValue = instq.GetHTML();
    		if (cqValue) {
			    $("#showfckdatquestion").val(cqValue);   
			}
			
    		var vardata = $('#editPost').serialize();
    		$('.box-footer > button').attr({'disabled':'disabled'});
    		$('#wait').html('Simpan database...tunggu...').addClass('label label-warning').fadeIn();
    		$.post('', vardata, function(data){
    			if (data.response == true) {
    				$('#wait').html(data.message).addClass('label label-warning').fadeIn('fast',function(){
    					setTimeout(function() {
               					window.location = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/<?php echo $this->currentNode; ?>";
               				},2000);
    				});
    				$('.box-footer > button').removeAttr('disabled');
    			}
    			else
    				$('#wait').html('Ada masalah...Kontak IT').addClass('label label-warning').fadeIn();
    			
    		}, "json");
		}
	});    
	
	$('a.irAction').click(function(){
		var self = this,
			val = $(this).attr('id'),
			rg = '<?php echo $this->catalogGuid; ?>';
	
		$('#confirmDialog').html('<div class="alert alert-warning">These items will be deleted.</div><p><?php echo addslashes("Are you sure?"); ?></p>')
		.dialog({
			width: 420,
			modal: true,
			title: "Confirm",
			buttons: [
			{
				html: "<i class='fa fa-trash'></i>&nbsp; Delete items",
				"class" : "btn btn-danger btn-xs",
				click: function() {
					$(this).dialog('destroy');
					$('#confirmDialog').empty();
				
					$('#row_'+val).html('').addClass('mloading');
				
					$.ajax({
						type: 'POST',
						url: '<?php echo $this->APP_STATIC_SERVER; ?>/<?php echo $this->getLanguage(); ?>/api/catalog/delrel',
						data: { itemGuid: val, relatedGuid:rg, relateAs:'RELATED_IMAGE' },
						success: function(response) {
							if ('RESULT_OK' == response) {
								$('#row_'+val).removeClass('mloading');
								$('#row_'+val).remove();
								$('#messageDialog').html('<?php echo $this->escape('The catalog have been deleted successfully.'); ?>')
								.dialog({
									title: "<div class='alert alert-success'><?php echo $this->escape('Message'); ?></div>",
									title_html: true,
									modal: true,
									show: { effect: 'fade' },
									open: function(event, ui) {
										setTimeout(function() {
											$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
											$('#messageDialog').empty();
										}, 3000);
									}
								});
							}
							
						}
					});
					
				}
			},
			{
				html: "<i class='fa fa-remove'></i>&nbsp; Cancel",
				"class" : "btn btn-xs",
				click: function() {
					$( this ).dialog( "destroy" );
					$('#confirmDialog').empty();
				}
			}
			]
		
		});
		
		
	});
	
});

function updateImageSet(el)
{
	var guid = $(el).attr('id'),
		val = $(el).val();
	$('#'+guid).html('').addClass('mloading');
    $.ajax({
    	url: '<?php echo $this->APP_STATIC_SERVER; ?>/<?php echo $this->getLanguage(); ?>/api/catalog/updatecatalogattribute',
    	type: 'POST',
    	data: {guid:guid,title:val,attributeGuid:'fixedTitle'},
    	success: function(response) {
    		if ('RESULT_OK' == response) {
    			$('#messageDialog').html('Title has been updated successfully.')
				.dialog({
					width: 420,
					resizable: false,
					modal: true,
					title: "Message",
					open: function(event, ui) {
						setTimeout(function() {
							$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							$('#'+guid).removeClass('mloading');
							$('#messageDialog').html('');
								
							}, 3000);
					}
				});
					
    			
    		}
    			
    	}
    });
}

function addFormAttribute(v,fileId,name)
{
	$('#extraattribute').append("<div class='form-group col-xs-9'>"+
	"<input type='text' name='attr_" + v + "_" + fileId + "[]' class='form-control' placeholder='"+ucfirst(v)+": "+name+"'></div>"+
	"</div>");
}
<?php $this->headScript()->captureEnd(); ?>