<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <?php echo $this->slideMenu->render(); ?>
            <fieldset>
                <legend>Navigation</legend>
                <?php echo $this->widget2->render(); ?>
            </fieldset>
            <fieldset>
                <legend>Data Center</legend>
                <?php echo $this->widget1->render(); ?>
            </fieldset>
            <h5>Number of Catalogs: <?php echo $this->totalItems; ?> Record(s)</h5>
            <form id="frmCatalogs" name="frmCatalogs" method="post">
                <div class="align-left">
                Sort By:
                <select id="sort" name="sort">
                    <option value="title">Title</option>
                    <option value="publishedDate">Published Date</option>
                    <option value="createdDate">Created Date</option>
                </select>
                <select id="sortBy" name="sortBy">
                    <option value="asc">Ascending</option>
                    <option value="desc" selected>Descending</option>
                </select>
                </div>
                <div class="align-right">
                <select id="ws" name="ws">
                    <option value="withselected">With selected:</option>
                    <option value="delete">Delete</option>
                    <option value="edit">Edit</option>
                    <option value="copy">Copy</option>
                    <option value="move">Move</option>
                    <option value="recycle">Recycle</option>
                </select>
                </div>
                <div style="display:none"></div>
                <table class="display stylized" id="catalog">
                    <thead>
                        <tr>
                            <th><input name="select_deselect" value="1" type="checkbox"></th>
                            <th>Title</th>
                            <th>Section</th>
                            <th>Published</th>
                            <th>Created on</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php //foreach ($this->hits->response->docs as $hit) { ?>
                    <?php 
                    $now = date('Y-m-d H:i:s');
                    foreach ($this->hits as $hit) { 
                    $rowUser = App_Model_Show_User::show()->getUserByName($hit['createdBy']);
                    ?>
                        <tr>
                            <td><input type='checkbox' name='catalogGuid[]' id='catalogGuid' value='<?php echo $hit['guid']; ?>' class="check_me"></td>
                            <td>
                                <?php if($hit['profileGuid'] == 'kutu_doc') { ?>
                                    <a href="<?php echo ROOT_URL; ?>/browser/downloadfile/guid/<?php echo $hit['guid']; ?>"><div class="searchResultTitle">File: <?php try { echo $this->getCatalogAttribute($hit['guid'],'fixedCommentTitle').' ['.$hit['guid'].']'; } catch (Exception $e) { echo ''; } ?></div></a>
                                <?php } else { ?>
                                    <a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $hit['guid']; ?>/node/<?php echo $this->currentNode; ?>" title="<?php echo $rowUser['email']; ?>"><?php try { echo $this->getCatalogAttribute($hit['guid'],'fixedCommentTitle'); } catch (Exception $e) { echo 'No-Title'; } ?></a>
                                <?php } ?>
                                    <br><small>id:<?php echo $hit['guid']; ?> - by: <?php echo $hit['createdBy']; ?>&nbsp;<span class="subtitle"><?php echo $hit['publishedDate']; ?></span></small>
	                                <?php $rowUser = App_Model_Show_User::show()->getUserByName($hit['createdBy']); ?>
	                                <br><small><a href="mailto:<?php echo $rowUser['email']; ?>"><?php echo $rowUser['email']; ?></a></small>
                            </td>
                            <td><?php echo $hit['profileGuid']; ?></td>
                            <td>
                                <?php
//                                $t = str_replace("Z", "", $hit['publishedDate']);
//                                $d = explode("T", $t);
//                                $publishedDate = $d[0].' '.$d[1];
//
//                                $et = str_replace("Z", "", $hit['expiredDate']);
//                                $ed = explode("T", $et);
//                                $expiredDate = $ed[0].' '.$ed[1];
//                                if ($expiredDate == "1999-12-31 00:00:00") $expiredDate = '0000-00-00 00:00:00';

                                if ($now <= $hit['publishedDate'] && $hit['status'] == 99) {
                                    $status = "publish_y";
                                    $ht = "Published, but is Pending";
                                }
				else if (($now <= $hit['expiredDate'] || $hit['expiredDate'] == '0000-00-00 00:00:00') && $hit['status'] == 99) {
                                    $status = "publish_g";
                                    $ht = "Published and is Current";
				}
				else if ($now > $hit['expiredDate'] && $hit['status'] == 99) {
                                    $status = "publish_r";
                                    $ht = "Published, but has Expired";
				}
				else if ($hit['status'] == 0) {
                                    $status = "publish_x";
                                    $ht = "Not Published";
				}
				else if ($hit['status'] == -1) {
                                    $status = "disabled";
                                    $ht = "Archived";
				}
                                ?>

                                <div class="ta-center" title="<?php echo $ht; ?>">
                                    <img src="<?php echo $this->cdn('images'); ?>/<?php echo $status; ?>.png">
                                </div>
                            </td>
                            <td nowrap>
                                <?php echo date('d.m.y H:i:s',strtotime($hit['createdDate'])); ?><br>
                                <small>modifiedBy: <?php echo $hit['modifiedBy']; ?></small>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </form>
            <table width='100%'>
            <tr>
                <td align=right><div id='catalogPagination' class="pagination"></div></td>
            </tr>
            </table>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>
    <div class="content-box">
        <?php echo $this->action('rightdown','misc','dms',array('node'=>$this->currentNode)); ?>
    </div>
</aside>
<!-- End of Right column/section -->