<h3>Register</h3>

<? if (isset($this->message)): ?>
<div class="box box-info closeable">
    <?= $this->message; ?>
</div>
<? endif; ?>

<? if (isset($this->error_message)): ?>
<div class="box box-error">ERROR</div>
<div class="box box-error-msg">
    <ol>
        <li>Your registration was <strong>failed</strong>. Please try again.</li>
        <li>We truly apologize for the inconvenience.</li>
    </ol>
</div>
<? endif; ?>

<form id="registerform" method="post" action="<?php $_SERVER['PHP_SELF'];?>" style="z-index:1;overflow:hidden;">

    <fieldset>
        <legend>Get started with hukumonlineID</legend>

        <p>
            <label for="promotioncode">Promotion Code:</label><br>
            <input id="promotioncode" class="full" name="promotioncode" type="text" value="<?=$this->value['promotioncode'];?>" />
        </p>
        <p>
            <label class="required" for="fullname">Full Name:</label><br>
            <input id="fullname" class="full" name="fullname" type="text" value="<?=$this->value['fullName'];?>" />
        </p>
        <p>
            <label for="chkGender">Gender:</label><br>
            <?=$this->gender();?>
        </p>
        <? $lang['months'] = array("January","February","March","April","May","June","July","August","September","October","November","December"); ?>
        <p>
            <label for="birthOfDate">Birth Of Date:</label><br>
            <?=$this->month($lang['months']).$this->day().$this->year();?>
        </p>
        <p>
            <label for="education">Education:</label><br>
            <?=$this->education();?>
        </p>
        <p>
            <label for="expense">Monthly expenses:</label><br>
            <?=$this->expense();?>
        </p>
        <p>
            <label for="company">Company:</label><br>
            <input id="company" class="full" name="company" type="text" value="<?=$this->value['company'];?>" />
        </p>
        <p>
            <label for="businessType">Business Type:</label><br>
            <?=$this->businessType($this->value['businessType']);?>
        </p>
        <p>
            <label for="address">Address:</label><br>
            <textarea name="address" class="medium" cols="30" rows="5"><?=$this->value['address'];?></textarea>
        </p>
        <p>
            <label for="city">City:</label><br>
            <input id="city" class="full" name="city" type="text" value="<?=$this->value['city'];?>" />
        </p>
        <?
        $state = ($this->value['province'])? $this->value['province'] : 7;
        ?>
        <p>
            <label for="province">State:</label><br>
            <?=$this->state($state);?>
        </p>
        <?
        $countryId = ($this->value['countryId'])? $this->value['countryId'] : "ID";
        ?>
        <p>
            <label for="country">Country:</label><br>
            <?=$this->country("countryId",$countryId);?>
        </p>
        <p>
            <label for="zip">PostalCode:</label><br>
            <input id="zip" class="small" name="zip" type="text" value="<?=$this->value['zip'];?>" />
        </p>
        <p>
            <label for="phone">Phone:</label><br>
            <input id="phone" class="small" name="phone" type="text" value="<?=$this->value['phone'];?>" />
        </p>
        <p>
            <label for="fax">Fax:</label><br>
            <input id="fax" class="small" name="fax" type="text" value="<?=$this->value['fax'];?>" />
        </p>
        <p>
            <label for="payment">Subscription:</label><br>
            <input id="payment" class="small" name="payment" type="text" size="2" value="<?=$this->value['payment'];?>" />&nbsp;month
            <small>.:Corporate or Individual Subscriber</small>
        </p>
    </fieldset>

    <fieldset>
        <legend>Enter Your E-mail Address</legend>
        <p>
            <label class="required" for="email">E-mail:</label><br>
            <input id="email" class="full" name="email" type="text" value="<?=$this->value['email'];?>" />
        </p>
    </fieldset>

    <fieldset>
        <legend>Choose Your GROUP PACKAGE</legend>
        <?
        $selected_group = isset($this->value['aro_groups'])? $this->value['aro_groups'] : '';
        ?>
        <label class="required" for="aro_groups">Package:</label><br>
        <select name="aro_groups" size="8"><?=$this->groupTree(array($selected_group));?></select>
    </fieldset>

    <?
    if (isset($this->value['iscontact']) == 1) {
        $isContact = 'checked';
    } else {
        $isContact = '';
    }
    ?>
    <fieldset>
        <legend>Choose Your Username</legend>
        <p>
            <input name="iscontact" id="iscontact" type="checkbox" value="1" <?=$isContact;?>>&nbsp;Contact Person<br/><br/>
            <label class="required" for="username">Username:</label><br>
            <input id="username" class="full" name="username" type="text" />
        </p>

        <p>
            <label class="required" for="password">Password:</label><br>
            <input id="password" class="full" name="password" type="password" />
        </p>

    </fieldset>
    
    <?
    if (isset($this->value['newArticle']) == 1) {
        $newArticlechecked = 'checked';
    } else {
        $newArticlechecked = '';
    }
    if (isset($this->value['newWeeklyRegulation']) == 1) {
        $weeklyListchecked = 'checked';
    } else {
        $weeklyListchecked = '';
    }
    if (isset($this->value['newRegulation']) == 1) {
        $monthlyListchecked = 'checked';
    } else {
        $monthlyListchecked = '';
    }
    ?>
    <fieldset>
        <legend>Newsletter</legend>
        <p>
            <input type="checkbox" name="newArticle" value="1" <?=$newArticlechecked;?>>&nbsp;News article<br>
            <input type="checkbox" name="newWeeklyRegulation" value="1" <?=$weeklyListchecked;?>>&nbsp;Weekly regulations<br>
            <input type="checkbox" name="newRegulation" value="1" <?=$monthlyListchecked;?>>&nbsp;Monthly regulations
        </p>
    </fieldset>

    <?
    if (isset($this->value['ec']) == 1) {
        $emailSend = 'checked';
    } else {
        $emailSend = '';
    }
    ?>
    <fieldset>
        <legend>Email Confirmation</legend>
        <p>
            <input type="checkbox" name="ec" value="1" <?=$emailSend;?>>&nbsp;Send
        </p>
    </fieldset>

    <?
    $auth = Zend_Auth::getInstance();
    if ($auth->hasIdentity())
        $createdBy = $auth->getIdentity()->username;
    else
        $createdBy = "";
    ?>
    <input type="hidden" name="createdBy" value="<?=$createdBy;?>" />
    <p>
        <input class="btn btn-green big" value="Process" type="submit" />
        <input class="btn btn-green big" value="Reset" type="reset" />
    </p>

    <div class="clear">&nbsp;</div>

</form>
