<?
if (count($this->userQueue) > 0) :
?>
<h4>Queue List</h4>
<hr/>
<form method="post">
<table class="display stylized">
    <thead>
        <tr>
            <th>Name</th>
            <th>Group</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <? $i=1; foreach($this->userQueue as $row): ?>
        <tr class="<?=($i%2 ? 'gradeX' : 'gradeC');?>">
            <td><?=$row['username'];?></td>
            <td><?=$this->group($row['packageId']);?></td>
            <td>
                <? if ($this->isAllowed('membership','all')) { ?>
                <input type="button" name="action" value="Approve" onclick="javascript: window.location.href='<?=$this->url(array('lang'=>$this->getLanguage(), 'controller'=>'user','module'=>'customer','action'=>'set.approval','id'=>$row['kopel']),'customer'); ?>';" class="btn" />
                <? } else { ?>
                <input type="button" name="action" value="Approve" disabled class="btn small" />
                <? } ?>
            </td>
        </tr>
        <? $i++; endforeach;?>
    </tbody>
</table>
</form>
<? endif; ?>