<?php
if ($this->aData['totalCount'] > 0) {
?>
<h4>Queue List</h4>
<hr/>

	<div class="align-right">
	Number of record(s): <span id="numOfRecords"><?php echo $this->aData['totalCount']; ?></span>
	</div>
	<?php if ($this->isAllowed('membership','all')) { ?>
	<div class="align-left">
		&nbsp;&nbsp;&nbsp;&nbsp;<input name='select_deselect' id='select_deselect' type='checkbox'>&nbsp;<abbr>Select All</abbr> |
		<a href="javascript: void(0);" class="approvedAction">Approved</a> |
		<a href="javascript: void(0);" class="suspendedAction">Suspended</a>
	</div>
	<?php } ?>
	<div id='catalogContent'>
		
	</div>
	<table width='100%'>
		<tr>
			<td width=35%>&nbsp;</td>
			<td align=right><div id='catalogPagination' class="pagination"></div></td>
		</tr>
	</table>
	
	<div id="confirmDialog"></div>

    <script>
    $(document).ready(function(){
    	
		var isFirstTime = 1;
		
		var myPageIndex = 0;
		var itemsPerPage = <?php echo $this->aData['limit']; ?>
		
		$("#catalogPagination").pagination(<?php echo $this->aData['totalCount']; ?>, 
		{items_per_page:itemsPerPage, callback:handlePaginationClick}
		);
		
		function handlePaginationClick(new_page_index, pagination_container) 
		{
			
			myPageIndex = new_page_index;
			myStart = (<?php echo $this->aData['limit']; ?> * myPageIndex);
			
			if(true)
			{
				if($('#tblCatalogPager-'+myPageIndex).length==0)
				{
					//$('#message_box').show();
					$.getJSON('<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/user/getappuser/start/'+myStart+'/limit/<?php echo $this->aData['limit']; ?>', '', testJson);
				}
				else
					showCatalogContent();
			}
			return false;
		}
		function testJson(res)
		{
			size = res.users.length;
			var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<div class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
			tblRow += "<table class='display stylized'><thead><tr><th>&nbsp;</th><th>Kopel</th><th>Username</th><th>Company</th><th>Group</th><th>Status</th></tr></thead><tbody>";
			
			
			for(i=0;i<size;i++)
			{
				tblRow += 
					"<tr id='row_"+res.users[i].kopel+"' class="+(i%2 ? 'gradeX' : 'gradeC')+">"
					<?php if ($this->isAllowed('membership','all')) { ?>
					+"<td>"+res.users[i].checkbox+"</td>"
					<?php } ?>
					+"<td>"+res.users[i].kopel+"</td>"
					+"<td>"+res.users[i].username+"</td>"
					+"<td width='25%'>"+res.users[i].company+"</td>"
					+"<td>"+res.users[i].group+"</td>"
					+"<td>"+res.users[i].status+"</td>"
					+"</tr>";
					
					
			}
			tblRow += "</tbody></table></div>";
			$(tblRow).appendTo("#catalogContent");
			showCatalogContent();
			//$('#message_box').fadeOut();
			
			
		}
		function showCatalogContent()
		{
			$('.tblCatalogPager').hide();
			$('#tblCatalogPager-'+myPageIndex).show();
			if(!isFirstTime)
				//window.location.hash = '#a-'+myPageIndex;
				Scroller.scroll();
			isFirstTime = 0;
		}
		
		function testCount()
		{
			$.getJSON('<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/user/countuserappbyquery/start/'+myStart+'/limit/<?php echo $this->aData['limit']; ?>', '', callbackTestCount);
		}
		function callbackTestCount(res)
		{
			$("#numOfRecords").html(res);
			$("#catalogPagination").pagination(res, 
			{items_per_page:itemsPerPage, callback:handlePaginationClick}
			);
			testInitiateFirstPagingClick();
		}
		function testInitiateFirstPagingClick()
		{
			$("#catalogContent").html("");
			myPageIndex = 0;
			myStart = (<?php echo $this->aData['limit']; ?> * myPageIndex);
			
			if(true)
			{
				if($('#tblCatalogPager-'+myPageIndex).length==0)
				{
					//$('#message_box').show();
					$.getJSON('<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/user/getalluser/start/'+myStart+'/limit/<?php echo $this->aData['limit']; ?>', '', testJson);
				}
				else
					showCatalogContent();
			}
		}
		
		
    	
		/**
		 * Select/Deselect all rows handler
		 */
		$('#select_deselect').click(function() {
			$('input[type="checkbox"].check_me').attr('checked', $(this).attr('checked'));
		});	
		
		<?php if ($this->isAllowed('membership','all')) : ?>
		$('a.approvedAction').click(function(){
			var numSelected = $('input[type="checkbox"].check_me:checked').length;
			var self = this;
			if (0 == numSelected) {
				$('#confirmDialog').html('<?php echo addslashes("Please select at least one user"); ?>')
					.dialog({
						title: '<?php echo addslashes("Error"); ?>',
						dialogClass: 't_a_ui_dialog',
						modal: true,
						closeOnEscape: false,
						resizable: false,
						open: function(event, ui) {
							$('.ui-dialog-titlebar-close').hide();
							$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
						},
						buttons: {
							'<?php echo addslashes("OK"); ?>': function() {
								$(this).dialog('destroy');
							}
						}
					});
				
			}
			else
			{
				var ids = new Array();
				$('input[type="checkbox"].check_me:checked').each(function() {
					ids.push($(this).val());
				});
				
				$.ajaxq('customer', {
					url: "<?php echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'user','module'=>'customer','action'=>'set.approval'),'customer'); ?>",
					type: 'POST',
					data: { id: $.toJSON(ids) },
					success: function(response) {
						if ('RESULT_OK' == response) {
							window.location.reload();
						}
					}
				});
				
			}
		});
		<?php endif; ?>
	    
		<?php if ($this->isAllowed('membership','all')) : ?>
		$('a.suspendedAction').click(function(){
			var numSelected = $('input[type="checkbox"].check_me:checked').length;
			var self = this;
			if (0 == numSelected) {
				$('#confirmDialog').html('<?php echo addslashes("Please select at least one user"); ?>')
					.dialog({
						title: '<?php echo addslashes("Error"); ?>',
						dialogClass: 't_a_ui_dialog',
						modal: true,
						closeOnEscape: false,
						resizable: false,
						open: function(event, ui) {
							$('.ui-dialog-titlebar-close').hide();
							$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
						},
						buttons: {
							'<?php echo addslashes("OK"); ?>': function() {
								$(this).dialog('destroy');
							}
						}
					});
				
			}
			else
			{
				var ids = new Array();
				$('input[type="checkbox"].check_me:checked').each(function() {
					ids.push($(this).val());
				});
				
				$.ajaxq('customer', {
					url: "<?php echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'user','module'=>'customer','action'=>'set.suspended'),'customer'); ?>",
					type: 'POST',
					data: { id: $.toJSON(ids) },
					success: function(response) {
						if ('RESULT_OK' == response) {
							window.location.reload();
						}
					}
				});
				
			}
		});
		<?php endif; ?>
	    
    });
    </script>

<?php } ?>