<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <h3>User Management: Group Associate</h3>
            <?php if (isset($this->message)) : ?>
            <div class="box box-info closeable">
                <?php echo $this->message; ?><br/>
            </div>
            <?php endif; ?>

            <form id="associate" method="post" action="">
                <fieldset>
                    <legend>Upgrade - Downgrade Package</legend>
                    <p>
                        <label class="required" for="aro_groups">Package:</label><br>
                        <select name="aro_groups" size="8"><?php echo $this->groupTree(array($this->user['packageId'])); ?></select>
                    </p>
                    <p>
                        <input type="hidden" name="id" id="id" value="<?php echo $this->user['kopel']; ?>">
                        <input type="hidden" name="username" id="username" value="<?php echo $this->user['username']; ?>">
                        <input value="Change Package" type="submit" class="btn btn-blue" />
                    </p>
                </fieldset>
                <div class="clear">&nbsp;</div>
            </form>
        </div>
    </div>

    <div class="colgroup leading">
        <div class="column width6 first">
        	<fieldset>
        		<legend>ROLE</legend>
        		<div class="box box-success" id="message"></div>
        		<?php if (isset($this->UserRoles)) { ?>
        		<table class="no-style full">
        		<tbody>
        		<?php for($i=0;$i<count($this->UserRoles);$i++) { ?>
				<tr class="<?php echo ($i%2 ? 'gradeX' : 'gradeC'); ?>" id="row_<?php echo str_replace(' ','_',$this->UserRoles[$i]); ?>">
					<td><abbr><?php echo $this->UserRoles[$i]; ?></abbr></td>
					<td><input type="button" name="delass" value="Delete" id="<?php echo $this->UserRoles[$i]; ?>/uname/<?php echo $this->user['username']; ?>" class="form-button" /></td>
				</tr>        		
        		<?php } ?>
        		</tbody>
        		</table>
        		<?php } ?>
        	</fieldset>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('rightupmenu','user','customer',array('id'=>$this->user['kopel'])); ?>
    </div>
    <div class="content-box">
        <?php echo $this->action('rightdownmenu','user','customer',array('id'=>$this->user['kopel'])); ?>
    </div>
</aside>
<!-- End of Right column/section -->