<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <h3>User Management: Change Password</h3>
            <?php if (isset($this->message)) : ?>
            <div class="box box-info closeable">
                <?php echo $this->message; ?><br/>
            </div>
            <?php endif; ?>

            <form id="changepassword" method="post" action="">
                <fieldset>
                    <legend>Create new password</legend>
                    <p>
                        <label class="required" for="opasswd">Old password:</label><br>
                        <input name="opasswd" id="opasswd" type="password" class="half" />
                    </p>
                    <p>
                        <label class="required" for="newpasswd">New password:</label><br>
                        <input name="newpasswd" id="newpasswd" type="password" class="password" value="" maxlength="20" />
                    </p>
                    <p>
                        <label class="required" for="rpasswd">Retype password</label><br>
                        <input name="rpasswd" id="rpasswd" type="password" class="half" />
                    </p>
                    <p>
                        <input type="hidden" name="id" id="id" value="<?php echo $this->user['kopel']; ?>">
                        <input value="Change Password" type="submit" class="btn btn-blue" />
                    </p>
                </fieldset>
                <div class="clear">&nbsp;</div>
            </form>
        </div>
    </div>

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php //echo $this->action('approval','user','customer'); ?>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('rightupmenu','user','customer',array('id'=>$this->user['kopel'])); ?>
    </div>
    <div class="content-box">
        <header style="cursor: s-resize;">
                <h3>Others</h3>
        </header>
        <section>
                <dl>
                    <dt>Hmm..where's the log?</dt>
                    <dd><a href="#"><abbr>Access Log</abbr></a></dd>
                    <dt>Change group: Upgrade or Downgrade</dt>
                    <dd><a href="#"><abbr>ASSOCIATE</abbr></a></dd>
                    <dt>User Invoice, Renew or Create One</dt>
                    <dd><a href="#"><abbr>Invoice</abbr></a></dd>
                </dl>
        </section>
    </div>
</aside>
<!-- End of Right column/section -->