<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <h3>User Management: Edit</h3>
            <?php if (isset($this->message)) : ?>
            <div class="box box-info closeable">
                <?php echo $this->message; ?><br/>
                <?php
                echo '<pre>';
                print_r($this->data);
                echo '</pre>';
                ?>
            </div>
            <?php endif; ?>

            <form id="edituser" method="post" action="">
                <fieldset>
                    <legend>Login Info</legend>
                    <p>
                        <label for="username">Username:</label><br>
                        <?php echo $this->user['username']; ?>
                    </p>
                </fieldset>
                <fieldset>
                    <legend>User Details</legend>
                    <p>
                        <label for="kopel">Customer Code:</label>
                        <input type="hidden" name="id" value="<?php echo $this->user['kopel']; ?>" />
                        <?php echo $this->user['kopel']; ?>
                    </p>
                    <p>
                        <label for="company">Company:</label>
                        <?php echo $this->user['company']; ?>
                    </p>
                    <p>
                        <label for="createdDate">Created Date:</label>
                        <?php echo date('l F jS, Y \a\t g:ia',strtotime($this->user['createdDate'])); ?>
                    </p>
                    <p>
                        <label for="createdBy">Created By:</label>
                        <?php echo $this->user['createdBy']; ?>
                    </p>
                    <?php if ($this->user['modifiedDate'] !== "0000-00-00 00:00:00") : ?>
                    <p>
                        <label for="modifiedDate">Modified Date:</label>
                        <?php echo date('l F jS, Y \a\t g:ia',strtotime($this->user['modifiedDate'])); ?>
                    </p>
                    <p>
                        <label for="modifiedBy">Modified By:</label>
                        <?php echo $this->user['modifiedBy']; ?>
                    </p>
                    <?php endif; ?>
                    <p>
                        <label for="promotioncode">Promotion Code:</label><br>
                        <input id="promotioncode" class="small" name="promotioncode" type="text" value="<?php echo $this->user['promotionId']; ?>" />
                    </p>
                    <p>
                        <label for="fullname">Full Name:</label><br>
                        <input id="fullname" class="half" name="fullname" type="text" value="<?php echo $this->user['fullName']; ?>" />
                    </p>
                    <?php
                    if ($this->user['gender'] == 'L')
                    {
                            $gender = 1;
                    }
                    else if($this->user['gender'] == 'P')
                    {
                            $gender = 2;
                    }
                    else
                    {
                            $gender = 0;
                    }
                    ?>
                    <p>
                        <label for="chkGender">Gender:</label><br>
                        <?php echo $this->gender($gender); ?>
                    </p>
                    <?php
                    $lang['months'] = array("January","February","March","April","May","June","July","August","September","October","November","December");
                    if ($this->user['birthday'] !== "0000-00-00") {
                        $bdate = $this->user['birthday'];
                        $year = date("Y", strtotime($bdate));
                        $month = date("n", strtotime($bdate));
                        $day = date("j", strtotime($bdate));
                    ?>
                    <p>
                        <label for="birthOfDate">Birth Of Date:</label><br>
                        <?php echo $this->month($lang['months'],$month).$this->day($day).$this->year($year); ?>
                    </p>
                    <?php } else { ?>
                    <p>
                        <label for="birthOfDate">Birth Of Date:</label><br>
                        <?php echo $this->month($lang['months']).$this->day().$this->year(); ?>
                    </p>
                    <?php } ?>
                    <p>
                        <label for="education">Education:</label><br>
                        <?php echo $this->education($this->user['educationId']); ?>
                    </p>
                    <p>
                        <label for="expense">Monthly expenses:</label><br>
                        <?php echo $this->expense($this->user['expenseId']); ?>
                    </p>
                    <p>
                        <label for="businessType">Business Type:</label><br>
                        <?php echo $this->businessType($this->user['businessTypeId']); ?>
                    </p>
                    <p>
                        <label for="address">Address:</label><br>
                        <textarea name="address" class="medium" cols="30" rows="5"><?php echo $this->user['address']; ?></textarea>
                    </p>
                    <p>
                        <label for="city">City:</label><br>
                        <input id="city" class="half" name="city" type="text" value="<?php echo $this->user['city']; ?>" />
                    </p>
                    <?php
                    $state = ($this->user['state'])? $this->user['state'] : 7;
                    ?>
                    <p>
                        <label for="province">State:</label><br>
                        <?php echo $this->state($state); ?>
                    </p>
                    <?php
                    $countryId = ($this->user['countryId'])? $this->user['countryId'] : "ID";
                    ?>
                    <p>
                        <label for="country">Country:</label><br>
                        <?php echo $this->country("countryId",$countryId); ?>
                    </p>
                    <p>
                        <label for="zip">PostalCode:</label><br>
                        <input id="zip" class="small" name="zip" type="text" value="<?php echo $this->user['zip']; ?>" />
                    </p>
                    <p>
                        <label for="phone">Phone:</label><br>
                        <input id="phone" class="small" name="phone" type="text" value="<?php echo $this->user['phone']; ?>" />
                    </p>
                    <p>
                        <label for="fax">Fax:</label><br>
                        <input id="fax" class="small" name="fax" type="text" value="<?php echo $this->user['fax']; ?>" />
                    </p>
                    <p>
                        <label for="payment">Subscription:</label><br>
                        <input id="payment" class="small" name="payment" type="text" size="2" value="<?php echo ($this->user['paymentId']==0)? "" : $this->user['paymentId']; ?>" />&nbsp;month
                        <small>.:Corporate or Individual Subscriber</small>
                    </p>
			        <p>
			            <label for="trial">Trial dalam Hari:</label><br>
			            <input id="trial" class="small" name="trial" type="text" size="2" value="<?php echo $this->user['trialInDays']; ?>" />&nbsp;days
			        </p>
                </fieldset>
                <fieldset>
                    <legend>Enter Your E-mail Address</legend>
                    <p>
                        <label class="required" for="email">E-mail:</label><br>
                        <input id="email" class="half" name="email" type="text" value="<?php echo $this->user['email']; ?>" />
                    </p>
                </fieldset>
                <p>
                    <label for="notes">Notes:</label><br>
                    <textarea name="notes" class="medium" cols="30" rows="5"><?php echo $this->user['notes']; ?></textarea>
                </p>
                <p>
                    <label for="userstatus">User Status</label>
                    <?php echo $this->uStatus($this->user['periodeId']); ?>
                </p>
                <p>
                    <label for="isActive">Is Active</label>
                    <?php
                    $arraystatus = array(
                                    0 => "No",
                                    1 => "Yes"
                            );
                    ?>
                    <select name="isactive">
                    <?php
                    foreach ($arraystatus as $key => $val)
                    {
                        $sel = ($key == $this->user['isActive']) ? " selected" : "";
                        echo '<option value='.$key . $sel.'>'.$val.'</option>';
                    }
                    ?>
                    </select>
                </p>
                <?php
                if ($this->user['isContact'] == "Y") {
                    $isContact = 'checked';
                } else {
                    $isContact = '';
                }
                ?>
                <p>
                    <input name="iscontact" id="iscontact" type="checkbox" value="1" <?php echo $isContact; ?>>&nbsp;Contact Person<br/><br/>
                </p>
                <fieldset>
                <?php
                    if ($this->user['newArticle'] == 'Y') {
                        $newArticlechecked = 'checked';
                    } else {
                        $newArticlechecked = '';
                    }
                    if ($this->user['monthlyList'] == 'Y') {
                        $monthlyListchecked = 'checked';
                    } else {
                        $monthlyListchecked = '';
                    }
                    if ($this->user['weeklyList'] == 'Y') {
                        $weeklyListchecked = 'checked';
                    } else {
                        $weeklyListchecked = '';
                    }
                ?>
                <legend>Newsletter</legend>
                <input type="checkbox" name="newArticle" value="1" <?php echo $newArticlechecked; ?>>&nbsp;News article<br>
                <input type="checkbox" name="newWeeklyRegulation" value="1" id="newWeeklyRegulation" <?php echo $weeklyListchecked; ?>>&nbsp;Weekly regulations<br>
                <input type="checkbox" name="newRegulation" value="1" <?php echo $monthlyListchecked; ?>>&nbsp;Monthly regulations
                </fieldset>
                <input type="hidden" name="modifiedBy" value="<?php echo $this->identity->username; ?>" />

                <p>
                    <input class="form-button" value="Process" type="submit" />
                    <input class="form-button" value="Back" type="button" onclick="window.location.href='<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/list'" />
                </p>
                <div class="clear">&nbsp;</div>
            </form>
        </div>
    </div>

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php //echo $this->action('approval','user','customer'); ?>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('rightupmenu','user','customer',array('id'=>$this->user['kopel'])); ?>
    </div>
    <div class="content-box">
        <?php echo $this->action('rightdownmenu','user','customer',array('id'=>$this->user['kopel'])); ?>
    </div>
</aside>
<!-- End of Right column/section -->