<?php 

$this->headLink()
	->appendStylesheet($this->cdn('scripts') . '/hol/datepicker/rfnet.css');

?>

<script type="text/javascript" src="<?php echo $this->cdn('scripts'); ?>/hol/datepicker/datetimepicker.js"></script>

<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <h3>User Management: Invoice</h3>
            <div class="align-right">
            	<!--
                <a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/invoice/new/id/<?=$this->user['kopel'];?>" class="btn"><span class="icon icon-add">&nbsp;</span>Add New</a>
                -->
				<a href="#invoice" class="nyroModal btn" title="Create New Invoice"><span class="icon icon-add">&nbsp;</span>Add New</a>            	
            </div>
            <div id='invoice' style='display: none;'>
            <?php if (in_array($this->user['packageId'],array(14,15,16,17,18))) { ?>
            <form action="" method="POST" name="newinvoice">
            	<fieldset>
            		<legend>CREATE NEW INVOICE</legend>
            		<?php 
            		/**
            		 * @modifiedDate: December 07, 2012
            		 */
            		$formater = new Pandamp_Core_Hol_User(); 
            		//$disc = $formater->checkPromoValidation('Disc',$this->user['packageId'],$this->user['promotionId'],$this->user['paymentId']);
            		$disc = 0;
            		//$total = $formater->checkPromoValidation('Total',$this->user['packageId'],$this->user['promotionId'],$this->user['paymentId']);
            		$total = $formater->checkPromoValidation($this->user['packageId'],$this->user['paymentId']);
            		?>
            		<table class='display stylized'>
            		<tr>
            			<td><label>Kode Pelanggan:</label></td>
            			<td><input type="text" value="<?php echo $this->user['kopel']; ?>" name="kopel" size="6" maxlength="6" readonly=""/></td>
            		</tr>
            		<tr>
            			<td><label>Price:</label></td>
            			<td><input type="text" value="<?php echo $total; ?>" name="price"/></td>
            		</tr>
            		<tr>
            			<td><label>Discount:</label></td>
            			<td><input type="text" value="<?php echo $disc; ?>" name="disc"/></td>
            		</tr>
            		<tr>
            			<td><label>Invoice Out Date:</label></td>
            			<td nowrap>
            				<input type="text" value="<?php echo date("Y-m-d"); ?>" name="invoiceOutDate" id="invoiceOutDate"/>
            				<a href="javascript:NewCal('invoiceOutDate','yyyymmdd',false)"><img src="<?php echo $this->cdn('images'); ?>/img.gif" width="16" height="16" border="0" alt="Pick a date"></a>
            			</td>
            		</tr>
            		<tr>
            			<td nowrap><label>Invoice Confirm Date:</label></td>
            			<td nowrap>
            				<input type="text" value="0000-00-00" name="invoiceConfirmDate" id="invoiceConfirmDate"/>
            				<a href="javascript:NewCal('invoiceConfirmDate','yyyymmdd',false)"><img src="<?php echo $this->cdn('images'); ?>/img.gif" width="16" height="16" border="0" alt="Pick a date"></a>
            			</td>
            		</tr>
            		<tr>
            			<td nowrap><label>Client Bank Account:</label></td>
            			<td>
            				<select name="clientBankAccount">
            					<option value="BCA">BCA</option>
            					<option value="BNI">BNI</option>
            				</select>
            			</td>
            		</tr>
            		<tr>
            			<td><label>Is Paid:</label></td>
            			<td>
            				<select name="isPaid">
            					<option value="N">No</option>
            					<option value="Y">Yes</option>
            				</select>
            			</td>
            		</tr>
            		<?php
        			$temptime = time();
					$temptime = Pandamp_Lib_Formater::DateAdd('d',5,$temptime);
					?>
            		<tr>
            			<td><label>Expiration Date:</label></td>
            			<td nowrap>
            				<input type="text" value="<?php echo strftime('%Y-%m-%d',$temptime); ?>" name="expirationDate" id="expirationDate"/>
            				<a href="javascript:NewCal('expirationDate','yyyymmdd',false)"><img src="<?php echo $this->cdn('images'); ?>/img.gif" width="16" height="16" border="0" alt="Pick a date"></a>
            			</td>
            		</tr>
            		<tr>
            			<td colspan="2"><input type="submit" value="Save" class="btn btn-blue big" /></td>
            		</tr>
            		</table>
            		
            	</fieldset>
            </form>
            <?php } else { ?>
            Oops ...
            <?php } ?>
            </div>
            <div style="clear:both;"></div>
            <div class="box box-success" id="message"></div>
            <table class="display stylized" id="userinvoicelist">
                <thead>
                    <tr>
                        <th>Invoice</th>
                        <th>Paid</th>
                        <th>Price</th>
                        <th>Disc</th>
                        <th>Date Out</th>
                        <th>Paid Date</th>
                        <th>Expr. Date</th>
                        <th class="ta-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?
                    $i=1; foreach($this->userInvoiceList as $row):
                    ?>
                    <tr class="<?=($i%2 ? 'gradeX' : 'gradeC');?>" id="row_<?=$row['invoiceId'];?>">
                        <td><?=$row['invoiceId'];?></td>
                        <td><?=$row['isPaid'];?></td>
                        <td><?=$row['price'];?></td>
                        <td><?=$row['discount'];?></td>
                        <td><?=date('d.m.y',strtotime($row['invoiceOutDate']));?></td>
                        <td>
                        <?
                        if ($row['invoiceConfirmDate'] == "0000-00-00") 
                        	$icd = "-";
                        else
                        	$icd = date('d.m.y',strtotime($row['invoiceConfirmDate']));
                        	
                        echo $icd;
                        ?>
                        </td>
                        <td><?=date('d.m.y',strtotime($row['expirationDate']));?></td>
                        <td>
                            <? 
                                if ($this->isAllowed('membership','all'))
                                {
                            ?>
                                    <input type="button" name="confirm" value="Confirm" id="<?=$row['invoiceId'];?>" class="form-button" />&nbsp;
                                    <input type="button" name="delete_invoice" value="Del" id="<?=$row['invoiceId'];?>" class="form-button" />&nbsp;
                                    <input type="button" name="renew" value="Renewable" id="<?=$row['invoiceId'];?>" class="form-button" />

                                <? } else { ?>

                                    <input type="button" name="confirm" value="Edit" disabled class="form-button" />&nbsp;
                                    <input type="button" name="delete_invoice" value="Del" disabled class="form-button" />&nbsp;
                                    <input type="button" name="renew" value="Reset" disabled class="form-button" />

                                <? } ?>

                        </td>
                    </tr>
                    <? $i++; endforeach;?>
                </tbody>
                <tfoot>
                    <tr>
                    	<td colspan="11">
                    	&raquo;&nbsp;<a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/list" title="Users List"">Back</a>
                    	</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <div class="colgroup leading">
        <div class="column width6 first">
            <?//=$this->action('approval','user','customer');?>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?=$this->action('rightupmenu','user','customer',array('id'=>$this->user['kopel']));?>
    </div>
    <div class="content-box">
        <?=$this->action('rightdownmenu','user','customer',array('id'=>$this->user['kopel']));?>
    </div>
</aside>
<!-- End of Right column/section -->
