<header>
    <h3>User Account</h3>
</header>
<dl class="first">
    <dt><img alt="" src="<?php echo $this->cdn('images'); ?>/key.png" height="16" width="16"></dt>
    <dd><a href="#"><?php echo $this->user['username']; ?> (<?php echo $this->userGroup($this->user['packageId']); ?>)</a></dd>
    <dd class="last">
        <ol>
            <li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/changepassword/id/<?php echo $this->user['kopel']; ?>">Change Password</a></li>
            <li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/uploadphoto/id/<?php echo $this->user['kopel']; ?>">Upload Photo</a></li>
        </ol>
    </dd>

    <dt><img alt="" src="<?php echo $this->cdn('images'); ?>/user_go.png" height="16" width="16"></dt>
    <dd>Last Login</dd>
    <dd class="last"><?php echo $this->lastLogin($this->user['kopel']); ?></dd>

    <dt><img alt="" src="<?php echo $this->cdn('images'); ?>/help.png" height="16" width="16"></dt>
    <dd><a href="#">Support</a></dd>
    <dd class="last">Documentation and FAQ</dd>
</dl>
