<header style="cursor: s-resize;">
    <h3>Others</h3>
</header>
<section>
<dl>
    <dt>Hmm..where's the log?</dt>
    <dd><a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/log/id/<?=$this->user['kopel'];?>"><abbr>Access Log</abbr></a></dd>
    <dt>Change group: Upgrade or Downgrade</dt>
    <dd><a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/associate/id/<?=$this->user['kopel'];?>"><abbr>ASSOCIATE</abbr></a></dd>
    <dt>User Invoice, Renew or Create One</dt>
    <dd><a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/invoicelist/id/<?=$this->user['kopel'];?>"><abbr>Invoice</abbr></a></dd>
</dl>
</section>
