<header style="cursor: s-resize;">
    <h3>Others</h3>
</header>
<section>
<dl>
    <dt>Hmm..where's the log?</dt>
    <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/log/id/<?php echo $this->user['kopel']; ?>"><abbr>Access Log</abbr></a></dd>
    <dt>Change group: Upgrade or Downgrade</dt>
    <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/associate/id/<?php echo $this->user['kopel']; ?>"><abbr>ASSOCIATE</abbr></a></dd>
    <dt>User Invoice, Renew or Create One</dt>
    <dd><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/invoicelist/id/<?php echo $this->user['kopel']; ?>"><abbr>Invoice</abbr></a></dd>
</dl>
</section>
