<!-- Left column/section -->
<section class="column width6 first">
	<div class="colgroup leading">
		<div class="column width6 first">
			<h3>Who's Online</h3>
			Number of record(s): <span id="numOfRecords"><?php echo $this->aData['totalCount'];?></span>
            <div class="clear">&nbsp;</div>
            <div class="box box-success" id="message"></div>
			
			<div class="align-right">
				<div class="psearch">
				<input id="keywords" name="keywords" type="text">
				</div>
			</div>
			
			<div id='wholContent'></div>
			
			<table width='100%'>
				<tr>
					<td width=35%>&nbsp;</td>
					<td align=right><div id='wholPagination' class="pagination"></div></td>
				</tr>
			</table>
			
			<script>
			$(document).ready(function(){
				var isFirstTime = 1;
				
				var myPageIndex = 0;
				var currentEncodedQuery ='';
				var itemsPerPage = <?php echo $this->aData['limit'];?>
				
				$("#wholPagination").pagination(<?php echo $this->aData['totalCount'];?>, 
				{items_per_page:itemsPerPage, callback:handlePaginationClick}
				);
				
				function handlePaginationClick(new_page_index, pagination_container) 
				{
					
					myPageIndex = new_page_index;
					myStart = (<?php echo $this->aData['limit'];?> * myPageIndex);
					
					if(true)
					{
						if($('#tblWholPager-'+myPageIndex).length==0)
						{
							//$('#message_box').show();
							$.getJSON('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/getwholuser/q/'+currentEncodedQuery+'/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', wholJson);
						}
						else
							showWholContent();
					}
					return false;
				}
				function wholJson(res)
				{
					size = res.users.length;
					var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<div class="tblWholPager" id="tblWholPager-'+myPageIndex+'">';
					tblRow += "<table class='display stylized'><thead><tr><th>Kopel</th><th>Username</th><th>Company</th><th>Group</th><th class='ta-center'>Action</th></tr></thead><tbody>"
					+"<?$gEx = $this->groupException(11);?>";
					
					
					for(i=0;i<size;i++)
					{
						tblRow += 
							"<tr id='row_"+res.users[i].kopel+"'>"
							+"<td>"+res.users[i].kopel+"</td>"
							+"<td>"+res.users[i].username+"</td>"
							+"<td width='25%'>"+res.users[i].company+"</td>"
							+"<td>"+res.users[i].group+"</td>"
							+"<td align='center'>"+res.users[i].action+"</td>"
							+"</tr>"
							
							
					}
					tblRow += "</tbody></table></div>";
					$(tblRow).appendTo("#wholContent");
					showWholContent();
					//$('#message_box').fadeOut();
					
					
				}
				function showWholContent()
				{
					$('.tblWholPager').hide();
					$('#tblWholPager-'+myPageIndex).show();
					if(!isFirstTime)
						//window.location.hash = '#a-'+myPageIndex;
						Scroller.scroll();
					isFirstTime = 0;
				}
				
				$("#keywords").change(function(){ 
					wholCount();
				});
				
				function wholCount()
				{
					var textKeywords = $("input#keywords").val();
					var searchQuery = textKeywords;
					var base64encoded = Base64.encode(searchQuery);
					currentEncodedQuery = base64encoded;
					$.getJSON('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/countuserwholbyquery/q/'+base64encoded+'/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', callbackWholCount);
				}
				function callbackWholCount(res)
				{
					$("#numOfRecords").html(res);
					$("#wholPagination").pagination(res, 
					{items_per_page:itemsPerPage, callback:handlePaginationClick}
					);
					wholInitiateFirstPagingClick();
				}
				function wholInitiateFirstPagingClick()
				{
					$("#wholContent").html("");
					myPageIndex = 0;
					myStart = (<?php echo $this->aData['limit'];?> * myPageIndex);
					
					if(true)
					{
						if($('#tblWholPager-'+myPageIndex).length==0)
						{
							//$('#message_box').show();
							$.getJSON('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/getwholuser/q/'+currentEncodedQuery+'/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', wholJson);
						}
						else
							showWholContent();
					}
				}
				
			});
			</script>
		</div>
	</div>
</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>

</aside>
<!-- End of Right column/section -->
<div class="clear">&nbsp;</div>