<!-- Left column/section -->
<section class="column width6 first">
	<div class="colgroup leading">
		<div class="column width6 first">
			<h3>Who's Online</h3>
			Number of record(s): <span id="numOfRecords"><?php echo $this->aData['totalCount'];?></span>
            <div class="clear">&nbsp;</div>
            <div class="box box-success" id="message"></div>
			
			<div class="align-left">
				&nbsp;&nbsp;&nbsp;&nbsp;<input name='select_deselect' id='select_deselect' type='checkbox'>&nbsp;<abbr>Select All</abbr> |
				<a href="javascript: void(0);" class="kickallAction">Kick User</a> 
			</div>
			<div class="align-right">
				<div class="psearch">
				<input id="keywords" name="keywords" type="text">
				</div>
			</div>
			
			<div id='wholContent'></div>
			
			<table width='100%'>
				<tr>
					<td width=35%>&nbsp;</td>
					<td align=right><div id='wholPagination' class="pagination"></div></td>
				</tr>
			</table>
			
			<div id="confirmDialog"></div>
			
			<script>
			$(document).ready(function(){
				var isFirstTime = 1;
				
				var myPageIndex = 0;
				var currentEncodedQuery ='';
				var itemsPerPage = <?php echo $this->aData['limit'];?>
				
				$("#wholPagination").pagination(<?php echo $this->aData['totalCount'];?>, 
				{items_per_page:itemsPerPage, callback:handlePaginationClick}
				);
				
				function handlePaginationClick(new_page_index, pagination_container) 
				{
					
					myPageIndex = new_page_index;
					myStart = (<?php echo $this->aData['limit'];?> * myPageIndex);
					
					if(true)
					{
						if($('#tblWholPager-'+myPageIndex).length==0)
						{
							//$('#message_box').show();
							$.getJSON('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/getwholuser/q/'+currentEncodedQuery+'/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', wholJson);
						}
						else
							showWholContent();
					}
					return false;
				}
				function wholJson(res)
				{
					size = res.users.length;
					var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<div class="tblWholPager" id="tblWholPager-'+myPageIndex+'">';
					tblRow += "<table class='display stylized'><thead><tr><th>&nbsp;</th><th>Kopel</th><th>Username</th><th>Company</th><th>Group</th><th class='ta-center'>Action</th></tr></thead><tbody>"
					+"<?$gEx = $this->groupException(11);?>";
					
					
					for(i=0;i<size;i++)
					{
						tblRow += 
							"<tr id='row_"+res.users[i].kopel+"'>"
							+"<td width='2%'>"+res.users[i].checkbox+"</td>"
							+"<td>"+res.users[i].kopel+"</td>"
							+"<td>"+res.users[i].username+"</td>"
							+"<td width='25%'>"+res.users[i].company+"</td>"
							+"<td>"+res.users[i].group+"</td>"
							+"<td align='center'>"+res.users[i].action+"</td>"
							+"</tr>"
							
							
					}
					tblRow += "</tbody></table></div>";
					$(tblRow).appendTo("#wholContent");
					showWholContent();
					//$('#message_box').fadeOut();
					
					
				}
				function showWholContent()
				{
					$('.tblWholPager').hide();
					$('#tblWholPager-'+myPageIndex).show();
					if(!isFirstTime)
						//window.location.hash = '#a-'+myPageIndex;
						Scroller.scroll();
					isFirstTime = 0;
				}
				
				$("#keywords").change(function(){ 
					wholCount();
				});
				
				function wholCount()
				{
					var textKeywords = $("input#keywords").val();
					var searchQuery = textKeywords;
					var base64encoded = Base64.encode(searchQuery);
					currentEncodedQuery = base64encoded;
					$.getJSON('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/countuserwholbyquery/q/'+base64encoded+'/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', callbackWholCount);
				}
				function callbackWholCount(res)
				{
					$("#numOfRecords").html(res);
					$("#wholPagination").pagination(res, 
					{items_per_page:itemsPerPage, callback:handlePaginationClick}
					);
					wholInitiateFirstPagingClick();
				}
				function wholInitiateFirstPagingClick()
				{
					$("#wholContent").html("");
					myPageIndex = 0;
					myStart = (<?php echo $this->aData['limit'];?> * myPageIndex);
					
					if(true)
					{
						if($('#tblWholPager-'+myPageIndex).length==0)
						{
							//$('#message_box').show();
							$.getJSON('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/getwholuser/q/'+currentEncodedQuery+'/start/'+myStart+'/limit/<?php echo $this->aData['limit'];?>', '', wholJson);
						}
						else
							showWholContent();
					}
				}
				
				/**
				 * Select/Deselect all rows handler
				 */
				$('#select_deselect').click(function() {
					$('input[type="checkbox"].check_me').attr('checked', $(this).attr('checked'));
				});	
				
				$('a.kickallAction').click(function(){
					var numSelected = $('input[type="checkbox"].check_me:checked').length;
					var self = this;
					if (0 == numSelected) {
						$('#confirmDialog').html('<?php echo addslashes("Please select at least one user"); ?>')
							.dialog({
								title: '<?php echo addslashes("Error"); ?>',
								dialogClass: 't_a_ui_dialog',
								modal: true,
								closeOnEscape: false,
								resizable: false,
								open: function(event, ui) {
									$('.ui-dialog-titlebar-close').hide();
									$(this).parent().find('.ui-dialog-buttonpane button').wrapInner('<span/>');
								},
								buttons: {
									'<?php echo addslashes("OK"); ?>': function() {
										$(this).dialog('destroy');
									}
								}
							});
						
					}
					else
					{
						var ids = new Array();
						$('input[type="checkbox"].check_me:checked').each(function() {
							ids.push($(this).val());
						});
						
						$.ajaxq('customer', {
							url: "<?php echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'user','module'=>'customer','action'=>'kickall'),'customer'); ?>",
							type: 'POST',
							data: { id: $.toJSON(ids) },
							success: function(response) {
								if ('RESULT_OK' == response) {
									window.location.reload();
								}
							}
						});
						
					}
				});
				
			});
			</script>
		</div>
	</div>
</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>

</aside>
<!-- End of Right column/section -->
<div class="clear">&nbsp;</div>