<div class="width7">
    <div class="wrapper">

        <form id="frmSearch" name="frmSearch" method="post">
            <fieldset>
                <legend>PAYMENT CONFIRMATION</legend>
            <p>
                <label>Status : </label><input id="sStatus" name="sStatus" size=10 value="<?php echo $this->sStatus; ?>">
                <label>Username : </label><input id="sUsername" name="sUsername" size=10 value="<?php echo $this->sUsername; ?>">
                <label>Date min : </label><input type="date" id="fdate" name="fdate" value="<?php echo $this->fdate; ?>"/>
                <label>Date max : </label><input type="date" id="ldate" name="ldate" value="<?php echo $this->ldate; ?>"/>
                <input type="hidden" id="limit" name="limit" value="10">
                <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset; ?>">
                <input class="btn btn-green big" value="Search" type="submit">
            </p>
            </fieldset>
        </form>

        <table class="display stylized" id="confirm">
            <thead>
                <tr>
                    <th>No</th>
                    <th>User</th>
                    <th>Order</th>
                    <th>Sender Detail</th>
                    <th>Destination</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $i=$this->offset+1; foreach($this->rowset as $row) { ?>
                <tr class="<?php echo ($i%2 ? 'gradeX' : 'gradeC'); ?>">
                    <td><?php echo $i; ?></td>
                    <td>
                        <?php echo $row['username']; ?><br/>
                        <?php echo $row['fullName']; ?>&nbsp;<br/>
                    </td>
                    <td>
                        Invoice : <?php echo $row['invoiceNumber']; ?><br/>
                        Total Order : <?php echo $row['orderTotal']; ?> IDR<br/>
                        method : <?php echo $row['paymentMethod']; ?><br/>
                    </td>
                    <td>
                        Acc. : <?php echo $row['senderAccount']; ?><br/>
                        Name : <?php echo $row['senderAccountName']; ?><br/>
                        Bank : <?php echo $row['bankName']; ?><br/>
                        Note : <?php echo $row['note']; ?><br/>
                    </td>
                    <td>
                        Acc. : <?php echo $row['destinationAccount']; ?><br/>
                        Transfer Amount : <?php echo $row['amount']; ?><br/>
                        Payment Date : <?php echo Pandamp_Lib_Formater::get_date($row['paymentDate']); ?><br/>
                    </td>
                    <td><a href="<?php echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'store', 'action'=>'payconfirm', 'orderId'=>$row['orderId']),'segwact'); ?>">confirm</a></td>
                </tr>
                <?php $i++; } ?>
            </tbody>
        </table>


        <div class="clear">&nbsp;</div>

    </div>
</div>