<fieldset>
<legend>EDITING DATA with ID NUMBER : <?=$this->id;?></legend>
<form method="POST">
<?  foreach($this->rows as $row): ?>
<p>
	<label for="key">Key: <?=$row->settingKey;?></label><br>
	<label for="value">Value:</label><br>
	<input type="text" name="value" value="<?=$row->settingValue;?>" size="70" /><br>
	<label for="notes">Notes:</label><br>
	<textarea id="note" cols="20" rows="5" name="note"><?=$row->note;?></textarea>
</p>
<? endforeach; ?><br>
<p style="z-index:1;overflow:hidden;">
<input type="hidden" name="id" value="<?=$this->id;?>" />
<input type="button" value= "back" class="btn" onclick="document.location.href='<?=ROOT_URL?>/<?=$this->getLanguage();?>/store/paymentsetting'" />
<input type="reset" value="reset" class="btn" />
<input type="submit" name="save" value="save" class="btn" />
</p>
</form>
</fieldset>