<fieldset>
    <legend>Editing data number <?php echo $this->id; ?></legend>
    <form method="post">
        <div class="colgroup">
            <?php foreach($this->rows as $row) { ?>
            <div class="column width2 first"><b>Invoice</b></div>
            <div class="column width2"><input type="text" name="invoiceNumber" value="<?php echo $row['invoiceNumber']; ?>" /></div>
            <div class="column width2"><b>Kode Pelanggan</b></div>
            <div class="column width2"><input type="text" name="userId" value="<?php echo $row['userId']; ?>"  /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Tax Number</b></div>
            <div class="column width2"><input type="text" name="taxNumber" value="<?php echo $row['taxNumber']; ?>" /></div>
            <div class="column width2"><b>Company</b></div>
            <div class="column width2"><input type="text" name="taxCompany" value="<?php echo $row['taxCompany']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Address</b></div>
            <div class="column width2"><input type="text" name="taxAddress" value="<?php echo $row['taxAddress']; ?>" /></div>
            <div class="column width2"><b>City</b></div>
            <div class="column width2"><input type="text" name="taxCity" value="<?php echo $row['taxCity']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>ZIP</b></div>
            <div class="column width2"><input type="text" name="taxZip" value="<?php echo $row['taxZip']; ?>" /></div>
            <div class="column width2"><b>Province</b></div>
            <div class="column width2"><input type="text" name="taxProvince" value="<?php echo $row['taxProvince']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Country</b></div>
            <div class="column width2"><input type="text" name="taxCountryId" value="<?php echo $row['taxCountryId']; ?>" /></div>
            <div class="column width2"><b>Telephone</b></div>
            <div class="column width2"><input type="text" name="telephone" value="<?php echo $row['telephone']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Payment Method</b></div>
            <div class="column width2"><input type="text" name="paymentMethod" value="<?php echo $row['paymentMethod']; ?>" /></div>
            <div class="column width2"><b>Payment Method Note</b></div>
            <div class="column width2"><input type="text" name="paymentMethodNote" value="<?php echo $row['paymentMethodNote']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Last Modified</b></div>
            <div class="column width2"><input type="date" name="lastModified" id="lastModified" value="<?php echo $row['lastModified']; ?>" /></div>
            <div class="column width2"><b>Date Purchased</b></div>
            <div class="column width2"><input type="text" name="datePurchased" id="datePurchased" value="<?php echo $row['datePurchased']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Order Status</b></div>
            <div class="column width2">
		<input type="hidden" name="orderaStatus" value="<?php echo $row['orderStatus']; ?>"  />

		<select name="orderStatus">
		<?php foreach($this->rowsStatus as $status) { ?>
		<option value="<?php echo $status['orderStatusId']; ?>" <?php echo ($status['orderStatusId']==$row['orderStatus']?'selected=selected':'') ; ?>><?php echo $status['ordersStatus']; ?>
		<?php } ?>
		</select>

            </div>
            <div class="column width2"><b>Date Order Finished</b></div>
            <div class="column width2"><input type="date" id="dof" name="dateOrderFinished" value="<?php echo $row['dateOrderFinished']; ?>"  /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Currency</b></div>
            <div class="column width2"><input type="text" name="currency" value="<?php echo $row['currency']; ?>" /></div>
            <div class="column width2"><b>Currency Value</b></div>
            <div class="column width2"><input type="text" name="currencyValue" value="<?php echo $row['currencyValue']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Order Total</b></div>
            <div class="column width2"><input type="text" name="orderTotal" value="<?php echo $row['orderTotal']; ?>" /></div>
            <div class="column width2"><b>Order Tax</b></div>
            <div class="column width2"><input type="text" name="orderTax" value="<?php echo $row['orderTax']; ?>" /></div>

            <div class="clear">&nbsp;</div>

            <div class="column width2 first"><b>Paypal IPN ID</b></div>
            <div class="column width2"><input type="text" name="paypalIpnId" value="<?php echo $row['paypalIpnId']; ?>" /></div>
            <div class="column width2"><b>IP Address</b></div>
            <div class="column width2"><input type="text" name="ipAddress" value="<?php echo $row['ipAddress']; ?>" /></div>

        </div>

        <input type="hidden" name="orderId" value="<?php echo $this->id; ?>">
        <input type="hidden" name="offset" value="<?php echo $this->offset; ?>" />

        <?php } ?>

        <div class="clear">&nbsp;</div>
        
        <input type="button" class="btn btn-green big" value= "back" onclick="javascript:history.back();" />
        <input type="reset" class="btn btn-green big" value="reset" />
        <input type="submit" class="btn btn-green big" name="save" value="save" />
        
        <div class="clear">&nbsp;</div>
    </form>
</fieldset>