<!-- Header -->
<header id="top">
    <div class="wrapper">
        <!-- Title/Logo - can use text instead of image -->
        <div id="title"><img src="<?php echo $this->cdn('images'); ?>/logo.png" alt="hukumonline" /><!--<span>CMS Hukumonline</span>--></div>
        <!-- Top navigation -->
        <?php echo $this->action('topnav','index','admin'); ?>
        <!-- End of Top navigation -->
        <!-- Main navigation -->
        <nav id="menu">
            <ul class="sf-menu sf-js-enabled sf-shadow">
                <li><a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>">Dashboard</a></li>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/dms">Dms</a></li>
                <?php if ($this->isAllowed('store','read')) { ?>
                <li class="current"><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/store">Store</a></li>
                <?php } ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/customer/user/list">User</a></li>
                <?php if ($this->isAllowed('membership','all')) { ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/acl">Access Control</a></li>
                <?php } ?>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/search">Search</a></li>
                <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/setting">Setting</a></li>
            </ul>
        </nav>
        <!-- End of Main navigation -->
        <!-- Aside links -->
        <aside>
            <?php if ($this->getLanguage() == "id") { ?>
            <a href="<?php echo ROOT_URL; ?>/en">English</a> &middot; <b>Indonesia</b>
            <?php } else { ?>
            <b>English</b> &middot; <a href="<?php echo ROOT_URL; ?>/id">Indonesia</a>
            <?php } ?>
        </aside>
        <!-- End of Aside links -->
    </div>
</header>
<!-- End of Header -->
<!-- Page title -->
<div id="pagetitle">
    <div class="wrapper">
        <h1>Dashboard</h1>
        <!-- Quick search box -->
        <form action="" method="get"><input class="" id="q" name="q" type="text"></form>
    </div>
</div>
<!-- End of Page title -->