<div class="width7">
    <?
    $statusId = $this->statusId;
    $status = $this->status;
    $rowset = $this->rowset;

    for ($i=0;$i<count($status);$i++)
    {
    ?>
        <div class="dataTables_length">
            <b>Status : <?=$status[$i];?>, Total : <?=$this->total[$i];?></b>
        </div>
        <div class="dataTables_filter">
            <a href="<?=$this->url(array('lang'=>$this->getLanguage(), 'controller'=>'store', 'action'=>'order', 'status'=>$this->statusId[$i]),'segwact');?>">View All <?=$status[$i];?> Orders</a>
        </div>
        <div class="clear">&nbsp;</div>
        <table id="report" class="display stylized">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Description</th>
                    <th>Payment Method</th>
                    <th>Order Total</th>
                    <th>Total Count</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <? for($x=0;$x<count($rowset[$i]);$x++){ ?>
                <tr class="<?=($x%2 ? 'gradeX even' : 'gradeX odd');?>">
                    <td><?=$x+1?></td>
                    <td><?=$rowset[$i][$x]->invoiceNumber;?></td>
                    <td><?=$rowset[$i][$x]->paymentMethod;?></td>
                    <td class="center"><?=$rowset[$i][$x]->orderTotal;?></td>
                    <td class="center"><?=$rowset[$i][$x]->countTotal;?></td>
                    <td class="center">
                        <a href="<? echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'store', 'action'=>'editOrder', 'orderId'=>$rowset[$i][$x]->orderId),'segwact');?>">Edit</a>
                        <a href="<? echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'store', 'action'=>'detailOrder', 'orderId'=>$rowset[$i][$x]->orderId),'segwact');?>">Detail</a>
                    </td>
                </tr>
                <?}?>
            </tbody>
        </table>
        <div class="clear">&nbsp;</div>
    <?
    }
    ?>
</div>
