<div class="width7">
    <div class="wrapper">
        <table class="display stylized" id="nsiapaypayment">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Description</th>
                    <th>Payment Method</th>
                    <th>Purchasing Date</th>
                    <th>Modified Date</th>
                    <th>Order Status</th>
                    <th>Total Price</th>
                    <th>Qty</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $i=$this->offset+1; foreach($this->rows as $row) { ?>
                <tr class="<?php echo ($i%2 ? 'gradeX' : 'gradeC'); ?>">
                    <td><?php echo $i; ?></td>
                    <td>
                        User ID : <?php echo $row->userId; ?><br />
                        Invoice : <?php echo $row->invoiceNumber; ?><br />
                        Name    : <?php echo $row->fullName; ?><br />
                        Company : <?php echo $row->company; ?><br />&nbsp;
                    </td>
                    <td><?php echo $row->paymentMethod; ?></td>
                    <td class="center"><?php echo strftime("%Y-%m-%d",strtotime($row->datePurchased)); ?></td>
                    <td><?php echo (!empty($row->lastModified))?strftime("%Y-%m-%d",strtotime($row->lastModified)):'undefined'; ?></td>
                    <td><?php echo $row->ordersStatus; ?></td>
                    <td><?php echo $row->orderTotal; ?></td>
                    <td><?php echo $row->countTotal; ?></td>
                    <td class="center">
                       <a href="<?php echo $this->url(array('controller'=>'store', 'action'=>'editOrder', 'orderId'=>$row->orderId)); ?>">edit</a>
                       <a href="<?php echo $this->url(array('controller'=>'store', 'action'=>'trdetail', 'orderId'=>$row->orderId)); ?>">detail</a>
                    </td>
                </tr>
                <?php $i++; } ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Description</th>
                    <th>Payment Method</th>
                    <th>Purchasing Date</th>
                    <th>Modified Date</th>
                    <th>Order Status</th>
                    <th>Total Price</th>
                    <th>Qty</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>