<div class="width7">
    <div class="wrapper">

        <form id="frmSearch" name="frmSearch" method="post">
            <fieldset>
                <legend>Order Status</legend>
            <p>
                <label>Status : </label><input id="sStatus" name="sStatus" size=10 value="<?=$this->sStatus;?>">
                <label>Username : </label<input id="sUsername" name="sUsername" size=10 value="<?=$this->sUsername;?>">
                <label>Date min : </label><input type="date" id="fdate" name="fdate" value="<?=$this->fdate;?>"/>
                <label>Date max : </label><input type="date" id="ldate" name="ldate" value="<?=$this->ldate;?>"/>
                <input type="hidden" id="limit" name="limit" value="10">
                <input type="hidden" id="offset" name="offset" value="<?=$this->offset;?>">
                <input class="btn btn-green big" value="Search" type="submit">
            </p>
            </fieldset>
        </form>

        <div class="box box-success" id="message"></div>

        <table class="display stylized" id="orderstatus">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Order ID</th>
                    <th>Description</th>
                    <th>Payment Method</th>
                    <th>Purchasing Date</th>
                    <th>Order Status</th>
                    <th>Total Price</th>
                    <th>Qty</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <? $i=$this->offset+1; foreach($this->rows as $row):
                    if($row->orderStatus == 3 or $row->orderStatus == 5){
                        $anchor = 'trdetail';
                        }else{
                        $anchor = 'detailOrder';
                        }
                ?>
                <tr class="<?=($i%2 ? 'gradeX' : 'gradeC');?>" id="row_<?=$row->orderId;?>">
                    <td><?=$i?></td>
                    <td class="center"><?=$row->orderId;?></td>
                    <td>
                        User ID : <?=$row->userId;?><br />
                        Invoice : <?=$row->invoiceNumber;?><br />
                        Name    : <?=$row->fullName;?><br />
                        Company : <?=$row->company;?><br />&nbsp;
                    </td>
                    <td><?=$row->paymentMethod;?></td>
                    <td class="center"><?=strftime("%Y-%m-%d", strtotime($row->datePurchased));?></td>
                    <td><?=$row->ordersStatus;?></td>
                    <td><?=$row->orderTotal;?></td>
                    <td><?=$row->countTotal;?></td>
                    <td>
                        <?
                        if($row->orderStatus == 4){
                                echo "<a href=".$this->url(array('controller'=>'store',
                                        'action'=> 'payconfirm', 'orderId'=>$row->orderId)).">Action</a>";
                        }
                        ?>
                        <a href="<? echo $this->url(array('controller'=>'store',
                    'action'=>$anchor, 'orderId'=>$row->orderId));?>">detail</a>
                        <?
                        if($row->orderStatus !=5 && $row->orderStatus !=2 && $row->orderStatus !=3 ){
                                echo "<a href=".$this->url(array('controller'=>'store',
                                        'action'=> 'deleteOrder', 'id'=>$row->orderId)) . " class='delete'>Delete</a>";
                        }
                        ?>
                    </td>
                </tr>
                <? $i++; endforeach;?>
            </tbody>
            <tfoot>
                <tr>
                    <th>No</th>
                    <th>Order ID</th>
                    <th>Description</th>
                    <th>Payment Method</th>
                    <th>Purchasing Date</th>
                    <th>Order Status</th>
                    <th>Total Price</th>
                    <th>Qty</th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
        
        
        <div class="clear">&nbsp;</div>

    </div>
</div>