<form id="payconfirm" name="payconfirm">
<fieldset>
<legend>ORDER</legend>
<table class="no-style full">
<?php foreach($this->rowset as $row) { ?>
<tr>
	<td><abbr>No.Pesanan:</abbr></td>
	<td><?php echo $row['orderId']; ?></td>
</tr>
<tr>
	<td><abbr>No. Faktur:</abbr></td>
	<td><?php echo $row['invoiceNumber']; ?></td>
</tr>
<tr>
	<td><abbr>Kode Pelanggan:</abbr></td>
	<td><?php echo $row['userId']; ?></td>
</tr>
<tr>
	<td>NPWP:</td>
	<td><?php echo $row['taxNumber']; ?></td>
</tr>
<tr>
	<td>Nama Perusahaan:</td>
	<td><?php echo $row['taxCompany']; ?></td>
</tr>
<tr>
	<td>Alamat Penagihan:</td>
	<td><?php echo $row['taxAddress']; ?></td>
</tr>
<tr>
	<td>Kota:</td>
	<td><?php echo $row['taxCity']; ?></td>
</tr>
<tr>
	<td>Kodepos:</td>
	<td><?php echo $row['taxCity']; ?></td>
</tr>
<tr>
	<td>Propinsi:</td>
	<td>
	<?php
	$modelState = new App_Model_Db_Table_State();
	$rowState = $modelState->find($row['taxProvince'])->current();
	if ($rowState) {
		$state = $rowState->pname;
	}
	else 
	{
		$state = "-";
	}
	
	echo $state;
	?>
	</td>
</tr>
<tr>
	<td>Negara</td>
	<td>
	<?php
		$config = new Zend_Config_Xml(CONFIG_PATH.'/countries.xml','countries');
		$aCountries = array();
		foreach($config->get('country') as $country)
		{
			if ($country->alpha2 == $row['taxCountryId']) {
				$arr = $country->name;
			}
		}
		echo $arr;
	?>
	</td>
</tr>
<tr>
	<td>Telepon:</td>
	<td><?php echo $row['telephone']; ?></td>
</tr>
<tr>
	<td><abbr>Metode Pembayaran</abbr></td>
	<td><?php echo $row['paymentMethod']; ?></td>
</tr>
<tr>
	<td>Terakhir di modifikasi</td>
	<td><?php echo $row['lastModified']; ?></td>
</tr>
<tr>
	<td>Tanggal pembelian</td>
	<td><?php echo ($row['datePurchased'])?strftime("%d-%m-%Y",strtotime($row['datePurchased'])):'undefined'; ?></td>
</tr>
<tr>
	<td><abbr>Status Pesanan</abbr></td>
	<td><?php echo $row['ordersStatus']; ?></td>
</tr>
<tr>
	<td>Pesanan selesai tanggal</td>
	<td><?php echo $row['dateOrderFinished']; ?></td>
</tr>
<tr>
	<td>Mata Uang</td>
	<td><?php echo $row['currency']; ?></td>
</tr>
<tr>
	<td>Total Pesanan</td>
	<td><?php echo $row['orderTotal']; ?></td>
</tr>
<tr>
	<td>Alamat IP:</td>
	<td><?php echo $row['ipAddress']; ?></td>
</tr>
<tr>
	<td>Tanggal Pembayaran:</td>
	<td><?php echo strftime("%d-%m-%Y",strtotime($this->Paid)); ?></td>
</tr>
<?php } ?>
</table>
<input type="hidden" name="orderId" value="<?php echo $this->idOrder; ?>">
</fieldset>
<fieldset>
<legend>DETAIL</legend>
<table class="no-style full">
<thead>
	<th>No</th>
	<th>Item ID</th>
	<th>Nama</th>
	<th>Harga</th>
	<th>Total</th>
	<th>Tax</th>
	<th>Qty</th>
</thead>
<tbody>
<?php $i =1; foreach($this->rowsetDetail as $rowDetail) { ?>
<tr>
	<td><?php echo $i; ?></td>
	<td><?php echo $rowDetail['itemId']; ?></td>
	<td><?php echo $rowDetail['documentName']; ?></td>
	<td><?php echo number_format($rowDetail['price'],2); ?></td>
	<td><?php echo number_format($rowDetail['finalPrice'],2); ?></td>
	<td><?php echo number_format($rowDetail['tax'],2); ?> %</td>
	<td><?php echo $rowDetail['qty']; ?></td>
</tr>
<?php $i++; } ?>
</tbody>
</table>
</fieldset>
<div class="box box-success" id="message"></div>
<fieldset>
<legend>SEJARAH KONFIRMASI PEMBAYARAN</legend>
<table class="no-style full">
<thead>
	<th>No</th>
	<th>Tanggal</th>
	<th>Metode</th>
	<th>Tujuan</th>
	<th>Nama</th>
	<th>Jumlah</th>
	<th>Catatan</th>
	<th colspan="2">Extra</th>
</thead>
<tbody>
<?php $i=1; foreach($this->rowsetConfirm as $rowConfirm) { ?>
<tr class="<?php ($i%2 ? 'gradeX' : 'gradeC'); ?>" id="row_<?php echo $rowConfirm['id']; ?>">
	<td><?php echo $i; ?></td>
	<td><?php echo Pandamp_Lib_Formater::get_date($rowConfirm->paymentDate); ?></td>
	<td><?php echo $rowConfirm->paymentMethod; ?></td>
	<td><?php echo $rowConfirm->destinationAccount; ?></td>
	<td>
	<?php echo $rowConfirm->senderAccount; ?><br/>
	<?php echo $rowConfirm->senderAccountName; ?><br/>
	<?php echo $rowConfirm->bankName; ?><br/>
	</td>
	<td>
	<?php echo number_format($rowConfirm->amount,2); ?>
	</td>
	<td><?php echo $rowConfirm->note; ?></td>
	<?php
	if($rowConfirm->confirmed == 0){
		$col = "green";
		$ext = "Unconfirmed";
	}else{
		$col = "red";
		$ext = "Rejected";
	}
	?>
	<td><b><font color="<?php echo $col; ?>"><?php echo $ext; ?></font></b></td>
	<td>
<a class="success" href="<?php echo $this->url(array('lang'=>$this->getLanguage(), 'controller'=>'store', 
            'action'=>'payconfirmyes', 'orderId'=>$this->idOrder),'segwact'); ?>">
            Accept [Confirm] </a>&nbsp;  
<a class="error" href="<?php echo $this->url(array('controller'=>'store', 
            'action'=>'payconfirmno', 'orderId'=>$this->idOrder )); ?>">Reject </a> &nbsp;
<a class="notice" href="#" id="<?php echo $rowConfirm->id; ?>">Delete</a>
	</td>
</tr>
<?php $i++; } ?>
</tbody>
</table>
</fieldset>
<p style="z-index:1;overflow:hidden;">
<input type="button" value="Kembali" class="btn" onclick="javascript:history.back();" />
</p><br/>
</form>

<script type="text/javascript">
$(document).ready(function(){
	$(".notice").live('click',function(){
		if (confirm("Are you sure?")) {
			var iId = $(this).attr('id');
            $.post('<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/store/deleteconfirm/orderId/'+iId,function(){
                $('#row_'+iId).fadeOut("slow");
                $('#message').fadeIn("slow", function(){
                    $(this).html("Row "+iId+" Deleted Successfully").delay(2000).fadeOut(1000);
                });
            })
			
		}
		return false;
	});
});
</script>