<fieldset>
<legend>PENGATURAN TOKO</legend>
<table class="no-style full">
<thead>
	<th>No</th>
	<th>ID</th>
	<th>Value</th>
	<th>Note</th>
	<th>Aksi</th>
</thead>
<tbody>
<?php $i=1; foreach($this->rows as $row) { ?>
<tr>
	<td><?php echo $i; ?></td>
	<td><?php echo $row->settingKey; ?></td>
	<td><?php echo $row->settingValue; ?></td>
	<td><?php echo htmlentities($row->note); ?></td>
	<td><a href="<?php echo $this->url(array('controller'=>'store', 
	'action'=>'editPaymentSetting', 'id'=>$row->settingId)); ?>">edit</a></td>
</tr>
<?php $i++; } ?>
</tbody>
</table>
</fieldset>