<h5>PESANAN yang AKAN DIBAYARKAN KEMBALI</h5>
<fieldset>
<legend>NO. PESANAN: <?=$this->id;?></legend>
<div class="width8" align="right">
    <form style="z-index:1;overflow:hidden;">
    <input class="btn btn-green big" type="button" value="Refund" onclick="window.location.href='<?=ROOT_URL?>/<?=$this->getLanguage();?>/store/refunded/id/<?=$this->id?>'" />
    &nbsp;
    <input class="btn btn-green big" type="button" value="Back" onclick="javascript:history.back();" />
    &nbsp;&nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">&nbsp;</div>
<?  foreach($this->rows as $row): ?>
<div class="colgroup">
	<div class="column width2 first">No.Faktur</div>
	<div class="column width2"><?=$row['invoiceNumber'];?></div>
	<div class="column width2">Kode Pelanggan</div>
	<div class="column width2"><?=$row['userId'];?></div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">NPWP</div>
	<div class="column width2"><?=$row['taxNumber'];?>&nbsp;</div>
	<div class="column width2">Perusahaan</div>
	<div class="column width2"><?=$row['taxCompany'];?>&nbsp;</div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Alamat Penagihan</div>
	<div class="column width2"><?=$row['taxAddress'];?>&nbsp;</div>
	<div class="column width2">Kota</div>
	<div class="column width2"><?=$row['taxCity'];?>&nbsp;</div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Kodepos</div>
	<div class="column width2"><?=$row['taxZip'];?>&nbsp;</div>
	<div class="column width2">Propinsi</div>
	<div class="column width2">
	<?
	$modelState = new App_Model_Db_Table_State();
	$rowState = $modelState->find($row['taxProvince'])->current();
	if ($rowState) {
		$state = $rowState->pname;
	}
	else 
	{
		$state = "";
	}
	echo $state;
	?>&nbsp;
	</div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Negara</div>
	<div class="column width2">
	<?
	$config = new Zend_Config_Xml(CONFIG_PATH.'/countries.xml','countries');
	$aCountries = array();
	foreach($config->get('country') as $country)
	{
		if ($country->alpha2 == $row['taxCountryId']) {
			$arr = $country->name;
		}
	}
	echo $arr;
	?>&nbsp;
	</div>
	<div class="column width2">Telp.</div>
	<div class="column width2"><?=$row['taxPhone'];?>&nbsp;</div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Metode Pembayaran</div>
	<div class="column width2"><?=$row['paymentMethod'];?></div>
	<div class="column width2">Catatan</div>
	<div class="column width2"><?=$row['paymentMethodNote'];?>&nbsp;</div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Terakhir dimodifikasi</div>
	<div class="column width2"><?=(!($row['lastModified'] == "0000-00-00 00:00:00"))?strftime("%d-%m-%Y",strtotime($row['lastModified'])):'undefined'; ?></div>
	<div class="column width2">Tanggal Pembelian</div>
	<div class="column width2"><?=(!($row['datePurchased'] == "0000-00-00 00:00:00"))?strftime("%d-%m-%Y",strtotime($row['datePurchased'])):'undefined'; ?></div>

	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Status Pesanan</div>
	<div class="column width2">
	<?
	$modelOrderStatus = new App_Model_Db_Table_OrderStatus();
	$rowOrderStatus = $modelOrderStatus->find($row['orderStatus'])->current();
	echo $rowOrderStatus->ordersStatus;
	?>
	</div>
	<div class="column width2">Tanggal Penyelesaian Pesanan</div>
	<div class="column width2"><?=(!($row['dateOrderFinished'] == "0000-00-00 00:00:00"))?strftime("%d-%m-%Y",strtotime($row['dateOrderFinished'])):'undefined'; ?></div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Mata Uang</div>
	<div class="column width2"><?=$row['currency'];?></div>
	<div class="column width2">Total Pesanan</div>
	<div class="column width2"><?=$row['orderTotal'];?></div>
	
	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Potongan Pajak</div>
	<div class="column width2"><?=$row['orderTax'];?></div>
	<div class="column width2">Alamat IP</div>
	<div class="column width2"><?=$row['ipAddress'];?></div>

	<div class="clear">&nbsp;</div>
	
	<div class="column width2 first">Tanggal Pembayaran</div>
	<div class="column width2"><?=(!($row['paymentDate'] == "0000-00-00 00:00:00"))?strftime("%d-%m-%Y",strtotime($row['paymentDate'])):'undefined'; ?></div>
</div>
<?endforeach;?>
</fieldset>
<fieldset>
<legend>DETAIL</legend>
<table class="no-style full">
<thead>
	<th>No</th>
	<th>Item ID</th>
	<th>Nama</th>
	<th>Harga</th>
	<th>Total</th>
	<th>Tax</th>
	<th>Qty</th>
</thead>
<tbody>
<?$i =1; foreach($this->rowsDetail as $rowDetail): ?>
<tr>
	<td><?=$i;?></td>
	<td><?=$rowDetail['itemId'];?></td>
	<td><?=$rowDetail['documentName'];?></td>
	<td><?=number_format($rowDetail['price'],2);?></td>
	<td><?=number_format($rowDetail['finalPrice'],2);?></td>
	<td><?=number_format($rowDetail['tax'],2); ?> %</td>
	<td><?=$rowDetail['qty']; ?></td>
</tr>
<? $i++; endforeach; ?>
</tbody>
</table>

</fieldset>