<div class="width7">
    <div class="wrapper">

        <form id="frmSearch" name="frmSearch" method="post">
            <fieldset>
                <legend>Transaction</legend>
            <p>
                <label>Status : </label><input id="sStatus" name="sStatus" size=10 value="<?php echo $this->sStatus; ?>">
                <label>Username : </label><input id="sUsername" name="sUsername" size=10 value="<?php echo $this->sUsername; ?>">
                <label>Date min : </label><input type="date" id="fdate" name="fdate" value="<?php echo $this->fdate; ?>"/>
                <label>Date max : </label><input type="date" id="ldate" name="ldate" value="<?php echo $this->ldate; ?>"/>
                <input type="hidden" id="limit" name="limit" value="10">
                <input type="hidden" id="offset" name="offset" value="<?php echo $this->offset; ?>">
                <input class="btn btn-green big" value="Search" type="submit">
            </p>
            </fieldset>
        </form>

        <table class="display stylized" id="transaction">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Description</th>
                    <th>Payment Method</th>
                    <th>Purchasing Date</th>
                    <th>Modified Date</th>
                    <th>Order Status</th>
                    <th>Total Price</th>
                    <th>Qty</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $i=$this->offset+1; foreach($this->rows as $row) { ?>
                <tr class="<?php echo ($i%2 ? 'gradeX' : 'gradeC'); ?>">
                    <td><?php echo $i; ?></td>
                    <td>
                        User ID : <?php echo $row->userId; ?><br />
                        Invoice : <?php echo $row->invoiceNumber; ?><br />
                        Name    : <?php echo $row->fullName; ?><br />
                        Company : <?php echo $row->company; ?><br />&nbsp;
                    </td>
                    <td><?php echo $row->paymentMethod; ?></td>
                    <td class="center"><?php echo strftime("%Y-%m-%d", strtotime($row->datePurchased)); ?></td>
                    <td><?php echo strftime("%Y-%m-%d",strtotime($row->lastModified)); ?></td>
                    <td><?php echo $row->ordersStatus; ?></td>
                    <td><?php echo $row->orderTotal; ?></td>
                    <td><?php echo $row->countTotal; ?></td>
                    <td>
                       <a href="<?php echo $this->url(array('controller'=>'store',
                            'action'=>'editOrder', 'orderId'=>$row->orderId)); ?>">edit</a>
                       <a href="<?php echo $this->url(array('controller'=>'store',
                            'action'=>'trdetail', 'orderId'=>$row->orderId)); ?>">detail</a>
                       <?php if($row->orderStatus == 3) { ?>
                       <a href="<?php echo $this->url(array('controller'=>'store',
                            'action'=>'refund', 'orderId'=>$row->orderId)); ?>">refund</a>
                       <?php } ?>
                    </td>
                </tr>
                <?php $i++; } ?>
            </tbody>
        </table>


        <div class="clear">&nbsp;</div>

    </div>
</div>