<div class="table-responsive mailbox-messages">
<table class="table table-hover table-striped">
	<tbody>	
    <tr>
        <td class="ta-left">
            <table>
                <?php foreach ($this->aAttribute as $row) { ?>
                <?php if ((!in_array($row['value'],array('no-info','-','in',''))) && (!in_array($row['name'],array('Billing')))) { ?>
                <tr valign="top">

                    <?php
                    if ($this->rowCatalog->profileGuid == "kutu_putusan") {
                    if (($row['name'] == "Title") || ($row['name'] == "Sub Title")) {
                    ?>
                        <td width="100">&nbsp;</td>
                    <?php } else { ?>
                        <td width="100"><h5><?php echo $row['name']; ?></h5></td>
                    <?php 
                    }
                    }
                    else { ?>
                        <td width="100"><h5><?php echo $row['name']; ?></h5></td>
                    <?php } ?>

                    <td width="10">&nbsp;</td>
                    
                    <?php if (in_array($row['name'],array('Date','Tanggal Dibacakan','Tanggal berlaku'))) { ?>
                    <td><?php echo strftime("%d %B %Y",strtotime($row['value'])); ?></td>
                    <?php } else if (in_array($row['name'],array('Name','Kategori Klinik','Mitra'))) { ?>
                    <td><?php echo $this->getCatalogTitle($row['value'],'fixedTitle'); ?></td>
                    <?php } else { ?>
                    <td><?php echo $row['value']; ?></td>
                    <?php } ?>
                </tr>
                <?php }} ?>
            </table>
        </td>
    </tr>
    </tbody>
</table>
</div>