<?php 
/**
 * Pandamp
 * 
 * @author		2012-2013 Nihki Prihadi <nihki@madaniyah.com>
 * @version		$Id: index.phtml 1 2012-08-29 13:35Z $
 */
?>
<!-- section category -->
<section class="column first">
	<?php if ($this->printmode <> 1) : ?>
	<div class="clear">&nbsp;</div>
	<div class="width8">
		<p>You can use following conditions to filter the list of profile</p>
	</div>
	<?php endif; ?>
	<div class="clear">&nbsp;</div>
	<div class="colgroup" id="filterContainer">
		<form method="GET" name="report">
			<div class="column width1 first">
				<label>Profile</label>
			</div>
			<div class="column width7">
				<?php if ($this->printmode == 1) :
				echo ': '.$this->profname;
				else :
				echo $this->helperLoader('report')->selectProf(array('id' => 'prof', 'name' => 'prof', 'class' => 'no-class', 'selected' => $this->prof));
				endif; ?>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="column width1 first">
				<label>Tahun</label>
			</div>
			<div class="column width7">
				<?php if ($this->printmode == 1) :
				echo ': '.$this->y;
				else :
				echo $this->helperLoader('report')->selectYear(array('id' => 'year', 'name' => 'year', 'class' => 'no-class', 'selected' => $this->y));
				endif; ?>
			</div>
			<div class="clear">&nbsp;</div>
			<div class="column width1 first">
				<label>Tampilkan</label>
			</div>
			<div class="column width7">
				<?php if ($this->printmode == 1) :
				echo ': '.$this->showname;
				else :
				echo $this->helperLoader('report')->selectShow(array('id' => 'show', 'name' => 'show', 'class' => 'no-class', 'selected' => $this->show));
				endif; ?>
			</div>
		</form>
	</div>
	<div class="clear">&nbsp;</div>
	<?php if ($this->printmode <> 1) : ?>
	<div class="align-right">
		<a href="<?php echo $this->uri.$this->sAddition; ?>printmode=1" target="_blank"><img border="0" src="<?php echo $this->cdn('styles'); ?>/images/printer.gif"></a>
	</div>
	<div style="clear:both"></div>
	<?php endif; ?>
	<hr />	
	<div class="width8">
		<?php if ($this->show == 1) : ?>
		<table <?php if ($this->printmode <> 1) : ?>class="display stylized"<?php else : ?>class="full" cellspacing="0" border="1"<?php endif; ?> id="report_graph">
		<!-- BEGIN row_graphic -->
		<tr>
			<td align="center"><img src="<?php echo $this->graph_url; ?>" alt="<?php echo $this->graph_alt; ?>"></td>
		</tr>
		<!-- END row_graphic -->
		</table>
		<?php else : ?>
		<table <?php if ($this->printmode <> 1) : ?>class="display stylized"<?php else : ?>class="full" cellspacing="0" border="1"<?php endif; ?> id="report">
			<thead>
				<tr>
					<th class="ta-center" colspan="2">REPORTS</th>
					<th class="ta-center" colspan="12">MONTH</th>
					<th class="ta-center">YEAR</th>
				</tr>
				<tr>
					<th>No.</th>
					<th>Division</th>
					<th>Jan</th>
					<th>Feb</th>
					<th>Mar</th>
					<th>Apr</th>
					<th>Mei</th>
					<th>Jun</th>
					<th>Jul</th>
					<th>Agt</th>
					<th>Sep</th>
					<th>Okt</th>
					<th>Nov</th>
					<th>Des</th>
					<th class="ta-center"><?php echo $this->y; ?></th>
				</tr>
			</thead>
			<tbody>
				<?php if ($this->prof == 0 || $this->prof == 1) { ?>
				<tr>
					<td rowspan="3" class="ta-center">1</td>
					<td colspan="14"><abbr>Data Center</abbr></td>
				</tr>
				<tr>
					<td><abbr>Peraturan</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/report/hol/dc/y/<?php echo $this->y; ?>/p/peraturan" target="_blank">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->p);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->p[$i];
						else : ?>
						<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/report/hol/dc/y/<?php echo $this->m[$i]; ?>/p/peraturan" target="_blank"><?php echo $this->p[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->yp; ?></th>
				</tr>
				<tr>
					<td><abbr>Putusan</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/report/hol/dc/y/<?php echo $this->y; ?>/p/putusan" target="_blank">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->put);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->put[$i];
						else : ?>
						<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/report/hol/dc/y/<?php echo $this->m[$i]; ?>/p/putusan" target="_blank"><?php echo $this->put[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->yput; ?></th>
				</tr>
				<?php } if ($this->prof == 0 || $this->prof == 2) { ?>
				<tr>
					<td rowspan="2" class="ta-center">2</td>
					<td colspan="14"><abbr>Redaksi</abbr></td>
				</tr>
				<tr>
					<td><abbr>Article</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/report/hol/dc/y/<?php echo $this->y; ?>/p/article" target="_blank">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->art);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->art[$i];
						else : ?>
						<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/report/hol/dc/y/<?php echo $this->m[$i]; ?>/p/article" target="_blank"><?php echo $this->art[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->yart; ?></th>
				</tr>
				<?php } if ($this->prof == 0 || $this->prof == 3) { ?>
				<tr>
					<td rowspan="2" class="ta-center">3</td>
					<td colspan="14"><abbr>Klinik</abbr></td>
				</tr>
				<tr>
					<td><abbr>All Questions</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->clinic);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->clinic[$i];
						else : ?>
						<a href=""><?php echo $this->clinic[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->ykli; ?></th>
				</tr>
				<?php } if ($this->prof == 0 || $this->prof == 4) { ?>
				<tr>
					<td rowspan="4" class="ta-center">4</td>
					<td colspan="14"><abbr>Redaksi English</abbr></td>
				</tr>
				<tr>
					<td><abbr>News</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->enews);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->enews[$i];
						else : ?>
						<a href=""><?php echo $this->enews[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->yenews; ?></th>
				</tr>
				<tr>
					<td><abbr>ILB</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->eilb);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->eilb[$i];
						else : ?>
						<a href=""><?php echo $this->eilb[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->yeilb; ?></th>
				</tr>
				<tr>
					<td><abbr>ILD</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->eild);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->eild[$i];
						else : ?>
						<a href=""><?php echo $this->eild[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->yeild; ?></th>
				</tr>
				<?php } if ($this->prof == 0 || $this->prof == 5) { ?>
				<tr>
					<td rowspan="10" class="ta-center">5</td>
					<td colspan="14"><abbr>Layanan</abbr></td>
				</tr>
				<tr>
					<td><abbr>New Member Free</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user[$i];
						else : ?>
						<a href=""><?php echo $this->user[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member Individual</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_individual);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_individual[$i];
						else : ?>
						<a href=""><?php echo $this->user_individual[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_individual; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member Corporate</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_corporate);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_corporate[$i];
						else : ?>
						<a href=""><?php echo $this->user_corporate[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_corporate; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member ILB</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_ilb);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_ilb[$i];
						else : ?>
						<a href=""><?php echo $this->user_ilb[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_ilb; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member ILD</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_ild);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_ild[$i];
						else : ?>
						<a href=""><?php echo $this->user_ild[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_ild; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member COMPLETE</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_complete);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_complete[$i];
						else : ?>
						<a href=""><?php echo $this->user_complete[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_complete; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member PROFESSIONAL</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_professional);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_professional[$i];
						else : ?>
						<a href=""><?php echo $this->user_professional[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_professional; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member PREMIUM</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_premium);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_premium[$i];
						else : ?>
						<a href=""><?php echo $this->user_premium[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_premium; ?></th>
				</tr>
				<tr>
					<td><abbr>New Member EXECUTIVE</abbr><?php if ($this->printmode <> 1) : ?>&nbsp;<a href="">[detail]</a><?php endif; ?></td>
					<?php for ($i=0;$i<count($this->user_exec);$i++) : ?>
					<td class="ta-center">
						<?php if ($this->printmode == 1) :
						echo $this->user_exec[$i];
						else : ?>
						<a href=""><?php echo $this->user_exec[$i]; ?></a>
						<?php endif; ?>
					</td>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->year_user_executive; ?></th>
				</tr>
				<?php } ?>
				<tr>
					<th>&nbsp;</th>
					<th><abbr>Total</abbr></th>
					<?php for ($i=0;$i<count($this->sum);$i++) : ?>
					<th class="ta-center"><?php echo $this->sum[$i]; ?></th>
					<?php endfor; ?>
					<th class="ta-center"><?php echo $this->sumrep; ?></th>
				</tr>
			</tbody>
		</table>
		<?php endif; ?>
	</div>
</section>
