<?php 
$this->headScript()
	->appendFile('//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js')
	->appendFile($this->cdn('scripts') . '/plugins/daterangepicker/daterangepicker.js')
	->appendFile($this->cdn('scripts') . '/plugins/timepicker/bootstrap-timepicker.min.js');

?>

<!-- Advanced Search -->
<div id="advs-modal-form" class="modal fade" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger">Advanced Search</h4>
			</div>
			<div class="modal-body no-padding">
				<table class="table table-striped table-bordered table-hover no-margin-bottom no-border-top">
				<tbody>
					<tr>
						<td>Query</td>
						<td>
							<input name="p" type="text" placeholder="Search ..." class="form-control input-xlarge" id="modal-search-input" />
						</td>
					</tr>
					<tr>
						<td>Profile</td>
						<td>
							<?php echo $this->profile(); ?>
						</td>
					</tr>
					<tr>
						<td>Tanggal</td>
						<td>
							<div class="input-group">
								<button class="btn btn-default pull-right" id="drp">
                        			<i class="fa fa-calendar"></i> Date range picker
                        			<i class="fa fa-caret-down"></i>
                      			</button>
							</div>
						
						</td>
					</tr>
					<tr>
						<td>Start Time</td>
						<td>
							<div class="input-group bootstrap-timepicker" style="width: 180px">
								<input id="timepicker1" type="text" class="form-control" />
								<span class="input-group-addon">
									<i class="fa fa-clock-o"></i>
								</span>
							</div>
						
						</td>
					</tr>
					<tr>
						<td>End Time</td>
						<td>
							<div class="input-group bootstrap-timepicker" style="width: 180px">
								<input id="timepicker2" type="text" class="form-control" />
								<span class="input-group-addon">
									<i class="fa fa-clock-o"></i>
								</span>
							</div>
						
						</td>
					</tr>
				</tbody>
				</table>
			</div>
			<div class="modal-footer">
				<a href="javascript:;" class="btn btn-sm" data-dismiss="modal">
					<i class="icon-remove"></i>
					Cancel
				</a>
				
				<a href="javascript:;" id="goadv" class="btn btn-sm btn-primary">
					<i class="icon-search"></i>
					GO
				</a>
			</div>
		</div>
	</div>
</div>

<footer class="main-footer">
   	<div class="pull-right hidden-xs">
   		<b>Version</b> 2.3.0
   	</div>
   	<strong>&copy; 2015</strong>
</footer>
<!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
<div style="position: fixed; height: auto;" class="control-sidebar-bg"></div>
<?php $this->headScript()->captureStart(); ?>
$(function () {
	$('#drp').daterangepicker(
            {
              format: 'YYYY-MM-DD',	
              ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
              },
              startDate: moment().subtract(29, 'days'),
              endDate: moment()
            },
        function (start, end) {
          $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        }
	);
	
	$('#timepicker1').timepicker({
		defaultTime:'0',
		minuteStep: 1,
		showSeconds: true,
		showMeridian: false
	}).next().on('click', function(){
		$(this).prev().focus();
	});
	
	$('#timepicker2').timepicker({
		minuteStep: 1,
		showSeconds: true,
		showMeridian: false
	}).next().on('click', function(){
		$(this).prev().focus();
	});
	
	$("#goadv").click(function(){
		var query = $("#modal-search-input").val(),
			profile = $("#advs-modal-form select[name=pg] option:selected").val(), 
			drp1 = $("input[name='daterangepicker_start']").val(), 
			drp2 = $("input[name='daterangepicker_end']").val(), 
			tp1 = $("#timepicker1").val(), 
			tp2 = $("#timepicker2").val();
			
		var selq='';
		if (query !== '') {
			selq = query;
		}
		if ($("#advs-modal-form #pg option:selected").val() !== '') {
			if (query !== '') {
				selq += ' profile:'+profile;
			}
			else
			{
				selq += 'profile:'+profile;
			}
			
		}
		if (drp1 !== '' && drp2 !== '') {
			if ((query !== '') || ($("#advs-modal-form #pg option:selected").val() !== '')) {
				selq += ' <?php echo $this->layout()->sort; ?>:[' + drp1 + 'T' + tp1 + 'Z TO ' + drp2 + 'T' + tp2 + 'Z]';
			}
			else 
			{
				selq += '<?php echo $this->layout()->sort; ?>:[' + drp1 + 'T' + tp1 + 'Z TO ' + drp2 + 'T' + tp2 + 'Z]';
			}
			
		}

		window.location.href = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=" + encodeURIComponent(selq).replace(/%20/g,'+');
	});
});
<?php $this->headScript()->captureEnd(); ?>