<?php 
$this->headScript()
	->appendFile($this->cdn('scripts') . '/plugins/daterangepicker/moment.js')
	->appendFile($this->cdn('scripts') . '/plugins/daterangepicker/daterangepicker.js');

?>
<?php 
if (empty($this->layout()->sort)) $this->layout()->sort = "publishedDate";
?>
<!-- Advanced Search -->
<div id="advs-modal-form" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger">Advanced Search</h4>
			</div>
			<div class="modal-body no-padding">
				<table class="table table-striped table-bordered table-hover no-margin-bottom no-border-top">
				<tbody>
					<tr>
						<td>Query</td>
						<td>
							<input name="p" type="text" placeholder="Search ..." class="form-control input-xlarge" id="modal-search-input" />
						</td>
					</tr>
					<tr>
						<td>Profile</td>
						<td>
							<?php echo $this->profile(); ?>
						</td>
					</tr>
					<tr>
						<td>Tanggal</td>
						<td>
							<div id="drp" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc;">
    							<i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
    							<span></span> <b class="caret"></b>
							</div>
						
						</td>
					</tr>
					<tr>
						<td>Status</td>
						<td>
							<select name="cekstatus" id="cekstatus" class="form-control">
								<option value="">---</option>
								<option value="-1">Archived</option>
								<option value="-2">Deleted</option>
								<option value="0">Draft</option>
								<option value="1">Not Applicable</option>
								<option value="2">UnPublished</option>
								<option value="99">Published</option>
							</select>
						
						</td>
					</tr>
				</tbody>
				</table>
			</div>
			<div class="modal-footer">
				<a href="javascript:;" class="btn btn-sm" data-dismiss="modal">
					<i class="icon-remove"></i>
					Cancel
				</a>
				
				<a href="javascript:;" id="goadv" class="btn btn-sm btn-primary">
					<i class="icon-search"></i>
					GO
				</a>
			</div>
		</div>
	</div>
</div>

<footer class="main-footer">
   	<div class="pull-right hidden-xs">
   		<b>Version</b> 2.3.0
   	</div>
   	<strong>&copy; 2015</strong>
</footer>
<!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
<div style="position: fixed; height: auto;" class="control-sidebar-bg"></div>
<?php $this->headScript()->captureStart(); ?>
$(function () {
	function cb(start, end) {
        $('#drp span').html(start.format('MMMM D, YYYY HH:mm:ss') + ' - ' + end.format('MMMM D, YYYY HH:mm:ss'));
    }
    cb(moment().subtract(29, 'days'), moment());
	$('#drp').daterangepicker(
            {
              locale: {
              	format: 'YYYY-MM-DDTHH:mm:ss',
              },	
              ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
              },
              timePicker: true,
              timePicker24Hour: true,
              timePickerSeconds: true,
              startDate: moment().subtract(29, 'days'),
              endDate: moment()
            }, cb
        
	);
	
	$("#goadv").click(function(){
		var query = $("#modal-search-input").val(),
			profile = $("#advs-modal-form select[name=pg] option:selected").val(), 
			cekstatus = $("#advs-modal-form select[name=cekstatus] option:selected").val(), 
			drp1 = $("input[name='daterangepicker_start']").val(), 
			drp2 = $("input[name='daterangepicker_end']").val(); 
			
		var selq='',
			stat='';
		if (query !== '') {
			selq = query;
		}
		if ($("#advs-modal-form #pg option:selected").val() !== '') {
			if (query !== '') {
				selq += ' profile:'+profile;
			}
			else
			{
				selq += 'profile:'+profile;
			}
			
		}
		if ($("#advs-modal-form #cekstatus option:selected").val() !== '') {
			stat = '&status=' + cekstatus;
		}
		if (drp1 !== '' && drp2 !== '') {
			if ((query !== '') || ($("#advs-modal-form #pg option:selected").val() !== '')) {
				selq += ' <?php echo $this->layout()->sort; ?>:[' + drp1 + 'Z TO ' + drp2 + 'Z]';
			}
			else 
			{
				selq += '<?php echo $this->layout()->sort; ?>:[' + drp1 + 'Z TO ' + drp2 + 'Z]';
			}
			
		}
		
		
		window.location.href = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=" + encodeURIComponent(selq).replace(/%20/g,'+')+stat;
	});
});
<?php $this->headScript()->captureEnd(); ?>