<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>CMS Hukumonline</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/adm/administry.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/custom.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/calender.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/pagination.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('scripts')?>/hol/jquery/jquery.ui/themes/base/ui.core.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('scripts')?>/hol/jquery/jquery.ui/themes/base/ui.resizable.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('scripts')?>/hol/jquery/jquery.ui/themes/base/ui.dialog.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('scripts')?>/hol/jquery/jquery.ui/themes/base/ui.theme.css" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/jquery/tooltip/jquery.tipTip.min.js,hol/jquery/paging/jquery.pagination.js,hol/smooth.scroller.js,hol/jquery/jquery.ui/ui.core.js,hol/jquery/jquery.ui/ui.draggable.js,hol/jquery/jquery.ui/ui.resizable.js,hol/jquery/jquery.ui/ui.dialog.js,hol/jquery/jquery.json/jquery.json.min.js,hol/jquery/jquery.ajaxq/jquery.ajaxq.min.js,adm/base64.js" >
		</script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->

        <script type="text/javascript">
        $(document).ready(function(){
        	Administry.setup();
        	
			
        });
        </script>

    </head>
    <body>
        <?= $this->render("header.phtml"); ?>

	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper">
                <?=$this->layout()->content;?>
		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper">
                <nav>
                    <a href="#">Dashboard</a> ·
                    <a href="#">Content</a> ·
                    <a href="#">Reports</a> ·
                    <a href="#">Users</a> ·
                    <a href="#">Media</a> ·
                    <a href="#">Events</a> ·
                    <a href="#">Newsletter</a> ·
                    <a href="#">Settings</a>
                </nav>
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->

	<!-- Animated footer -->
	<footer id="animated">
		<ul>
			<li><a href="#">Dashboard</a></li>
			<li><a href="#">Content</a></li>
			<li><a href="#">Reports</a></li>
			<li><a href="#">Users</a></li>
			<li><a href="#">Media</a></li>
			<li><a href="#">Events</a></li>
			<li><a href="#">Newsletter</a></li>
			<li><a href="#">Settings</a></li>
		</ul>
	</footer>
	<!-- End of Animated footer -->

	<!-- Scroll to top link -->
	<a style="display: none;" id="totop">^ scroll to top</a>
    <script type="text/javascript" src="<?=$this->cdn('scripts');?>/hol/administry.js"></script>
    </body>
</html>