<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- search form -->
		<form action="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="Search..." value="<?php echo $this->layout()->searchQuery; ?>">
				<span class="input-group-btn">
					<button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
				</span>
			</div>
			
		</form>
		<p class="margin"><a href="#advs-modal-form" data-toggle="modal"><small><i class="fa fa-search-plus"></i> Advanced</small></a></p>
		
		<!-- /.search form -->
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<ul class="sidebar-menu">
			<li class="header">MAIN NAVIGATION</li>
			<?php echo $this->action('facetprofile','dms','search',[
					'q'=>$this->layout()->searchQuery,
					'category'=>$this->layout()->category,
					'clinic_selected'=>$this->layout()->clinicSelected,
					'putusanSelected'=>$this->layout()->putusanSelected
				]); ?>
			<?php echo $this->action('facetcatclinic','dms','search',['q'=>$this->layout()->searchQuery,
					'kategoriklinik'=>$this->layout()->kategoriklinik]); ?>
			<?php echo $this->action('facetlp','dms','search',['q'=>$this->layout()->searchQuery,
					'regulationType'=>$this->layout()->regulationType]); ?>
			<?php echo $this->action('facetjp','dms','search',['q'=>$this->layout()->searchQuery,
					'regulationType'=>$this->layout()->regulationType]); ?>
		</ul>
				
	</section>
	<!-- /.sidebar -->
</aside>