<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- search form -->
		<form action="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="Search...">
				<input type="hidden" name="sLimit" value="25">
            	<input type="hidden" name="sOffset" value="0">
            	<input type="hidden" name="category" value="all">
				<span class="input-group-btn">
					<button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
				</span>
			</div>
			
		</form>
		<p class="margin"><a href=""><small><i class="fa fa-search-plus"></i> Advanced</small></a></p>
		<!-- /.search form -->
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<ul class="sidebar-menu">
			<li class="header">MAIN NAVIGATION</li>
			<li id="dmstree"></li>
		</ul>
				
	</section>
	<!-- /.sidebar -->
</aside>
<?php $this->headScript()->captureStart(); ?>
$(function () {
	$("#dmstree").jstree({
		"core" : {
			"check_callback" : true,
			"data" : {
				'url' : '<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/folder/getchildreninjson2',
				'data' : function (node) {
					return { 'id' : node.id };
				}
			}
		},
		"plugins" : [ "contextmenu", "dnd" ]	
	})
	.bind( "dblclick.jstree", function( e ) {
		e.preventDefault();
		var node = $(e.target).closest("li");
		var href = node.children("a").attr("href");
		window.location.href = "<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/explorer/browse/node/"+node[0].id;
	})
	.bind( "ready.jstree open_node.jstree", function (e, data) {
		var dom = data && data.node ? data.instance.get_node(data.node, true).children('ul') : data.instance.element;
		dom.find('.jstree-anchor'); 
		dom.find('.jstree-anchor').each(function() {
			data.instance.open_node([<?php echo $this->layout()->breadcrumb; ?>]);
			data.instance.select_node('<?php echo $this->layout()->folderGuid; ?>');  
	  	});
		
	});
});
<?php $this->headScript()->captureEnd(); ?>