<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>CMS Hukumonline</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/adm/administry.css" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/jquery/form/jquery.validate.pack.js" ></script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->

        <script type="text/javascript">
            jQuery(document).ready(function(){
                
                var validator = jQuery("#registerform").validate({
                   rules:{
                       fullname:"required"
                       /*
                       ,company:{
                           remote: "<?=$this->baseUrl(); ?>/<?=$this->getLanguage();?>/customer/manager/checkcompany"
                       }
                       */
                       ,aro_groups:"required"
                       ,payment:{
                           digits:true
                           ,range:[1,36]
                       }
                       ,trial:{
                       		digits:true
                       }
                       ,email:{
                           required: true,
                           email: true
                       }
                       ,username:{
                           required: true,
                           minlength: 6,
                           remote: "<?=$this->baseUrl(); ?>/<?=$this->getLanguage();?>/customer/manager/checkusername"
                       }
                       ,password:"required"
                   }
                   ,messages:{
                       aro_groups:"Choose package"
                       ,payment: {
                            digits: "Digits only",
                            range: "Value between {0} and {1}."
                        }
                   }
                    ,errorPlacement: function(error, element) {
                        error.insertAfter(element.parent().find('label:first'));
                    }
                    ,success: function(label){
                        label.html("&nbsp;").addClass("ok");
                    }
                });
            }
        );
        </script>

    </head>
    <body>
        <!-- Header -->
        <header id="top">
            <div class="wrapper-login">
                <div id="title"><img src="<?=$this->cdn('images');?>/logo.png" alt="hukumonline" /><!--<span>CMS Hukumonline</span>--></div>
                <!-- Main navigation -->
                <nav id="menu">
                    <ul class="sf-menu sf-js-enabled sf-shadow">
                        <li><a href="<?=ROOT_URL;?>">Login</a></li>
                        <li class="current"><a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/account/register">Register</a></li>
                    </ul>
                </nav>
                <!-- End of Main navigation -->
            </div>
        </header>
        <!-- End of Header -->
	<!-- Page title -->
	<div id="pagetitle">
            <div class="wrapper-login"></div>
	</div>
	<!-- End of Page title -->

	<!-- Page content -->
	<div id="page">
            <!-- Wrapper -->
            <div class="wrapper-login">
                <!-- Login form -->
                <section class="full">

                    <?=$this->layout()->content;?>
                </section>
                <!-- End of login form -->

            </div>
            <!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper-login">
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->
        
    </body>
</html>