<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>CMS Hukumonline</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/adm/administry.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/style.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/pagination.css" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hpdia/jquery/jquery.json/jquery.json.min.js,hpdia/jquery/jquery.ajaxq/jquery.ajaxq.min.js,hol/jquery/jquery.cookie.js,hol/jquery/tooltip/jquery.tipTip.min.js,hol/jquery/form/jquery.validate.pack.js,hol/jquery/paging/jquery.pagination.js,hol/smooth.scroller.js" ></script>
		
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->


        <style type="text/css">
            #message {
                display: none;
            }
        </style>

        <script type="text/javascript">

            $(document).ready(function(){
                $("a[title], div[title], span[title]").tipTip();

                var isFirstTime = 1;

                var myPageIndex = 0;
                var itemsPerPage = <?=$this->itemsPerPage;?>;
                var currentOffset = <?=$this->offset;?>;
                var limit = <?=$this->limit;?>;
                var totalItems = <?=$this->totalItems;?>;

                var tmpCurrentPageIndex = currentOffset/itemsPerPage;

                $("#commentPagination").pagination(totalItems,
                {items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
                );

                function handlePaginationClick(new_page_index, pagination_container)
                {
                    if(!isFirstTime)
                    {
                        myPageIndex = new_page_index;
                        var nextOffset = (itemsPerPage * myPageIndex);

                        var url = "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/comment/catalog/browse/offset/"+nextOffset+"/limit/"+limit;
                        window.location = url;
                    }
                    isFirstTime = 0;
                    return false;
                }

                $('.delete').live('click', function(){
                    var removeId = $(this).attr('href');

                    if (confirm("Are you sure?")) {
                        window.location = '<?=ROOT_URL;?>/<?=$this->getLanguage();?>/comment/catalog/delete/id/'+removeId;
                    }

                    return false;
                });

                $("input[name=select_deselect]").click(function(){
                    var checked_status = this.checked;
                    $("input[class=check_me]").each(function(){
                        this.checked = checked_status;
                    });
               });
                                
                $('#deleteAction').click(function() {
                	var numSelected = $('input[type="checkbox"].check_me:checked').length;
                	var self = this;
                	if (0 == numSelected) {
                    	alert('Please select at least one comment');
                	}
                	else
                	{
            			var ids = new Array();
            			$('input[type="checkbox"].check_me:checked').each(function() {
            				ids.push($(this).val());
            			});
            			
            			$.ajaxq('comment_article_delete', {
            				url: "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/comment/catalog/delcom",
            				type: 'POST',
            				data: { id: $.toJSON(ids) },
                            beforeSend: function()
                            {
            					for (var i in ids) {
            						$('#row_' + ids[i]).addClass('loading').text('processing...');
            					}
                            },
            				success: function(response) {
            					if ('RESULT_OK' == response) {
            						for (var i in ids) {
            							$('#row_' + ids[i]).fadeOut('slow').removeClass('loading').text('delete');
            						}
            					}
            				}
            			});
                	
                	}
                });    

                $('.status').live('click', function(){
                    var removeId = $(this).attr('href');
                    qString = removeId.split('/');
                    var cId = qString[0];

                    if (confirm("Are you sure?")) {
                        window.location = '<?=ROOT_URL;?>/<?=$this->getLanguage();?>/comment/catalog/status/id/'+removeId;
                    }

                    return false;
                });


            });


        </script>

    </head>
    <body>
        <?= $this->render("header-pusatdata.phtml"); ?>

	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper">

                    <?=$this->layout()->content;?>

		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper">
                <nav>
                    <a href="#">Dashboard</a> ·
                    <a href="#">Content</a> ·
                    <a href="#">Reports</a> ·
                    <a href="#">Users</a> ·
                    <a href="#">Media</a> ·
                    <a href="#">Events</a> ·
                    <a href="#">Newsletter</a> ·
                    <a href="#">Settings</a>
                </nav>
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->

	<!-- Animated footer -->
	<footer id="animated">
		<ul>
			<li><a href="#">Dashboard</a></li>
			<li><a href="#">Content</a></li>
			<li><a href="#">Reports</a></li>
			<li><a href="#">Users</a></li>
			<li><a href="#">Media</a></li>
			<li><a href="#">Events</a></li>
			<li><a href="#">Newsletter</a></li>
			<li><a href="#">Settings</a></li>
		</ul>
	</footer>
	<!-- End of Animated footer -->

	<!-- Scroll to top link -->
	<a style="display: none;" id="totop">^ scroll to top</a>
        <script type="text/javascript" src="<?=$this->cdn('scripts');?>/hol/administry.js"></script>
    </body>
</html>