<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?php echo $this->headTitle(); ?>
	<!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link href="<?php echo $this->cdn('styles'); ?>/favicon.ico" rel="shortcut icon" type="image/ico" />
	<?php
	$this->headLink()
		->prependStylesheet($this->cdn('styles') . '/dist/css/skins/_all-skins.min.css')
		->prependStylesheet($this->cdn('styles') . '/dist/css/AdminLTE.min.css')
		->prependStylesheet('//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
		->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
		->prependStylesheet($this->cdn('styles') . '/bootstrap/css/bootstrap.min.css')
		->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
	
	?>
	<!-- Bootstrap 3.3.5 -->
	<!-- Font Awesome 4.4.0 -->
	<!-- Ionicons 2.0.1 -->
	<?php
    /**
     * Compress CSS and JS if it is enabled
     */ 
    echo $this->compressor('css');
	?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-yellow-light layout-top-nav">
	<div class="wrapper">
		<header class="main-header">
			<nav class="navbar navbar-static-top">
				<div class="container">
					<div class="navbar-header">
						<a href="<?php echo ROOT_URL; ?>" class="navbar-brand"><b>Hol</b>NP-BETA</a>
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                			<i class="fa fa-bars"></i>
              			</button>
					</div>
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<?php $auth = Zend_Auth::getInstance(); ?>
							<?php if ($auth->hasIdentity()) : ?>
							<li class="dropdown user user-menu">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<img src="<?php echo $this->userAvatar(); ?>" class="user-image" alt="User Image">
									<span class="hidden-xs"><?php echo $auth->getIdentity()->fullName; ?></span>
								</a>
								<ul class="dropdown-menu">
			                		<!-- User image -->
			                		<li class="user-header">
			                    		<img src="<?php echo $this->userAvatar(); ?>" class="img-circle" alt="User Image">
			                    		<p><?php echo $auth->getIdentity()->fullName; ?></p>
			                  		</li>
			                  		<!-- Menu Footer-->
			                  		<li class="user-footer">
			                    		<div class="pull-left">
			                      			<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/customer/user/edit/id/<?php echo $auth->getIdentity()->kopel; ?>" class="btn btn-default btn-flat">Profile</a>
			                    		</div>
			                    		<div class="pull-right">
			                      			<a href="<?php echo Pandamp_Application::getResource('identity')->logoutUrl.'/returnUrl/'.base64_encode("http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']); ?>" class="btn btn-default btn-flat">Sign out</a>
			                    		</div>
			                  		</li>	
								</ul>
							</li>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</nav>
		</header>
		<!-- Content Wrapper. Contains page content -->
      	<div class="content-wrapper">
      		<?php echo $this->layout()->content; ?>
      	</div><!-- /.content-wrapper -->
			
		<footer class="main-footer">
        	<div class="pull-right hidden-xs">
          		<b>Version</b> 2.3.0
        	</div>
        	<strong>&copy; 2015</strong>
      	</footer>
			
			
      	<!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
		<div style="position: fixed; height: auto;" class="control-sidebar-bg"></div>
	</div>

	<script src="<?php echo $this->cdn('scripts'); ?>/hol/pandamp/namespace.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jQuery-2.1.4.min.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQueryUI/jquery-ui.min.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jquery.iframe-transport.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jquery.fileupload.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jquery.json.min.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jquery.validate.min.js"></script>
	<!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $this->cdn('styles'); ?>/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->cdn('scripts'); ?>/plugins/validator.min.js"></script>
    <!-- FastClick -->
    <script src="<?php echo $this->cdn('scripts'); ?>/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="<?php echo $this->cdn('styles'); ?>/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="<?php echo $this->cdn('styles'); ?>/dist/js/demo.js"></script>
    <script src="<?php echo $this->cdn('scripts'); ?>/hol/jquery/jstree/jstree.js"></script>
	<?php
	/**
	 * Put all widget's javascript to the bottom of page 
	 */
	echo $this->compressor('js', 'bottomBody'); 
	?>
	
</body>
</html>