<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>CMS Hukumonline</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/adm/administry.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/style.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/pagination.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/jquery/dataTables/jquery.dataTables.min.js,hol/jquery/jquery.cookie.js,hol/jquery/tooltip/jquery.tipTip.min.js,hol/jquery/paging/jquery.pagination.js,hol/smooth.scroller.js,hol/jquery/form/jquery.validate.pack.js,adm/base64.js" ></script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->

        <style type="text/css">
            #message {
                display: none;
            }
        </style>

        <script type="text/javascript">
            var oTable;
            var oTable1;
            var oTable2;

            $(document).ready(function(){
                Administry.setup();

                /*
                oTable = $("#usermanagement").dataTable({
                    "iDisplayLength": 25
                    ,"aoColumns": [null, null,
                    null, null, null, { "bSortable": false}]
                });
                */

                oTable = $("#usermanagement").dataTable({
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "<?=ROOT_URL;?>/<?=$this->getLanguage();?>/api/user/getalluser"
                });

                oTable1 = $("#userinvoicelist").dataTable({
                    "iDisplayLength": 25
                    ,"aoColumns": [null, null,
                    null, null, null, null, { "bSortable": false}]
                });

                oTable2 = $("#userlog").dataTable({
                    "iDisplayLength": 25
                    ,"aaSorting": [[ 1, "desc" ]]
                });

                var validator = $("#edituser").validate({
                   rules:{
                       payment:{
                           digits:true
                           ,range:[1,12]
                       }
                       ,email:{
                           required: true,
                           email: true
                       }
                   }
                   ,messages:{
                       payment: {
                            digits: "Digits only",
                            range: "Value between {0} and {1}."
                        }
                   }
                    ,errorPlacement: function(error, element) {
                        error.insertAfter(element.parent().find('label:first'));
                    }
                    ,success: function(label){
                        label.html("&nbsp;").addClass("ok");
                    }

                });

                var cpasswd = $("#changepassword").validate({
                   rules:{
                        opasswd: "required",
                        newpasswd: "required",
                        rpasswd: {
                            required: true,
                            equalTo: "#newpasswd"
                        }
                   }
                   ,messages:{
                        opasswd: "Enter old password",
                        newpasswd: "Enter new password",
                        rpasswd: {
                            required: "Please provide a password",
                            equalTo: "Please enter the same password as above"
                        }
                   }
                    ,errorPlacement: function(error, element) {
                        error.insertAfter(element.parent().find('label:first'));
                    }
                    ,success: function(label){
                        label.html("&nbsp;").addClass("ok");
                    }

                });

                $('[name=reset]').live('click', function(){
                    var iId = $(this).attr('id');
                    $.post('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/reset/id/'+iId,function(){
                        $('#message').fadeIn("slow", function(){
                            $(this).html("Row "+iId+" Reset Password Successfully").delay(2000).fadeOut(1000);
                        });
                    });

                    return false;
                });

                $('[name=delass]').live('click', function(){

                    var iId = $(this).attr('id');

                    if (confirm("Are you sure?")) {
                        $.post('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/delass/id/'+iId,function(){
                            $('#row_'+iId).fadeOut("slow");
                            $('#message').fadeIn("slow", function(){
                                $(this).html("Row "+iId+" Deleted Successfully").delay(2000).fadeOut(1000);
                                window.location.reload();
                            });
                        }
                    )
                    }

                    return false;
                });
                $('[name=delete]').live('click', function(){
                    //var aData = oTable.fnGetData( this );
                    //var iId = aData[0];

                    var iId = $(this).attr('id');

                    if (confirm("Are you sure?")) {
                        $.post('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/delete/id/'+iId,function(){
                            $('#row_'+iId).fadeOut("slow");
                            $('#message').fadeIn("slow", function(){
                                $(this).html("Row "+iId+" Deleted Successfully").delay(2000).fadeOut(1000);
                                oTable.fnDraw();
                            });
                        }
                    )
                    }

                    return false;
                });
                $('[name=confirm]').live('click', function(){

                    var iId = $(this).attr('id');

                    $.ajax({
                       type: "POST",
                       dataType: 'json',
                       url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/invoice/confirm",
                       data: "id=" + iId,
                       success: function(response){
                            $('#message').fadeIn("slow", function(){
                                $(this).html(response.msg).delay(2000).fadeOut(1000);
                                oTable1.fnDraw();
                                window.location.reload();
                            });
                       }
                     });

                    return false;
                });
                $('[name=renew]').live('click', function(){

                    var iId = $(this).attr('id');

                    $.ajax({
                       type: "POST",
                       dataType: 'json',
                       url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/invoice/renew",
                       data: "id=" + iId,
                       success: function(response){
                            $('#message').fadeIn("slow", function(){
                                $(this).html(response.msg).delay(2000).fadeOut(1000);
                                oTable1.fnDraw();
                                window.location.reload();
                            });
                       }
                     });

                    return false;
                });
                $('[name=delete_invoice]').live('click', function(){

                    var iId = $(this).attr('id');

                    if (confirm("Are you sure?")) {
                    	
                    	if (confirm("Change the status of a member for free?")) {
                    		
	                        $.post('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/invoice/delete/change/y/id/'+iId,function(){
	                            $('#row_'+iId).fadeOut("slow");
	                            $('#message').fadeIn("slow", function(){
	                                $(this).html("Row "+iId+" Deleted Successfully").delay(2000).fadeOut(1000);
	                                oTable1.fnDraw();
	                            });
	                        })
                    		
                    	}
                    	else
                    	{
	                        $.post('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/invoice/delete/id/'+iId,function(){
	                            $('#row_'+iId).fadeOut("slow");
	                            $('#message').fadeIn("slow", function(){
	                                $(this).html("Row "+iId+" Deleted Successfully").delay(2000).fadeOut(1000);
	                                oTable1.fnDraw();
	                            });
	                        })
                    		
                    	}
                        
                    }

                    return false;
                });
                
                $('#ulog').change(function(){
                    checkValues = new Array();
                    a=0;
                    $("input.check_me:checked").each(function(){
                        checkValues[a]=$(this).val();
                        a++;
                    });

                    if(checkValues.length==0)
                    {
                        alert('NO CATALOG SELECTED');
                        $("#ulog").val(withSelected);
                        return false;
                    }

                    if ($("#ulog").val() == "deletelog")
                    {
	                    if (confirm("Are you sure?")) {
	                        $.post('<?=ROOT_URL;?>/<?=$this->getLanguage();?>/customer/user/deletelog/id/'+checkValues,function(){
	                            $('#message').fadeIn("slow", function(){
	                                $(this).html("Row "+checkValues+" Deleted Successfully").delay(2000).fadeOut(1000);
	                                window.location.reload();
	                            });
	                        }
	                    )
	                    }
                    	
                    }
                    
                    return false;
                });
                
                
            });
        </script>

    </head>
    <body>
        <?= $this->render("header-account-user.phtml"); ?>

	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper">

                    <?=$this->layout()->content;?>

		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper">
                <nav>
                    <a href="#">Dashboard</a> ·
                    <a href="#">Content</a> ·
                    <a href="#">Reports</a> ·
                    <a href="#">Users</a> ·
                    <a href="#">Media</a> ·
                    <a href="#">Events</a> ·
                    <a href="#">Newsletter</a> ·
                    <a href="#">Settings</a>
                </nav>
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->

	<!-- Animated footer -->
	<footer id="animated">
		<ul>
			<li><a href="#">Dashboard</a></li>
			<li><a href="#">Content</a></li>
			<li><a href="#">Reports</a></li>
			<li><a href="#">Users</a></li>
			<li><a href="#">Media</a></li>
			<li><a href="#">Events</a></li>
			<li><a href="#">Newsletter</a></li>
			<li><a href="#">Settings</a></li>
		</ul>
	</footer>
	<!-- End of Animated footer -->

	<!-- Scroll to top link -->
	<a style="display: none;" id="totop">^ scroll to top</a>
        <script type="text/javascript" src="<?=$this->cdn('scripts');?>/hol/administry.js"></script>
    </body>
</html>