<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<?php echo $this->headTitle(); ?>
	<!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link href="<?php echo $this->cdn('styles'); ?>/favicon.ico" rel="shortcut icon" type="image/ico" />
	<?php
	$this->headLink()
		->prependStylesheet($this->cdn('styles') . '/dist/css/AdminLTE.min.css')
		->appendStylesheet($this->cdn('scripts') . '/plugins/iCheck/square/blue.css')
		->prependStylesheet('//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
		->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
		->prependStylesheet($this->cdn('styles') . '/bootstrap/css/bootstrap.min.css');
	
	?>
	<!-- Bootstrap 3.3.5 -->
	<!-- Font Awesome 4.4.0 -->
	<!-- Ionicons 2.0.1 -->
	<?php
    /**
     * Compress CSS and JS if it is enabled
     */ 
    echo $this->compressor('css');
	?>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <style type="text/css">
	#wait{font-size:.885em;position:absolute;top:0;right:0;background:#F00;color:#003;padding:10px;}
	</style>
</head>
<body class="hold-transition login-page">
	<div id="wait"></div>
	<?php echo $this->layout()->content; ?>	

	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jQuery-2.1.4.min.js"></script>
	<script src="<?php echo $this->cdn('scripts'); ?>/plugins/jQuery/jquery.validate.min.js"></script>
	<!-- Bootstrap 3.3.5 -->
    <script src="<?php echo $this->cdn('styles'); ?>/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->cdn('scripts'); ?>//plugins/iCheck/icheck.min.js"></script>
	<?php
	/**
	 * Put all widget's javascript to the bottom of page 
	 */
	echo $this->compressor('js', 'bottomBody'); 
	?>
	
</body>
</html>