<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>CMS Hukumonline</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/adm/administry.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/adm/style.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/pagination.css" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/jquery/jquery.cookie.js,hol/jquery/tooltip/jquery.tipTip.min.js,hol/jquery/form/jquery.validate.pack.js,hol/jquery/paging/jquery.pagination.js,hol/smooth.scroller.js" ></script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->

        <style type="text/css">
            #message {
                display: none;
            }
        </style>

        <script type="text/javascript">
            $(document).ready(function(){
                $("a[title], div[title], span[title]").tipTip();

                var isFirstTime = 1;

                var myPageIndex = 0;
                var itemsPerPage = 25;
                var currentQuery = $("#sQuery").val();
                var withSelected = "<?=$this->withSelected;?>";
                var relatedGuid = "<?=$this->relatedGuid;?>";

                var tmpCurrentPage = $("#nOffset").val()/itemsPerPage;

                $("#catalogRelatePagination").pagination(<?=$this->hits->response->numFound;?>,
                {items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPage}
                );

                function handlePaginationClick(new_page_index, pagination_container)
                {
                    if(!isFirstTime)
                    {
                        myPageIndex = new_page_index;
                        myStart = (itemsPerPage * myPageIndex);
			$("#nOffset").val(myStart);
			$("#sQuery").val(currentQuery);
			$("#frmSearchRelation").submit();

                    }
                    isFirstTime = 0;
                    return false;
                }

                $('input#sQuery').bind('keypress', function(e) {
                    if(e.keyCode==13){
                        // Enter pressed... do anything here...
                        $("#nOffset").val(0);
                        $("#frmSearchRelation").submit();
                        return false;
                    }
                });
                $('input#btnGoSearch').bind('click', function(e) {
                    $("#nOffset").val(0);
                    $("#frmSearchRelation").submit();
                    return false;
                });

                $("input[name=select_deselect]").click(function(){
                     var checked_status = this.checked;
                     $("input[class=check_me]").each(function(){
                         this.checked = checked_status;
                     });
                });

                $('#relate').change(function(){
                    checkValues = new Array();
                    a=0;
                    $("input.check_me:checked").each(function(){
                        checkValues[a]=$(this).val();
                        a++;
                    });

                    if(checkValues.length==0)
                    {
                        alert('NO CATALOG SELECTED');
                        $("#relate").val(withSelected);
                        return false;
                    }

                    if(this.value != '')
                    {
                        if(confirm ('Are you sure to relate this?'))
                        {
                            $.ajax({
                               type: "POST",
                               dataType: 'json',
                               url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/relation/new",
                               data: "relatedGuid=" + relatedGuid + "&relateAs=" + this.value + "&guid[]=" + checkValues,
                               beforeSend: function()
                               {
                                    $('#spinner').show();
                               },
                               success: function(response){
                                    $('#spinner').hide();
                                    $('#message').fadeIn("slow", function(){
                                        $(this).html("Row " + checkValues + " " + response.msg).delay(2000).fadeOut(1000);
                                    });
                               }
                             });
                        }
                    }
                    return false;
                });


            });

        </script>

    </head>
    <body>
        <?= $this->render("header-dms-catalog.phtml"); ?>

	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper">

                    <?=$this->layout()->content;?>

		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper">
                <nav>
                    <a href="#">Dashboard</a> ·
                    <a href="#">Content</a> ·
                    <a href="#">Reports</a> ·
                    <a href="#">Users</a> ·
                    <a href="#">Media</a> ·
                    <a href="#">Events</a> ·
                    <a href="#">Newsletter</a> ·
                    <a href="#">Settings</a>
                </nav>
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->

	<!-- Animated footer -->
	<footer id="animated">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Content</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Users</a></li>
            <li><a href="#">Media</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Newsletter</a></li>
            <li><a href="#">Settings</a></li>
        </ul>
	</footer>
	<!-- End of Animated footer -->

    </body>
</html>