<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?php echo $this->headTitle(); ?>
        <link href="<?php echo $this->cdn('styles'); ?>/favicon.ico" rel="shortcut icon" type="image/ico" />

	    <?php 
	    $this->headLink()
	    	->prependStylesheet($this->cdn('styles') . '/adm/administry.css')
			->prependStylesheet($this->cdn('styles') . '/adm/style.css');
	    	
		$this->headScript()
	    	->prependFile($this->cdn('scripts') . '/hol/pandamp/namespace.js')
	    	->prependFile($this->cdn('scripts') . '/hol/jquery/jquery.js')
	    	->appendFile($this->cdn('scripts') . '/hol/jquery/jquery.cookie.js')
	    	->appendFile($this->cdn('scripts') . '/hol/jquery/wysiwyg/jquery.wysiwyg.min.js')
	    	->appendFile($this->cdn('scripts') . '/hol/jquery/tooltip/jquery.tipTip.min.js')
	    	->appendFile($this->cdn('scripts') . '/hol/jquery/form/jquery.validate.pack.js')
	    	->appendFile($this->cdn('scripts') . '/hol/jquery/form/jquery.form.js')
	    	->appendFile($this->cdn('scripts') . '/hol/jquery/nyroModal/jquery.nyroModal.pack.js');
	    ?>
	    
	    <?php
	    /**
	     * Compress CSS and JS if it is enabled
	     */ 
	    echo $this->compressor('css');
	    echo $this->compressor('js');
	    ?>
		
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->cdn('styles'); ?>/ie.css"/>

        <script src="<?php echo $this->cdn('scripts'); ?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?php echo $this->cdn('scripts'); ?>/hol/IE8.js"></script>

        <![endif]-->

        <style>
            #galleryLoading {
                width: 100%;
                position: absolute;
            }
            #pagination
            {
                text-align:center;
                margin-left:105px;
            }
            #pagination li
            {
                list-style: none;
                float: left;
                margin-right: 16px;
                padding:5px;
                border:solid 1px #dddddd;
                color:#0063DC;
            }
            #pagination li:hover
            {
                color:#FF0084;
                cursor: pointer;
            }

        </style>

        <script type="text/javascript">
            $(document).ready(function(){
                $("a[title], div[title], span[title]").tipTip();
                
                $("input[name=select_deselect]").click(function(){
                     var checked_status = this.checked;
                     $("input[class=check_me]").each(function(){
                         this.checked = checked_status;
                     });
                });

                $('.historynew').click(function(e){
                	e.preventDefault();
                    var elem = $(this);
                    if(confirm ('Are you sure ?')) {
                    	$.ajax({
                    		type:"post"
                    		,url:"<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/api/relation/deletehistory"
                    		,data: "itemGuid="+ elem.attr('data-historyid') + "&relatedGuid="+ elem.attr('data-guid') +"&relateAs="+ elem.attr('data-status')
                    		,beforeSend: function() {
                    			displayLoad();
                    		}
                			,success: function() {
                				elem.html("Data has been deleted successfully");
                				setTimeout(function() {
               					 location.reload()
               					  },1000);
                			}		
                    	});    
                    }
                });

                $('#ws').change(function(){
                     checkValues = new Array();
                     a=0;
                     $("input.check_me:checked").each(function(){
                         checkValues[a]=$(this).val();
                         a++;
                     });

                    if ($("#ws").val() == "delete")
                    {
                        if(checkValues.length==0)
                        {
                            alert('NO CATALOG SELECTED');
                            $("#ws").val("withselected");
                            return false;
                        }
                        else
                        {
                            if(confirm ('Are you sure ?'))
                            {
                                var parent = $(this).parent();
                                $.ajax({
                                    type:"post"
                                    ,url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/catalog/delete"
                                    ,data: "guid=" + checkValues
                                    ,beforeSend: function()
                                    {
                                        $('#row_'+checkValues).empty().fadeOut('slow').append('<p id="loading">&nbsp;</p>');
                                    }
                                    ,success: function()
                                    {
                                        $('#row_'+checkValues).fadeOut("slow");
                                        $("input.check_me:checked").each(function(){
                                            $(this).parent().parent().remove();
                                        });
                                    }
                                }
                                );
                            }

                        }

                        return false;

                    }
                    else if ($("#ws").val() == "recycle")
                    {
                        if(checkValues.length==0)
                        {
                            alert('NO CATALOG SELECTED');
                            $("#ws").val("withselected");
                            return false;
                        }
                        else
                        {

                    	if (confirm ("Recycle, are you sure ?"))
                    	{
                                var parent = $(this).parent();
                                $.ajax({
                                    type:"post"
                                    ,url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/catalog/recycle"
                                    ,data: "guid=" + checkValues
                                    ,beforeSend: function()
                                    {
                                        $('#row_'+checkValues).empty().fadeOut('slow').append('<p id="loading">&nbsp;</p>');
                                    }
                                    ,success: function()
                                    {
                                        $('#row_'+checkValues).fadeOut("slow");
                                        $("input.check_me:checked").each(function(){
                                            $(this).parent().parent().remove();
                                        });
                                    }
                                }
                                );
                    	}
                    	
                        }
                    }
                    else if ($("#ws").val() == "restore")
                    {
                    	                        if(checkValues.length==0)
                        {
                            alert('NO CATALOG SELECTED');
                            $("#ws").val("withselected");
                            return false;
                        }
                        else
                        {

                    	$("#display_status").show("slow").fadeIn("slow");
                        }
                    }

                });
                
                $('#go').click(function(){
                    	if (confirm ("Restore, are you sure ?"))
                    	{
                                var parent = $(this).parent();
                                var stat = $("#sta").val();
                                $.ajax({
                                    type:"post"
                                    ,url:"<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/catalog/restore"
                                    ,data: "guid=" + checkValues + "&status=" + stat
                                    ,beforeSend: function()
                                    {
                                        $('#row_'+checkValues).empty().fadeOut('slow').append('<p id="loading">&nbsp;</p>');
                                    }
                                    ,success: function()
                                    {
                                        $('#row_'+checkValues).fadeOut("slow");
                                        $("input.check_me:checked").each(function(){
                                            $(this).parent().parent().remove();
                                        });
                                    }
                                }
                                );
                    		
                    	}
					
				});
				
            });

        </script>

    </head>
    <body>
        <?= $this->render("header-dms-catalog.phtml"); ?>

	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper">
			<?=$this->layout()->content;?>
		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper">
                <nav>
                    <a href="#">Dashboard</a> ·
                    <a href="#">Content</a> ·
                    <a href="#">Reports</a> ·
                    <a href="#">Users</a> ·
                    <a href="#">Media</a> ·
                    <a href="#">Events</a> ·
                    <a href="#">Newsletter</a> ·
                    <a href="#">Settings</a>
                </nav>
                <p>.:CMS Hukumonline:.</p>
            </div>
	</footer>
	<!-- End of Page footer -->

	<!-- Animated footer -->
	<footer id="animated">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Content</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Users</a></li>
            <li><a href="#">Media</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Newsletter</a></li>
            <li><a href="#">Settings</a></li>
        </ul>
	</footer>
	<!-- End of Animated footer -->

    </body>
</html>