<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <a href="javascript:history.back();">Back to Origin Page</a>
            <fieldset>
                <legend>Location:</legend>
                <?php echo $this->widget2->render(); ?>
            </fieldset>
            <fieldset>
                <legend>Data Center</legend>
                <h4><?php echo $this->catalogTitle; ?></h4>
                <h6><?php echo $this->catalogSubTitle; ?></h6>
            </fieldset>
            <form id="frmSearchRelation" name="frmSearchRelation" method="GET">
                <input id="sQuery" name="sQuery" class="half" value='<?php echo $this->sQuery; ?>'>
                <input type="hidden" id="nLimit" name="nLimit" value="25">
                <input type="hidden" id="nOffset" name="nOffset" value="<?php echo $this->nOffset; ?>">
                <input type="hidden" id="relatedGuid" name="relatedGuid" value="<?php echo $this->relatedGuid; ?>">
                <input type="submit" id="btnGoSearch" value="Search" class="btn btn-blue big" />
            </form>
            <h5>Search Result: <?php echo $this->hits->response->numFound; ?> Record(s)</h5>
            <div id="spinner" style="color:red; display:none;"><img src="<?php echo $this->cdn('images'); ?>/index.gif" border="0"> Sending Request</div>
            <div class="box box-success" id="message"></div>
            <form id="frmCatalogRelation" name="frmCatalogRelation" method="post">
                <div class="align-right">
                <select id="relate" name="relate">
                    <option value="">Relate As:</option>
                    <option value="RELATED_OTHER">Item</option>
                    <option value="RELATED_Clinic">Clinic</option>
                    <option value="RELATED_HISTORY">History</option>
                    <option value="RELATED_ISSUE">Hot Issue</option>
                    <option value="RELATED_BASE">Legal Basis</option>
                    <option value="RELATED_PP">Peraturan Pelaksana</option>
                    <option value="RELATED_TRANSLATION_ID">Indonesian Translation</option>
                    <option value="RELATED_TRANSLATION_EN">English Translation</option>
                    <option value="REPEAL">Mencabut Peraturan</option>
                    <option value="AMEND">Merubah Peraturan</option>
                    <option value="ESTABLISH">Menetapkan Peraturan</option>
                    <option value="ISROOT">Is ROOT</option>
                </select>
                </div>
                <div style="display:none"></div>
                <table class="display stylized" id="catalogrelation">
                    <thead>
                        <tr>
                            <th><input name="select_deselect" value="1" type="checkbox"></th>
                            <th>Title</th>
                            <th>Section</th>
                            <th>Published</th>
                            <th>Created on</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->hits->response->docs as $hit) { ?>
                        <tr>
                            <td><input type='checkbox' name='catalogGuid[]' id='catalogGuid' value='<?php echo $hit->id; ?>' class="check_me"></td>
                            <td>
                                <?php if($hit->profile == 'kutu_doc') { ?>
                                    <a href="<?php echo ROOT_URL; ?>/browser/downloadfile/guid/<?php echo $hit->id; ?>"><div class="searchResultTitle">File: <?php try { echo $hit->title.' ['.$hit->id.']'; } catch (Exception $e) { echo ''; } ?></div></a>
                                <?php } else { ?>
                                    <a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/dms/catalog/detail/guid/<?php echo $hit->id; ?>/node/<?php echo $this->currentNode; ?>" title="<?php echo $hit->subTitle; ?>"><?php try { echo $hit->title; } catch (Exception $e) { echo 'No-Title'; } ?></a>
                                <?php } ?>
                                <br><small>id:<?php echo $hit->id; ?> - by: <?php echo $hit->createdBy; ?>&nbsp;<span class="subtitle"><?php echo $hit->publishedDate; ?></span></small>
                            </td>
                            <td><?php echo $hit->profile; ?></td>
                            <td>
                                <?php
                                $now = date('Y-m-d H:i:s');
                                $t = str_replace("Z", "", $hit->publishedDate);
                                $d = explode("T", $t);
                                $publishedDate = $d[0].' '.$d[1];

                                $et = str_replace("Z", "", $hit->expiredDate);
                                $ed = explode("T", $et);
                                $expiredDate = $ed[0].' '.$ed[1];
                                if ($expiredDate == "1999-12-31 00:00:00") $expiredDate = '0000-00-00 00:00:00';

                                if ($now <= $publishedDate && $hit->status == 99) {
                                    $status = "publish_y";
                                    $ht = "Published, but is Pending";
                                }
				else if (($now <= $expiredDate || $expiredDate == '0000-00-00 00:00:00') && $hit->status == 99) {
                                    $status = "publish_g";
                                    $ht = "Published and is Current";
				}
				else if ($now > $expiredDate && $hit->status == 99) {
                                    $status = "publish_r";
                                    $ht = "Published, but has Expired";
				}
				else if ($hit->status == 0) {
                                    $status = "publish_x";
                                    $ht = "Not Published";
				}
				else if ($hit->status == -1) {
                                    $status = "disabled";
                                    $ht = "Archived";
				}
                                ?>

                                <div class="ta-center" title="<?php echo $ht; ?>">
                                    <img src="<?php echo $this->baseUrl(); ?>/resources/images/silk/icons/<?php echo $status; ?>.png">
                                </div>
                            </td>
                            <td nowrap>
                                <?php echo date('d.m.y H:i:s',strtotime($hit->createdDate)); ?><br>
                                <small>modifiedBy: <?php echo $hit->modifiedBy; ?></small>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </form>
            <table width='100%'>
            <tr>
                <td align=right><div id='catalogRelatePagination' class="pagination"></div></td>
            </tr>
            </table>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div>
</aside>
<!-- End of Right column/section -->