<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>
            <h3>Site: <a href="http://<?=$tag;?>" target="_blank" title="DMS <?=$tag;?>"><?=$tag;?></a></h3>
            <a href="javascript:history.back();">Back to Origin Page</a>
            <fieldset>
                <legend>Location:</legend>
                <?=$this->widget2->render();?>
            </fieldset>
            <fieldset>
                <legend>Data Center</legend>
                <h4><?=$this->catalogTitle;?></h4>
                <h6><?=$this->catalogSubTitle;?></h6>
            </fieldset>
            <form id="frmSearchRelation" name="frmSearchRelation" method="GET">
                <input id="sQuery" name="sQuery" class="half" value='<?=$this->sQuery;?>'>
                <input type="hidden" id="nLimit" name="nLimit" value="25">
                <input type="hidden" id="nOffset" name="nOffset" value="<?echo $this->nOffset;?>">
                <input type="hidden" id="relatedGuid" name="relatedGuid" value="<?echo $this->relatedGuid;?>">
                <input type="submit" id="btnGoSearch" value="Search" class="btn btn-blue big" />
            </form>
            <h5>Search Result: <?=$this->hits->response->numFound;?> Record(s)</h5>
            <div id="spinner" style="color:red; display:none;"><img src="<?=$this->cdn('images');?>/index.gif" border="0"> Sending Request</div>
            <div class="box box-success" id="message"></div>
            <form id="frmCatalogRelation" name="frmCatalogRelation" method="post">
                <div class="align-right">
                <select id="relate" name="relate">
                    <option value="">Relate As:</option>
                    <option value="RELATED_OTHER">Item</option>
                    <option value="RELATED_CLINIC">Clinic</option>
                    <option value="RELATED_HISTORY">History</option>
                    <option value="RELATED_ISSUE">Hot Issue</option>
                    <option value="RELATED_BASE">Legal Basis</option>
                    <option value="RELATED_TRANSLATION">Translation</option>
                </select>
                </div>
                <div style="display:none"></div>
                <table class="display stylized" id="catalogrelation">
                    <thead>
                        <tr>
                            <th><input name="select_deselect" value="1" type="checkbox"></th>
                            <th>Title</th>
                            <th>Section</th>
                            <th>Published</th>
                            <th>Created on</th>
                        </tr>
                    </thead>
                    <tbody>
                    <? for($ii=0;$ii<$this->numberOfRows;$ii++) { $hit = $this->hits->response->docs[$ii]; ?>
                        <tr>
                            <td><input type='checkbox' name='catalogGuid[]' id='catalogGuid' value='<?=$hit->id;?>' class="check_me"></td>
                            <td>
                                <? if($hit->profile == 'kutu_doc'){?>
                                    <a href="<?=ROOT_URL;?>/browser/downloadfile/guid/<?=$hit->id;?>"><div class="searchResultTitle">File: <?php try {echo $hit->title.' ['.$hit->id.']';} catch (Exception $e) {echo '';}?></div></a>
                                <? } else { ?>
                                    <a href="<?=ROOT_URL;?>/<?=$this->getLanguage();?>/dms/catalog/detail/guid/<?=$hit->id;?>/node/<?=$this->currentNode;?>" title="<?=$hit->subTitle;?>"><?php try {echo $hit->title;} catch (Exception $e) {echo 'No-Title';}?></a>
                                <? } ?>
                                <br><small>id:<?=$hit->id;?> - by: <?=$hit->createdBy;?>&nbsp;<span class="subtitle"><?=$hit->publishedDate;?></span></small>
                            </td>
                            <td><?=$hit->profile;?></td>
                            <td>
                                <?
                                $now = date('Y-m-d H:i:s');
                                $t = str_replace("Z", "", $hit->publishedDate);
                                $d = explode("T", $t);
                                $publishedDate = $d[0].' '.$d[1];

                                $et = str_replace("Z", "", $hit->expiredDate);
                                $ed = explode("T", $et);
                                $expiredDate = $ed[0].' '.$ed[1];
                                if ($expiredDate == "1999-12-31 00:00:00") $expiredDate = '0000-00-00 00:00:00';

                                if ($now <= $publishedDate && $hit->status == 99) {
                                    $status = "publish_y";
                                    $ht = "Published, but is Pending";
                                }
				else if (($now <= $expiredDate || $expiredDate == '0000-00-00 00:00:00') && $hit->status == 99) {
                                    $status = "publish_g";
                                    $ht = "Published and is Current";
				}
				else if ($now > $expiredDate && $hit->status == 99) {
                                    $status = "publish_r";
                                    $ht = "Published, but has Expired";
				}
				else if ($hit->status == 0) {
                                    $status = "publish_x";
                                    $ht = "Not Published";
				}
				else if ($hit->status == -1) {
                                    $status = "disabled";
                                    $ht = "Archived";
				}
                                ?>

                                <div class="ta-center" title="<?=$ht;?>">
                                    <img src="<?=$this->baseUrl();?>/resources/images/silk/icons/<?=$status;?>.png">
                                </div>
                            </td>
                            <td nowrap>
                                <?=date('d.m.y H:i:s',strtotime($hit->createdDate));?><br>
                                <small>modifiedBy: <?=$hit->modifiedBy;?></small>
                            </td>
                        </tr>
                    <? } ?>
                    </tbody>
                </table>
            </form>
            <table width='100%'>
            <tr>
                <td align=right><div id='catalogRelatePagination' class="pagination"></div></td>
            </tr>
            </table>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?=$this->action('sidebar','user','customer');?>
    </div>
</aside>
<!-- End of Right column/section -->
