<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>

            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <h5>Hukumonline Polling</h5>
            <section>
                <ul>
                <?php foreach($this->rowPoll as $row) { ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/polling/election/whos/id/<?php echo $row->guid; ?>"><?php echo $row->title; ?></a></li>
                <?php } ?>
                </ul>
            </section>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div><br>
    <div id="showDiv1" style="width:100%;text-align:center;">
    <?php echo $this->action('browse','manager','agenda'); ?>
    </div>
    <?php echo $this->action('view','manager','polling'); ?>
</aside>
<!-- End of Right column/section -->

