<!-- Left column/section -->
<section class="column width6 first">

    <div class="colgroup leading">
        <div class="column width6 first">
            <?php
            if ($this->getLanguage() == 'id')
                $tag = "www.hukumonline.com";
            else
                $tag = "en.hukumonline.com";
            ?>

            <h3>Site: <a href="http://<?php echo $tag; ?>" target="_blank" title="DMS <?php echo $tag; ?>"><?php echo $tag; ?></a></h3>
            <div class="align-left">
                <h5>Hukumonline Polling:</h5>
            </div>
            <div class="align-right">
                <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/polling/election/new" class="btn"><span class="icon icon-add">&nbsp;</span>Add New</a>
                <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->getLanguage(); ?>/polling/election/delete/id/<?php echo $this->pollId; ?>" class="btn"><span class="icon icon-cancel">&nbsp;</span>Delete</a>
            </div>
            <div style="clear:both;">&nbsp;</div>
            <div id="poll-container"></div>
            <script type="text/javascript">
            var total_votes = 0;
            var percent;
            var votedID = '<?php echo $this->pollId; ?>';

            function animateResults(){
              $("#poll-results div").each(function(){
                  var percentage = $(this).next().text();
                  $(this).css({width: "0%"}).animate({
                                            width: percentage}, 'slow');
              });
            }

            <?php
                    $queryAttr="SELECT * FROM options WHERE pollGuid ='".$this->pollId."'";
                    $db = Zend_Db_Table::getDefaultAdapter()->query($queryAttr);
                    $rowset = $db->fetchAll(Zend_Db::FETCH_OBJ);

                    foreach ($rowset as $row) {
            ?>

                            total_votes = total_votes+parseInt(<?php echo $row->hits; ?>);

            <?php } ?>

            var results_html = "<span class='barjudul'><?php echo $this->rowPoll->title; ?><br></span><div id='poll-results'><h4>Hasil :</h4><dl class='graph'>";

            <?php foreach ($rowset as $row) { ?>
                    percent = Math.round((parseInt(<?php echo $row->hits; ?>)/parseInt(total_votes))*100);
                    if ('<?php echo $row->guid; ?>' !== votedID) {
                            results_html = results_html+"<dt class='bar-title'><?php echo $row->text; ?></dt><dd class='bar-container'><div id='bar<?php echo $row->guid; ?>'style='width:0%;'>&nbsp;</div><strong>"+percent+"%</strong></dd>\n";
                    }
                    else
                    {
                            results_html = results_html+"<dt class='bar-title'><?php echo $row->text; ?></dt><dd class='bar-container'><div id='bar<?php echo $row->guid; ?>'style='width:0%;background-color:#0066cc;'>&nbsp;</div><strong>"+percent+"%</strong></dd>\n";
                    }
            <?php } ?>

            results_html = results_html+"</dl><p>Total Votes: "+total_votes+"</p></div>";

            $("#poll-container").append(results_html).fadeIn("slow",function(){
                    animateResults();
            });
            </script>
        </div>
    </div>


    <div class="clear">&nbsp;</div>

</section>
<!-- End of Left column/section -->

<!-- Right column/section -->
<aside class="column width2">
    <div id="rightmenu">
        <?php echo $this->action('sidebar','user','customer'); ?>
    </div><br>
    <div id="showDiv1" style="width:100%;text-align:center;">
    <?php echo $this->action('browse','manager','agenda'); ?>
    </div>
    <?php echo $this->action('view','manager','polling'); ?>
</aside>
<!-- End of Right column/section -->

