<!-- Main content -->
<section class="content">
	<!-- Info boxes -->
	<div class="row">
		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<div style="padding:10px;margin-left:10px">
					<span class="info-box-text">Log Request</span>
					<span class="info-box-number" id="logreq"></span>
				</div>
			</div>
			
		</div>
		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<div style="padding:10px;margin-left:10px">
					<span class="info-box-text">Today's Request</span>
					<span class="info-box-number" id="todayreq"></span>
					<span style="font-size:11px;">/ Day</span>
				</div>
			</div>
			
		</div>
		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<span style="padding:8px;margin-right:5px;display:block;float:left;width:90px;background:rgba(0,0,0,0.2);line-height:37px;">
					<small>desktop:</small><span id="percen-desktop"></span><br>
					<small>mobile:</small><span id="percen-mobile"></span>
				</span>
				<div style="padding:10px;margin-left:10px">
					<span class="info-box-text">Live Request</span>
					<span class="info-box-number" id="livereq"></span>
					<span style="font-size:11px;">/ Minute</span>
				</div>
			</div>
			
		</div>
		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<div style="padding:10px;margin-left:10px">
					<span class="info-box-text">Customer Request</span>
					<span class="info-box-number" id="custreq"></span>
					<span style="font-size:11px;">/ Day</span>
				</div>
			</div>
			
		</div>
		
		
	</div>
	<div class="row">
		<div class="col-md-6">
			<ul class="timeline" id="timeline"></ul>
		</div>
		<div class="col-md-6">
			<div class="nav-tabs-custom">
				<ul class="nav nav-tabs pull-right">
					<li><a href="#clickYesterday" data-toggle="tab">Kemarin</a></li>
					<li class="active"><a href="#clickToday" data-toggle="tab">Hari ini</a></li>
					<li class="pull-left header">Klik</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane" id="clickYesterday">
						<table class="table table-striped">
                           	<tr>
                                <th style="width: 90%">URL</th>
                            	<th>Jumlah</th>
							</tr>
                        </table>
					</div>
					<div class="tab-pane active" id="clickToday">
						<table class="table table-striped">
							<tr>
								<th style="width: 90%">URL</th>
								<th>Jumlah</th>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<div class="nav-tabs-custom">
				<ul class="nav nav-tabs pull-right">
					<li><a href="#searchYesterday" data-toggle="tab">Kemarin</a></li>
					<li class="active"><a href="#searchToday" data-toggle="tab">Hari ini</a></li>
					<li class="pull-left header">Website referral</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane" id="searchYesterday">
						<table class="table table-striped">
                           	<tr>
                                <th style="width: 90%">Referral</th>
                            	<th>Jumlah</th>
							</tr>
                        </table>
					</div>
					<div class="tab-pane active" id="searchToday">
						<table class="table table-striped">
							<tr>
								<th style="width: 90%">Referral</th>
								<th>Jumlah</th>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>