<!-- Main content -->
<section class="content">
	<!-- Info boxes -->
	<div class="row">
		<div class="col-md-3 col-sm-6 col-xs-12">
			<div class="info-box">
				<div style="padding:10px;margin-left:10px">
					<span class="info-box-text">Log Request</span>
					<span class="info-box-number" id="logreq"></span>
				</div>
			</div>
			
		</div>
		
		
	</div>
	<div class="row">
		<div class="col-md-8">
			<ul class="timeline" id="timeline"></ul>
		</div>
	</div>
</section>