<li>
	<?php if (isset($this->reqlog->kopel)) : ?>
	<?php
	$rowUser = App_Model_Show_User::show()->getUserById($this->reqlog->kopel);
	$topInfo = '<a href="#">'.$rowUser['fullName'].'</a>'.' <small>'.$this->reqlog->ip.'</small>';
	?>
	<i class="fa fa-user bg-aqua"></i>
	<?php elseif (isset($this->reqlog->bot)) : ?>
	<?php
	$topInfo = '<a href="#">'.$this->reqlog->ip.'</a>'.' <small>'.$this->reqlog->bot.'</small>';
	?>
	<i class="fa fa-exchange bg-yellow"></i>
	<?php else : ?>
	<?php
	$topInfo = '<a href="#">'.$this->reqlog->ip.'</a>';
	?>
	<i class="fa fa-road bg-blue"></i>
	<?php endif; ?>
	<div class="timeline-item">
		<span class="time"><i class="fa fa-clock-o"></i> <?php echo date("H:i:s",strtotime($this->reqlog->access_time)); ?></span>
		<h3 class="timeline-header"><a href="#"><?php echo $topInfo; ?></a></h3>
		<div class="timeline-body">
		<?php
		$furl = $this->reqlog->full_url;
		$url = pathinfo($furl);
		$guid = basename($url['dirname']);
		$catalogDb = App_Model_Show_Catalog::show()->getCatalogByGuid($guid);
		?>
		<?php if ($catalogDb) : ?>
		<?php
		if ($catalogDb['profileGuid'] == 'klinik')
			$title = App_Model_Show_CatalogAttribute::show()->getCatalogAttributeValue($guid,'fixedCommentTitle'); 
		else
			$title = App_Model_Show_CatalogAttribute::show()->getCatalogAttributeValue($guid,'fixedTitle'); 
		?>
		<a href="<?php echo $furl; ?>"><?php echo $title; ?></a>
		<?php else : ?>
		<?php echo $furl; ?>
		<?php endif; ?>
		</div>
		<div class="timeline-footer">
			<span class="label label-primary"><?php echo $this->reqlog->browser; ?></span>
			<span class="label label-primary"><?php echo $this->reqlog->version; ?></span>
			<span class="label label-primary"><?php echo $this->reqlog->platform; ?></span>
		</div>
	</div>
</li>
