<?php if (count($this->aData) > 0) : ?>
<li class="treeview active">
	<a href="#">
		<i class="fa fa-files-o"></i>
		<span>
		<?php if ($this->getLanguage() == "id") : ?>
		KATEGORI KLINIK
		<?php else : ?>
		CLINIC CATEGORY
		<?php endif; ?>
		</span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<?php for($i=0; $i<count($this->aData);$i++) : ?>
		<li <?php if($this->kategoriklinik=="\"".$this->getCatalogAttribute($this->aData[$i]['profile'],'fixedTitle')."\"" or ($this->kategoriklinik == "no_categori" and $this->aData[$i]['profile'] == "_empty_")){ ?> class="active" <?php } ?>>
			<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=<?php echo str_replace(" ", "+", $this->query); ?>&kategoriklinik=%22<?php echo str_replace("&", "%26", $this->getCatalogAttribute($this->aData[$i]['profile'],'fixedTitle')); ?>%22&category=klinik&clinic_selected=1" id="fcClinic"><?php echo $this->getCatalogAttribute($this->aData[$i]['profile'],'fixedTitle'); ?>
			&nbsp;<small class="label label-primary pull-right"><?php echo $this->aData[$i]['count']; ?></small></a>
		</li>
		<?php endfor; ?>
	</ul>
</li>
<?php endif; ?>