<?php if (count($this->aData) > 0) : ?>
<li class="treeview active">
	<a href="#">
		<i class="fa fa-files-o"></i>
		<span>
		BERDASARKAN TAHUN
		</span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<li>
		<?php
		$c = 0;
		$breaker = 2;
		?>
		<?php for($i=0; $i<count($this->aData);$i++) : ?>
		<?php 
if ($c == 0 || $c%$breaker == 0) {
        ?><div class="row" style="padding-left: 15px;line-height:28px"><?php
    } ?>
		        <div class="col-md-4">
			<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=<?php echo str_replace(" ", "+", $this->query); ?>&year=<?php echo $this->aData[$i]['profile'];?>&category=(kutu_peraturan_kolonial OR kutu_rancangan_peraturan OR kutu_peraturan)&sort=fixedDate&order=desc" id="fcHold"><?php echo $this->aData[$i]['profile']; ?>
			&nbsp;<small class="label bg-yellow"><?php echo $this->aData[$i]['count']; ?></small></a>
			</div>
<?php

    $c++;
    if ($c%$breaker == 0) {
        ?></div><?php
    } ?>
		
		<?php endfor; ?>
		</li>
	</ul>
</li>
<?php endif; ?>