<?php if (count($this->aData) > 0) : ?>
<li class="treeview active">
	<a href="#">
		<i class="fa fa-files-o"></i>
		<span>
		<?php if ($this->getLanguage() == "id") : ?>
		JENIS DOKUMEN
		<?php else : ?>
		CATEGORY
		<?php endif; ?>
		</span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<?php for($i=0; $i<count($this->aData);$i++) : ?>
		<li <?php if($this->category==$this->aData[$i]['profile'] && $this->clinic_selected != 1 && $this->putusanSelected != 1){ ?> class="active" <?php } ?>>
			<?php if (in_array($this->aData[$i]['profile'], array('kutu_peraturan_kolonial','kutu_rancangan_peraturan','kutu_peraturan'))) { ?>
			<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=<?php echo str_replace(" ", "+", $this->query); ?>&category=<?php echo str_replace("&", "%26", $this->aData[$i]['profile']); ?>&sort=fixedDate&order=desc" id="fcProfile"><?php echo ucfirst($this->aData[$i]['facet']); ?>
			<?php } else { ?>
			<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=<?php echo str_replace(" ", "+", $this->query); ?>&category=<?php echo str_replace("&", "%26", $this->aData[$i]['profile']); ?>" id="fcProfile"><?php echo ucfirst($this->aData[$i]['facet']); ?>
			<?php } ?>
			&nbsp;<small class="label pull-right bg-red"><?php echo $this->aData[$i]['count']; ?></small></a>
		</li>
		<?php endfor; ?>
	</ul>
</li>
<?php endif; ?>