<?php if (count($this->aData) > 0) : ?>
<li class="treeview">
	<a href="#">
		<i class="fa fa-files-o"></i>
		<span>
		PEMBUAT ARTIKEL
		</span>
		<i class="fa fa-angle-left pull-right"></i>
	</a>
	<ul class="treeview-menu">
		<?php for($i=0; $i<count($this->aData);$i++) : ?>
		<li>
			<a href="<?php echo ROOT_URL; ?>/<?php echo $this->getLanguage(); ?>/search/dms/browse?q=<?php echo str_replace(" ", "+", $this->query); ?>&createdBy=<?php echo $this->aData[$i]['profile']; ?>" id="fcAuthor">
			<?php echo $this->aData[$i]['profile']; ?>
			<small class="label pull-right bg-black">
				<?php echo $this->aData[$i]['count']; ?>
			</small>
			</a>
		</li>
		<?php endfor; ?>
	</ul>
</li>
<?php endif; ?>