<div class="unit footer-container">
    <div class="container" style="background:#3a3a3a;color:white;padding-top:15px;padding-bottom:15px;">
        <div class="unit horizontal-center layout on-2 columns">
            <div class="fixed column">
                <div style="font-size:20px;font-weight: bold;margin: 25px 10px;">
                    hukumonline<span style="color:#FF8C00">.com</span>
                </div>
            </div>
            <div class="fixed column" style="padding-left:30px;">
                <div class="footerMenu">
                    <ul>
                        <li><a href="">Awal</a></li>
                        <li>|</li>
                        <li><a href="">Tentang Kami</a></li>
                        <li>|</li>
                        <li><a href="">Kode Etik</a></li>
                        <li>|</li>
                        <li><a href="">Mitra Kami</a></li>
                    </ul>
                </div>
                <div style="padding-top:15px;">
                     Informasi yang tersedia di<a href="<?=$this->baseUrl(); ?>" class="footnote"> www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
                     namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
                     Akses dan penggunaan situs ini tunduk pada Syarat dan Ketentuan &copy; 2009
                </div>
            </div>
        </div>
    </div>
</div>